Repository StudyFork/GoogryAndroidArchitectureStudy, pull requests merged in 2019-06, with the labels that each got.

#45 Sample 프로젝트, 깃 이그노어 추가
  Nanamare/SampleProject/.gitignore
  Nanamare/SampleProject/.idea/codeStyles/Project.xml
  Nanamare/SampleProject/.idea/codeStyles/codeStyleConfig.xml
  Nanamare/SampleProject/.idea/gradle.xml
  Nanamare/SampleProject/.idea/misc.xml
  Nanamare/SampleProject/.idea/runConfigurations.xml
  Nanamare/SampleProject/app/.gitignore
  Nanamare/SampleProject/app/build.gradle
  Nanamare/SampleProject/app/proguard-rules.pro
  Nanamare/SampleProject/app/src/androidTest/java/com/nanamare/mac/sample/ExampleInstrumentedTest.kt
  Nanamare/SampleProject/app/src/main/AndroidManifest.xml
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/MainActivity.kt
  Nanamare/SampleProject/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  Nanamare/SampleProject/app/src/main/res/drawable/ic_launcher_background.xml
  Nanamare/SampleProject/app/src/main/res/layout/activity_main.xml
  Nanamare/SampleProject/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  Nanamare/SampleProject/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  Nanamare/SampleProject/app/src/main/res/mipmap-hdpi/ic_launcher.png
  Nanamare/SampleProject/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  Nanamare/SampleProject/app/src/main/res/mipmap-mdpi/ic_launcher.png
  Nanamare/SampleProject/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  Nanamare/SampleProject/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  Nanamare/SampleProject/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  Nanamare/SampleProject/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  Nanamare/SampleProject/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  Nanamare/SampleProject/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  Nanamare/SampleProject/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  Nanamare/SampleProject/app/src/main/res/values/colors.xml
  Nanamare/SampleProject/app/src/main/res/values/strings.xml
  Nanamare/SampleProject/app/src/main/res/values/styles.xml
  Nanamare/SampleProject/app/src/test/java/com/nanamare/mac/sample/ExampleUnitTest.kt
  Nanamare/SampleProject/build.gradle
  Nanamare/SampleProject/gradle.properties
  Nanamare/SampleProject/gradle/wrapper/gradle-wrapper.properties
  Nanamare/SampleProject/gradlew
  Nanamare/SampleProject/gradlew.bat
  Nanamare/SampleProject/settings.gradle
Labels: Mentor Needed, Merge Needed

#46 스터디 초반 셋팅 과정 완료
  zion830/StudyFirstProject/.gitignore
  zion830/StudyFirstProject/.idea/codeStyles/Project.xml
  zion830/StudyFirstProject/.idea/codeStyles/codeStyleConfig.xml
  zion830/StudyFirstProject/.idea/runConfigurations.xml
  zion830/StudyFirstProject/app/.gitignore
  zion830/StudyFirstProject/app/build.gradle
  zion830/StudyFirstProject/app/proguard-rules.pro
  zion830/StudyFirstProject/app/src/androidTest/java/com/studyfirstproject/ExampleInstrumentedTest.kt
  zion830/StudyFirstProject/app/src/main/AndroidManifest.xml
  zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/MainActivity.kt
  zion830/StudyFirstProject/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  zion830/StudyFirstProject/app/src/main/res/drawable/ic_launcher_background.xml
  zion830/StudyFirstProject/app/src/main/res/layout/activity_main.xml
  zion830/StudyFirstProject/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  zion830/StudyFirstProject/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  zion830/StudyFirstProject/app/src/main/res/mipmap-hdpi/ic_launcher.png
  zion830/StudyFirstProject/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  zion830/StudyFirstProject/app/src/main/res/mipmap-mdpi/ic_launcher.png
  zion830/StudyFirstProject/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  zion830/StudyFirstProject/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  zion830/StudyFirstProject/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  zion830/StudyFirstProject/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  zion830/StudyFirstProject/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  zion830/StudyFirstProject/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  zion830/StudyFirstProject/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  zion830/StudyFirstProject/app/src/main/res/values/colors.xml
  zion830/StudyFirstProject/app/src/main/res/values/strings.xml
  zion830/StudyFirstProject/app/src/main/res/values/styles.xml
  zion830/StudyFirstProject/app/src/test/java/com/studyfirstproject/ExampleUnitTest.kt
  zion830/StudyFirstProject/build.gradle
  zion830/StudyFirstProject/gradle.properties
  zion830/StudyFirstProject/gradle/wrapper/gradle-wrapper.properties
  zion830/StudyFirstProject/gradlew
  zion830/StudyFirstProject/gradlew.bat
  zion830/StudyFirstProject/settings.gradle
Labels: Mentor Needed, Merge Needed

#48 Create Android Studio Project
  BeokBeok/.gitignore
  BeokBeok/app/.gitignore
  BeokBeok/app/build.gradle
  BeokBeok/app/proguard-rules.pro
  BeokBeok/app/src/main/AndroidManifest.xml
  BeokBeok/app/src/main/java/com/architecturestudy/MainActivity.kt
  BeokBeok/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  BeokBeok/app/src/main/res/drawable/ic_launcher_background.xml
  BeokBeok/app/src/main/res/layout/activity_main.xml
  BeokBeok/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  BeokBeok/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  BeokBeok/app/src/main/res/mipmap-hdpi/ic_launcher.png
  BeokBeok/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  BeokBeok/app/src/main/res/mipmap-mdpi/ic_launcher.png
  BeokBeok/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  BeokBeok/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  BeokBeok/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  BeokBeok/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  BeokBeok/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  BeokBeok/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  BeokBeok/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  BeokBeok/app/src/main/res/values/colors.xml
  BeokBeok/app/src/main/res/values/strings.xml
  BeokBeok/app/src/main/res/values/styles.xml
  BeokBeok/build.gradle
  BeokBeok/gradle.properties
  BeokBeok/gradle/wrapper/gradle-wrapper.properties
  BeokBeok/gradlew
  BeokBeok/gradlew.bat
  BeokBeok/settings.gradle
Labels: Mentor Needed, Merge Needed

#49 set git ignore and add StudyFirst project
  NackUn/StudyFirst/.gitignore
  NackUn/StudyFirst/.gitignore.bak
  NackUn/StudyFirst/.idea/codeStyles/Project.xml
  NackUn/StudyFirst/.idea/codeStyles/codeStyleConfig.xml
  NackUn/StudyFirst/.idea/runConfigurations.xml
  NackUn/StudyFirst/app/.gitignore
  NackUn/StudyFirst/app/build.gradle
  NackUn/StudyFirst/app/proguard-rules.pro
  NackUn/StudyFirst/app/src/androidTest/java/sample/nackun/com/studyfirst/ExampleInstrumentedTest.kt
  NackUn/StudyFirst/app/src/main/AndroidManifest.xml
  NackUn/StudyFirst/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  NackUn/StudyFirst/app/src/main/res/drawable/ic_launcher_background.xml
  NackUn/StudyFirst/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  NackUn/StudyFirst/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  NackUn/StudyFirst/app/src/main/res/mipmap-hdpi/ic_launcher.png
  NackUn/StudyFirst/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  NackUn/StudyFirst/app/src/main/res/mipmap-mdpi/ic_launcher.png
  NackUn/StudyFirst/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  NackUn/StudyFirst/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  NackUn/StudyFirst/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  NackUn/StudyFirst/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  NackUn/StudyFirst/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  NackUn/StudyFirst/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  NackUn/StudyFirst/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  NackUn/StudyFirst/app/src/main/res/values/colors.xml
  NackUn/StudyFirst/app/src/main/res/values/strings.xml
  NackUn/StudyFirst/app/src/main/res/values/styles.xml
  NackUn/StudyFirst/app/src/test/java/sample/nackun/com/studyfirst/ExampleUnitTest.kt
  NackUn/StudyFirst/build.gradle
  NackUn/StudyFirst/gradle.properties
  NackUn/StudyFirst/gradle/wrapper/gradle-wrapper.properties
  NackUn/StudyFirst/gradlew
  NackUn/StudyFirst/gradlew.bat
  NackUn/StudyFirst/settings.gradle
Labels: Mentor Needed, Merge Needed

#50 gitignore파일 추가 및 프로젝트 추가
  .gitignore
  sport0102/.gitignore
  sport0102/.idea/codeStyles/Project.xml
  sport0102/.idea/codeStyles/codeStyleConfig.xml
  sport0102/.idea/encodings.xml
  sport0102/.idea/gradle.xml
  sport0102/.idea/misc.xml
  sport0102/.idea/runConfigurations.xml
  sport0102/app/.gitignore
  sport0102/app/build.gradle
  sport0102/app/proguard-rules.pro
  sport0102/app/src/androidTest/java/com/aiden/aiden/architecturepatternstudy/ExampleInstrumentedTest.kt
  sport0102/app/src/main/AndroidManifest.xml
  sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/MainActivity.kt
  sport0102/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  sport0102/app/src/main/res/drawable/ic_launcher_background.xml
  sport0102/app/src/main/res/layout/activity_main.xml
  sport0102/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  sport0102/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  sport0102/app/src/main/res/mipmap-hdpi/ic_launcher.png
  sport0102/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  sport0102/app/src/main/res/mipmap-mdpi/ic_launcher.png
  sport0102/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  sport0102/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  sport0102/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  sport0102/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  sport0102/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  sport0102/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  sport0102/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  sport0102/app/src/main/res/values/colors.xml
  sport0102/app/src/main/res/values/strings.xml
  sport0102/app/src/main/res/values/styles.xml
  sport0102/app/src/test/java/com/aiden/aiden/architecturepatternstudy/ExampleUnitTest.kt
  sport0102/build.gradle
  sport0102/gradle.properties
  sport0102/gradle/wrapper/gradle-wrapper.properties
  sport0102/gradlew
  sport0102/gradlew.bat
  sport0102/settings.gradle
Labels: Mentor Needed, Merge Needed

#51 AndroidArchitectureStdudy 프로젝트 및 git ignore 파일 추가
  AndroidArchitectureStudy/.gitignore
  AndroidArchitectureStudy/AndroidArchitectureStudy.iml
  AndroidArchitectureStudy/app/.gitignore
  AndroidArchitectureStudy/app/app.iml
  AndroidArchitectureStudy/app/build.gradle
  AndroidArchitectureStudy/app/build/generated/source/buildConfig/debug/org/study/kotlin/androidarchitecturestudy/BuildConfig.java
  AndroidArchitectureStudy/app/proguard-rules.pro
  AndroidArchitectureStudy/app/src/androidTest/java/org/study/kotlin/androidarchitecturestudy/ExampleInstrumentedTest.kt
  AndroidArchitectureStudy/app/src/main/AndroidManifest.xml
  AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/MainActivity.kt
  AndroidArchitectureStudy/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  AndroidArchitectureStudy/app/src/main/res/drawable/ic_launcher_background.xml
  AndroidArchitectureStudy/app/src/main/res/layout/activity_main.xml
  AndroidArchitectureStudy/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  AndroidArchitectureStudy/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  AndroidArchitectureStudy/app/src/main/res/mipmap-hdpi/ic_launcher.png
  AndroidArchitectureStudy/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  AndroidArchitectureStudy/app/src/main/res/mipmap-mdpi/ic_launcher.png
  AndroidArchitectureStudy/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  AndroidArchitectureStudy/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  AndroidArchitectureStudy/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  AndroidArchitectureStudy/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  AndroidArchitectureStudy/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  AndroidArchitectureStudy/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  AndroidArchitectureStudy/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  AndroidArchitectureStudy/app/src/main/res/values/colors.xml
  AndroidArchitectureStudy/app/src/main/res/values/strings.xml
  AndroidArchitectureStudy/app/src/main/res/values/styles.xml
  AndroidArchitectureStudy/app/src/test/java/org/study/kotlin/androidarchitecturestudy/ExampleUnitTest.kt
  AndroidArchitectureStudy/build.gradle
  AndroidArchitectureStudy/gradle.properties
  AndroidArchitectureStudy/gradle/wrapper/gradle-wrapper.jar
  AndroidArchitectureStudy/gradle/wrapper/gradle-wrapper.properties
  AndroidArchitectureStudy/gradlew
  AndroidArchitectureStudy/gradlew.bat
  AndroidArchitectureStudy/local.properties
  AndroidArchitectureStudy/settings.gradle
Labels: Mentor Needed, Merge Needed

#40 HW-3 mvvm (Delegates.observable) 변환
  sabgilhun/StudyProject/app/build.gradle
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/BindingAdapter.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/data/CoinRepository.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/data/CoinRepositoryImpl.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/data/model/Ticker.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/data/remote/CoinDataSource.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/data/remote/upbit/UpbitApi.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/data/remote/upbit/UpbitCoinDataSourceImpl.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/data/remote/upbit/request/UpbitTickerListRequest.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/ext/CompositeDisposableExt.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/ext/ObservableExt.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/base/BaseActivity.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/base/BaseContract.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/base/BaseFragment.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/base/BasePresenter.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/base/BaseViewModel.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/coinlist/CoinListContract.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/coinlist/CoinListFragment.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/coinlist/CoinListPresenter.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/coinlist/CoinListViewModel.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/home/HomeActivity.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/home/HomeContract.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/home/HomePresenter.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/home/HomeViewModel.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/searchcoin/SearchCoinActivity.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/searchcoin/SearchCoinContract.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/searchcoin/SearchCoinPresenter.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/searchcoin/SearchCoinViewModel.kt
  sabgilhun/StudyProject/app/src/main/res/layout/activity_main.xml
  sabgilhun/StudyProject/app/src/main/res/layout/activity_search_coin.xml
  sabgilhun/StudyProject/app/src/main/res/layout/fragmnet_coin_list.xml
  sabgilhun/StudyProject/app/src/main/res/values/strings.xml
  sabgilhun/StudyProject/build.gradle
Labels: Merge Needed

#38 HW-3 mvvm (Delegates.observable) 변환
  improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/base/BaseFragment.kt
  improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/data/source/UpbitDataSource.kt
  improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/data/source/UpbitRepository.kt
  improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/TickerContract.kt
  improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/TickerFragment.kt
  improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/TickerPresenter.kt
Labels: Mentor Needed, Merge Needed

#43 HW - 3 MVVM (Delgate Observable) 변환
  gongsulmin/StudyGong/.idea/codeStyles/Project.xml
  gongsulmin/StudyGong/app/src/main/AndroidManifest.xml
  gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/Injection.kt
  gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/adapter/CoinAdapter.kt
  gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/adapter/CoinMarketAdapter.kt
  gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/base/BaseDialog.kt
  gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/data/source/upbit/UpbitDataSource.kt
  gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/data/source/upbit/UpbitRepository.kt
  gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/mvp/presenter/coindetail/CoinDetailContract.kt
  gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/mvp/presenter/coindetail/CoinDetailPresenter.kt
  gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/mvp/presenter/coinlist/CoinListContract.kt
  gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/mvp/presenter/coinlist/CoinListPresenter.kt
  gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/mvp/presenter/coinmarketlist/CoinMarketContract.kt
  gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/mvp/presenter/coinmarketlist/CoinMarketPresenter.kt
  gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/mvp/view/CoinDetailDialog.kt
  gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/mvp/view/CoinListActivity.kt
  gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/mvp/view/CoinMarketDialog.kt
  gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/ui/CoinListActivity.kt
  gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/ui/CoinMarketDialog.kt
  gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/ui/CoinSearchDialog.kt
  gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/viewmodel/CoinViewModel.kt
Labels: Mentor Needed, Merge Needed

#44 HW-3 MVVM (Delegates.observable) 적용
  namjackson/ArchStudy/.idea/codeStyles/Project.xml
  namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/base/BaseContract.kt
  namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/base/BaseFragment.kt
  namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/data/source/local/TickerLocalDataSourceImpl.kt
  namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/data/source/remote/TickerRemoteDataSource.kt
  namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/data/source/remote/TickerRemoteDataSourceImpl.kt
  namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/view/coinlist/CoinListContract.kt
  namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/view/coinlist/CoinListFragment.kt
  namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/view/coinlist/CoinListPresenter.kt
Labels: Mentor Needed, Merge Needed

#52 HW-1 코인헬퍼 카피 앱 만들기
  .gitignore
  sport0102/.idea/codeStyles/Project.xml
  sport0102/app/build.gradle
  sport0102/app/src/androidTest/java/com/aiden/aiden/architecturepatternstudy/ExampleInstrumentedTest.kt
  sport0102/app/src/main/AndroidManifest.xml
  sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/MainActivity.kt
  sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/api/Retrofit.kt
  sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/api/UpbitApi.kt
  sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/api/model/MarketModel.kt
  sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/api/model/TickerModel.kt
  sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/data/enums/Market.kt
  sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/MainActivity.kt
  sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/MainFragment.kt
  sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/MainPagerAdapter.kt
  sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/TickerListAdapter.kt
  sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/util/StringUtil.kt
  sport0102/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  sport0102/app/src/main/res/drawable/ic_launcher_background.xml
  sport0102/app/src/main/res/drawable/stroke_1dp_radius.xml
  sport0102/app/src/main/res/layout/activity_main.xml
  sport0102/app/src/main/res/layout/fragment_main.xml
  sport0102/app/src/main/res/layout/item_main_tab.xml
  sport0102/app/src/main/res/layout/item_ticker.xml
  sport0102/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  sport0102/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  sport0102/app/src/main/res/values/colors.xml
  sport0102/app/src/main/res/values/strings.xml
  sport0102/app/src/main/res/values/styles.xml
  sport0102/app/src/test/java/com/aiden/aiden/architecturepatternstudy/ExampleUnitTest.kt
  sport0102/build.gradle
Labels: Mentor Needed, Merge Needed

#54 HW-1 코인 가격 보기 앱 제작
  zion830/StudyFirstProject/.idea/codeStyles/Project.xml
  zion830/StudyFirstProject/app/build.gradle
  zion830/StudyFirstProject/app/src/main/AndroidManifest.xml
  zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/MainActivity.kt
  zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/activity/MainActivity.kt
  zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/adapter/CoinRecyclerViewAdapter.kt
  zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/model/MarketModel.kt
  zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/model/TickerModel.kt
  zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/network/CoinApi.kt
  zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/network/RetrofitBuilder.kt
  zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/network/RetrofitCallback.kt
  zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/util/NumberFormatUtil.kt
  zion830/StudyFirstProject/app/src/main/res/drawable/ic_sort.xml
  zion830/StudyFirstProject/app/src/main/res/layout/activity_main.xml
  zion830/StudyFirstProject/app/src/main/res/layout/item_coin_info.xml
  zion830/StudyFirstProject/app/src/main/res/values/strings.xml
Labels: Mentor Needed, Merge Needed

#53 HW-1 Upbit API를 활용한 코인 마켓 리스트 조회 기능 구현
  BeokBeok/app/build.gradle
  BeokBeok/app/src/main/AndroidManifest.xml
  BeokBeok/app/src/main/java/com/architecturestudy/common/UpBitCommunicable.kt
  BeokBeok/app/src/main/java/com/architecturestudy/common/UpBitConnector.kt
  BeokBeok/app/src/main/java/com/architecturestudy/model/UpBitTickerResponse.kt
  BeokBeok/app/src/main/java/com/architecturestudy/view/DividerItemDecoration.kt
  BeokBeok/app/src/main/java/com/architecturestudy/view/MainActivity.kt
  BeokBeok/app/src/main/java/com/architecturestudy/view/MainAdapter.kt
  BeokBeok/app/src/main/java/com/architecturestudy/view/MainFragment.kt
  BeokBeok/app/src/main/res/drawable/line_divider.xml
  BeokBeok/app/src/main/res/layout/activity_main.xml
  BeokBeok/app/src/main/res/layout/fragment_main.xml
  BeokBeok/app/src/main/res/layout/rv_main_item.xml
  BeokBeok/app/src/main/res/values/strings.xml
Labels: Mentor Needed, Merge Needed

#55 HW-1 코인헬퍼 따라잡기
  NackUn/StudyFirst/.gitignore
  NackUn/StudyFirst/.gitignore.bak
  NackUn/StudyFirst/.idea/codeStyles/Project.xml
  NackUn/StudyFirst/.idea/codeStyles/codeStyleConfig.xml
  NackUn/StudyFirst/.idea/runConfigurations.xml
  NackUn/StudyFirst/app/.gitignore
  NackUn/StudyFirst/app/build.gradle
  NackUn/StudyFirst/app/proguard-rules.pro
  NackUn/StudyFirst/app/src/androidTest/java/sample/nackun/com/studyfirst/ExampleInstrumentedTest.kt
  NackUn/StudyFirst/app/src/main/AndroidManifest.xml
  NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/MainActivity.kt
  NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/TickerAdapter.kt
  NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/market/Market.kt
  NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/market/Ticker.kt
  NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/network/UpbitApi.kt
  NackUn/StudyFirst/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  NackUn/StudyFirst/app/src/main/res/drawable/ic_launcher_background.xml
  NackUn/StudyFirst/app/src/main/res/drawable/rounded.xml
  NackUn/StudyFirst/app/src/main/res/layout/activity_main.xml
  NackUn/StudyFirst/app/src/main/res/layout/ticker_item.xml
  NackUn/StudyFirst/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  NackUn/StudyFirst/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  NackUn/StudyFirst/app/src/main/res/mipmap-hdpi/ic_launcher.png
  NackUn/StudyFirst/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  NackUn/StudyFirst/app/src/main/res/mipmap-mdpi/ic_launcher.png
  NackUn/StudyFirst/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  NackUn/StudyFirst/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  NackUn/StudyFirst/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  NackUn/StudyFirst/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  NackUn/StudyFirst/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  NackUn/StudyFirst/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  NackUn/StudyFirst/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  NackUn/StudyFirst/app/src/main/res/values/colors.xml
  NackUn/StudyFirst/app/src/main/res/values/strings.xml
  NackUn/StudyFirst/app/src/main/res/values/styles.xml
  NackUn/StudyFirst/app/src/test/java/sample/nackun/com/studyfirst/ExampleUnitTest.kt
  NackUn/StudyFirst/build.gradle
  NackUn/StudyFirst/gradle.properties
  NackUn/StudyFirst/gradle/wrapper/gradle-wrapper.properties
  NackUn/StudyFirst/gradlew
  NackUn/StudyFirst/gradlew.bat
  NackUn/StudyFirst/settings.gradle
Labels: Mentor Needed, Merge Needed

#60 HW-4 mvvm + LiveData 수정
  sabgilhun/StudyProject/app/build.gradle
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/BindingAdapter.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/adapter/CoinListPagerAdapter.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/ext/RecyclerViewExt.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/ext/ViewExt.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/utils/SingleLiveEvent.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/base/BaseActivity.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/base/BaseFragment.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/base/BaseViewModel.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/coinlist/CoinListFragment.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/coinlist/CoinListViewModel.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/home/HomeActivity.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/home/HomeViewModel.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/searchcoin/SearchCoinActivity.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/searchcoin/SearchCoinViewModel.kt
  sabgilhun/StudyProject/app/src/main/res/layout/activity_main.xml
  sabgilhun/StudyProject/app/src/main/res/layout/activity_search_coin.xml
  sabgilhun/StudyProject/app/src/main/res/layout/fragmnet_coin_list.xml
Labels: Mentor Needed, Merge Needed

#59 HW-1 숙제
  Nanamare/SampleProject/app/build.gradle
  Nanamare/SampleProject/app/src/androidTest/java/com/nanamare/mac/sample/ExampleInstrumentedTest.kt
  Nanamare/SampleProject/app/src/main/AndroidManifest.xml
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/AppApplication.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/MainActivity.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/adapter/BaseAdapter.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/adapter/MarketListViewPager.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/adapter/TickerAdapter.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/adapter/viewholder/BaseViewHolder.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/adapter/viewholder/TickerViewHolder.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/api/DisposableManager.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/api/ServiceDefine.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/api/upbit/MarketModel.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/api/upbit/TickerModel.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/api/upbit/UpBitService.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/api/upbit/UpBitServiceManager.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/ui/CoinFragment.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/ui/MainActivity.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/ui/MarketListFragment.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/ui/ProgressDialogFragment.kt
  Nanamare/SampleProject/app/src/main/res/layout/activity_main.xml
  Nanamare/SampleProject/app/src/main/res/layout/dialog_loading.xml
  Nanamare/SampleProject/app/src/main/res/layout/empty_coin_list.xml
  Nanamare/SampleProject/app/src/main/res/layout/fragment_coin_list.xml
  Nanamare/SampleProject/app/src/main/res/layout/fragment_market_list_viewpager.xml
  Nanamare/SampleProject/app/src/main/res/layout/item_ticker.xml
  Nanamare/SampleProject/app/src/main/res/values/colors.xml
  Nanamare/SampleProject/app/src/main/res/values/strings.xml
  Nanamare/SampleProject/app/src/test/java/com/nanamare/mac/sample/ExampleUnitTest.kt
  Nanamare/SampleProject/gradle.properties
Labels: Mentor Needed, Merge Needed

#61 HW - 4 Mvvm LiveData로 변경
  gongsulmin/StudyGong/app/build.gradle
  gongsulmin/StudyGong/app/src/androidTest/java/my/gong/studygong/ExampleInstrumentedTest.kt
  gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/BindingAdapter.kt
  gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/SingleLiveEvent.kt
  gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/adapter/CoinAdapter.kt
  gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/adapter/CoinMarketAdapter.kt
  gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/base/BaseDialog.kt
  gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/ui/CoinListActivity.kt
  gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/ui/CoinMarketDialog.kt
  gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/ui/CoinSearchDialog.kt
  gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/viewmodel/CoinViewModel.kt
  gongsulmin/StudyGong/app/src/main/res/layout/activity_main.xml
  gongsulmin/StudyGong/app/src/main/res/layout/dialog_coin_detail.xml
  gongsulmin/StudyGong/app/src/main/res/layout/dialog_coin_market.xml
  gongsulmin/StudyGong/app/src/main/res/layout/item_coin_market.xml
  gongsulmin/StudyGong/app/src/main/res/layout/item_ticker.xml
  gongsulmin/StudyGong/gradle.properties
Labels: Mentor Needed, Merge Needed

#57 HW-4 mvvm + LiveData 수정
  improve777/GAASProject/app/build.gradle
  improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/base/BaseFragment.kt
  improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/data/source/UpbitDataSource.kt
  improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/data/source/UpbitRepository.kt
  improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ext/EditTextExt.kt
  improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ext/RecyclerViewExt.kt
  improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/network/NetworkManager.kt
  improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/network/UpbitApi.kt
  improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/TickerAdapter.kt
  improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/TickerFragment.kt
  improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/TickerViewModel.kt
  improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/util/Event.kt
  improve777/GAASProject/app/src/main/res/layout/dialog_ticker_search.xml
  improve777/GAASProject/app/src/main/res/layout/fragment_ticker.xml
Labels: Mentor Needed, Merge Needed

#62 HW-4 MVVM- LiveData
  namjackson/ArchStudy/app/build.gradle
  namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/base/BaseFragment.kt
  namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/base/BaseViewModel.kt
  namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/util/DatabindingUtil.kt
  namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/util/Event.kt
  namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/view/coinlist/CoinListFragment.kt
  namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/view/coinlist/CoinListViewModel.kt
  namjackson/ArchStudy/app/src/main/res/layout/fragment_coin_list.xml
Labels: Mentor Needed, Merge Needed

#72 HW - 5 AAC ViewModel
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/adapter/TickerAdapter.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/data/enums/BaseCurrency.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/data/enums/SortingCriteria.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/data/model/Ticker.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/ext/RecyclerViewExt.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/ext/TextViewExt.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/ext/ViewExt.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/base/BaseActivity.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/base/BaseFragment.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/base/BaseViewModel.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/coinlist/CoinListFragment.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/coinlist/CoinListViewModel.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/coinlist/CoinListViewModelFactory.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/home/HomeActivity.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/home/HomeViewModel.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/home/HomeViewModelFactory.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/searchcoin/SearchCoinActivity.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/searchcoin/SearchCoinViewModelFactory.kt
  sabgilhun/StudyProject/app/src/main/res/drawable/selector_order_indicator.xml
  sabgilhun/StudyProject/app/src/main/res/drawable/vector_arrow_drop_down.xml
  sabgilhun/StudyProject/app/src/main/res/drawable/vector_arrow_drop_up.xml
  sabgilhun/StudyProject/app/src/main/res/drawable/vector_search.xml
  sabgilhun/StudyProject/app/src/main/res/layout/activity_main.xml
  sabgilhun/StudyProject/app/src/main/res/layout/activity_search_coin.xml
  sabgilhun/StudyProject/app/src/main/res/layout/fragmnet_coin_list.xml
  sabgilhun/StudyProject/app/src/main/res/layout/item_ticker.xml
  sabgilhun/StudyProject/app/src/main/res/menu/menu_home.xml
  sabgilhun/StudyProject/app/src/main/res/values/colors.xml
  sabgilhun/StudyProject/app/src/main/res/values/strings.xml
  sabgilhun/StudyProject/app/src/main/res/values/styles.xml
Labels: Mentor Needed, Merge Needed

#70 HW - 5 AAC ViewModel 변경
  gongsulmin/StudyGong/app/build.gradle
  gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/ui/CoinListActivity.kt
  gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/ui/CoinMarketDialog.kt
  gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/ui/CoinSearchDialog.kt
  gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/viewmodel/CoinViewModel.kt
  gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/viewmodel/ViewModelFactoryImpl.kt
Labels: Mentor Needed, Merge Needed

#69 HW-5 AAC-ViewModel 적용
  namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/base/BaseViewModel.kt
  namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/data/model/Ticker.kt
  namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/util/DatabindingUtil.kt
  namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/util/ViewModelFactory.kt
  namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/view/coinlist/CoinListFragment.kt
  namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/view/coinlist/CoinListViewModel.kt
Labels: Mentor Needed, Merge Needed

#65 HW-2 MVP 변환
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/AppApplication.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/adapter/MarketListViewPager.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/adapter/TickerAdapter.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/adapter/viewholder/BaseViewHolder.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/adapter/viewholder/TickerViewHolder.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/api/ServiceDefine.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/base/BaseActivity.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/base/BaseAdapter.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/base/BaseFragment.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/base/BasePresenter.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/base/BaseSource.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/base/BaseView.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/base/BaseViewHolder.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/data/coin/CoinRemoteDataSource.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/data/coin/CoinRepository.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/data/coin/CoinSource.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/data/market/MarketRemoteDataSource.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/data/market/MarketRepository.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/data/market/MarketSource.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/ui/MainActivity.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/ui/coin/CoinContract.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/ui/coin/CoinFragment.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/ui/coin/CoinPresenter.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/ui/market/MarketContract.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/ui/market/MarketListFragment.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/ui/market/MarketPresenter.kt
  Nanamare/SampleProject/app/src/main/res/values/strings.xml
Labels: Mentor Needed, Merge Needed

#75 HW-7 1기 스터디 후기 작성
  README.md
  improve777/README.md
  improve777/주차별_후기.md
Labels: Mentor Needed

#78 HW-7 1기 스터디 후기 작성
  README.md
Labels: Merge Needed

#63 HW-2 MVP 패턴 적용
  BeokBeok/.idea/codeStyles/Project.xml
  BeokBeok/.idea/codeStyles/codeStyleConfig.xml
  BeokBeok/.idea/runConfigurations.xml
  BeokBeok/app/build.gradle
  BeokBeok/app/src/androidTest/java/com/architecturestudy/ExampleInstrumentedTest.kt
  BeokBeok/app/src/main/AndroidManifest.xml
  BeokBeok/app/src/main/java/com/architecturestudy/base/BaseActivity.kt
  BeokBeok/app/src/main/java/com/architecturestudy/base/BaseFragment.kt
  BeokBeok/app/src/main/java/com/architecturestudy/base/BasePresenter.kt
  BeokBeok/app/src/main/java/com/architecturestudy/base/BaseView.kt
  BeokBeok/app/src/main/java/com/architecturestudy/common/UpBitCommunicable.kt
  BeokBeok/app/src/main/java/com/architecturestudy/common/UpBitConnector.kt
  BeokBeok/app/src/main/java/com/architecturestudy/data/common/MarketTypes.kt
  BeokBeok/app/src/main/java/com/architecturestudy/data/upbit/UpbitRepository.kt
  BeokBeok/app/src/main/java/com/architecturestudy/data/upbit/UpbitTicker.kt
  BeokBeok/app/src/main/java/com/architecturestudy/data/upbit/service/UpbitRetrofit.kt
  BeokBeok/app/src/main/java/com/architecturestudy/data/upbit/service/UpbitService.kt
  BeokBeok/app/src/main/java/com/architecturestudy/data/upbit/source/UpbitDataSource.kt
  BeokBeok/app/src/main/java/com/architecturestudy/data/upbit/source/UpbitRetrofitDataSource.kt
  BeokBeok/app/src/main/java/com/architecturestudy/model/UpBitTickerResponse.kt
  BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/UpbitActivity.kt
  BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/UpbitContract.kt
  BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/UpbitFragment.kt
  BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/UpbitPresenter.kt
  BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/recyclerview/DividerItemDecoration.kt
  BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/recyclerview/UpbitAdapter.kt
  BeokBeok/app/src/main/java/com/architecturestudy/util/NumberFormatter.kt
  BeokBeok/app/src/main/java/com/architecturestudy/view/MainActivity.kt
  BeokBeok/app/src/main/java/com/architecturestudy/view/MainAdapter.kt
  BeokBeok/app/src/main/java/com/architecturestudy/view/MainFragment.kt
  BeokBeok/app/src/main/res/layout/activity_upbit.xml
  BeokBeok/app/src/main/res/layout/fragment_main.xml
  BeokBeok/app/src/main/res/layout/fragment_upbit.xml
  BeokBeok/app/src/main/res/layout/rv_upbit_item.xml
  BeokBeok/app/src/main/res/values-ko/strings.xml
  BeokBeok/app/src/main/res/values/colors.xml
  BeokBeok/app/src/main/res/values/strings.xml
  BeokBeok/app/src/test/java/com/architecturestudy/ExampleUnitTest.kt
  BeokBeok/build.gradle
  BeokBeok/gradle.properties
Labels: Mentor Needed, Merge Needed

#74 HW-6 DI-koin 적용
  improve777/GAASProject/app/build.gradle
  improve777/GAASProject/app/src/main/AndroidManifest.xml
  improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/MyApplication.kt
  improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/module/NetworkModule.kt
  improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/module/RepositoryModule.kt
  improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/module/ViewModelModule.kt
  improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/TickerFragment.kt
  improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/marketchoice/MarketChoiceDialogFragment.kt
  improve777/GAASProject/app/src/main/java/dev/daeyeon/gaasproject/ui/ticker/search/TickerSearchDialogFragment.kt
  improve777/GAASProject/build.gradle
Labels: Mentor Needed, Merge Needed

#64 HW-2 MVP 패턴 적용
  sport0102/.idea/misc.xml
  sport0102/app/build.gradle
  sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/api/Retrofit.kt
  sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/api/UpbitApi.kt
  sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/api/model/MarketModel.kt
  sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/api/model/MarketResponse.kt
  sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/api/model/TickerModel.kt
  sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/api/model/TickerResponse.kt
  sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/base/BaseFragment.kt
  sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/base/BasePresenter.kt
  sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/base/BaseView.kt
  sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/data/model/TickerModel.kt
  sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/data/source/UpbitDataSource.kt
  sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/data/source/UpbitRepository.kt
  sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/data/source/remote/UpbitRemoteDataSource.kt
  sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/MainActivity.kt
  sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/MainContract.kt
  sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/MainFragment.kt
  sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/MainPagerAdapter.kt
  sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/MainPresenter.kt
  sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/TabSelectedListener.kt
  sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/TickerListAdapter.kt
  sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/util/StringUtil.kt
  sport0102/app/src/main/res/layout/activity_main.xml
  sport0102/app/src/main/res/layout/fragment_main.xml
  sport0102/app/src/main/res/layout/item_main_tab.xml
  sport0102/app/src/main/res/layout/item_ticker.xml
  sport0102/app/src/main/res/values/strings.xml
Labels: Mentor Needed, Merge Needed

#68 HW-2 MVP 패턴 적용하기
  zion830/StudyFirstProject/.idea/codeStyles/Project.xml
  zion830/StudyFirstProject/app/src/main/AndroidManifest.xml
  zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/BasePresenter.kt
  zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/BaseView.kt
  zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/activity/MainActivity.kt
  zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/adapter/CoinRecyclerViewAdapter.kt
  zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/data/CoinDataSource.kt
  zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/data/CoinRepository.kt
  zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/data/model/MarketModel.kt
  zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/data/model/TickerModel.kt
  zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/network/CoinApi.kt
  zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/network/RetrofitBuilder.kt
  zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/network/RetrofitCallback.kt
  zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/showcoin/CoinContract.kt
  zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/showcoin/CoinPresenter.kt
  zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/showcoin/view/MainActivity.kt
  zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/util/NumberFormatUtil.kt
  zion830/StudyFirstProject/app/src/main/res/layout/activity_main.xml
  zion830/StudyFirstProject/app/src/main/res/layout/item_coin_info.xml
Labels: Mentor Needed, Merge Needed

#77 HW 6 Koin 적용
  sabgilhun/StudyProject/app/build.gradle
  sabgilhun/StudyProject/app/src/main/AndroidManifest.xml
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/CoinApplication.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/data/CoinRepositoryImpl.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/data/remote/upbit/UpbitCoinDataSourceImpl.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/di/DataSourceModule.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/di/NetworkModule.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/di/RepositoryModule.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/di/ViewModelModule.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/base/BaseActivity.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/base/BaseFragment.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/base/BaseViewModel.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/coinlist/CoinListFragment.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/coinlist/CoinListViewModelFactory.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/home/HomeActivity.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/home/HomeViewModelFactory.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/searchcoin/SearchCoinActivity.kt
  sabgilhun/StudyProject/app/src/main/java/ado/sabgil/studyproject/view/searchcoin/SearchCoinViewModelFactory.kt
Labels: Mentor Needed, Merge Needed

#67 HW-2 MVP 패턴 적용
  NackUn/StudyFirst/app/src/main/AndroidManifest.xml
  NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/Base/BaseActivity.kt
  NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/Base/BaseFragment.kt
  NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/Base/BasePresenter.kt
  NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/Base/BaseView.kt
  NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/MainActivity.kt
  NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/TickerAdapter.kt
  NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/data/DataSource.kt
  NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/data/Repository.kt
  NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/data/remote/RemoteDataSource.kt
  NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/main/MainActivity.kt
  NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/main/MainContract.kt
  NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/main/MainFragment.kt
  NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/main/MainPresenter.kt
  NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/market/Market.kt
  NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/network/UpbitApi.kt
  NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/TickerAdapter.kt
  NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/util/TickerFormatter.kt
  NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/vo/Market.kt
  NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/vo/Ticker.kt
  NackUn/StudyFirst/app/src/main/res/layout/activity_main.xml
  NackUn/StudyFirst/app/src/main/res/layout/main_fragment.xml
  NackUn/StudyFirst/app/src/main/res/layout/ticker_item.xml
  NackUn/StudyFirst/app/src/test/java/sample/nackun/com/studyfirst/ExampleUnitTest.kt
Labels: Mentor Needed, Merge Needed
