Repository StudyFork/GoogryAndroidArchitectureStudy, pull requests merged in 2019-07, with the labels that each got.

#79 HW - 6 Koin 적용
  gongsulmin/StudyGong/app/build.gradle
  gongsulmin/StudyGong/app/src/main/AndroidManifest.xml
  gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/Injection.kt
  gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/MyApplication.kt
  gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/data/source/upbit/UpbitRepository.kt
  gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/di/NetworkModule.kt
  gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/di/RepositoryModule.kt
  gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/di/ViewModelModule.kt
  gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/ui/CoinListActivity.kt
  gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/ui/CoinMarketDialog.kt
  gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/ui/CoinSearchDialog.kt
  gongsulmin/StudyGong/app/src/main/java/my/gong/studygong/viewmodel/ViewModelFactoryImpl.kt
Labels: Mentor Needed, Merge Needed

#83 HW-3 MVP 패턴 적용 및 코드 리뷰 적용
  machine-human/AndroidArchitectureStudy/.idea/runConfigurations.xml
  machine-human/AndroidArchitectureStudy/app/build.gradle
  machine-human/AndroidArchitectureStudy/app/src/main/AndroidManifest.xml
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/adapter/recyclerviewadapter/MainListAdapter.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/adapter/viewpageradapter/MainViewPagerAdapter.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/api/UPbitApi.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/api/retorifit/RetrofitBuilder.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/base/BaseActivity.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/base/BaseDataSource.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/base/BaseFragment.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/base/BasePresenter.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/base/BaseView.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/data/TickerRepository.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/data/enum/TabTitle.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/data/source/remote/TickerRemoteDataSource.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/ui/activity/MainActivity.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/ui/fragment/MainFragment.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/util/FormatUtil.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/view/activity/main/MainActivity.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/view/activity/main/MainContract.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/view/activity/main/MainFragment.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/view/activity/main/MainPresenter.kt
  machine-human/AndroidArchitectureStudy/app/src/main/res/layout/activity_main.xml
  machine-human/AndroidArchitectureStudy/app/src/main/res/layout/fragment_main.xml
  machine-human/AndroidArchitectureStudy/app/src/main/res/layout/item_ticker.xml
Labels: Mentor Needed, Review Needed

#91 스터디 후기 작성입니다!
  README.md
Labels: Mentor Needed

#76 HW-6 DI (Koin) 적용
  namjackson/ArchStudy/app/build.gradle
  namjackson/ArchStudy/app/src/main/AndroidManifest.xml
  namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/base/BaseApplication.kt
  namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/di/DataSourceModule.kt
  namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/di/NetworkModule.kt
  namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/di/RepositoryModule.kt
  namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/di/ViewModelModule.kt
  namjackson/ArchStudy/app/src/main/java/com/namjackson/archstudy/view/coinlist/CoinListFragment.kt
  namjackson/ArchStudy/build.gradle
Labels: Mentor Needed, Review Needed

#86 Add Branch / Edit Readme.md
  README.md
  zojae031/README.md
Labels: Mentor Needed, Merge Needed

#87 fist init
  README.md
  onemask/README.md
Labels: Mentor Needed, Merge Needed

#96 HW-4 MVVM + DataBinding 적용
  machine-human/AndroidArchitectureStudy/.idea/codeStyles/Project.xml
  machine-human/AndroidArchitectureStudy/app/build.gradle
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/base/BaseFragment.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/base/BasePresenter.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/base/BaseView.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/view/activity/main/MainContract.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/view/activity/main/MainFragment.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/view/activity/main/MainPresenter.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/view/activity/main/MainViewModel.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/view/bindingadapter/bindTickerData.kt
  machine-human/AndroidArchitectureStudy/app/src/main/res/layout/fragment_main.xml
  machine-human/AndroidArchitectureStudy/build.gradle
Labels: Mentor Needed, Review Needed

#89 본인 기수 항목에 이름/프로필링크/폴더링크를 추가
  README.md
  dlwls5201/README.md
Labels: Mentor Needed, Merge Needed

#106 사전과제!
  README.md
  ganghee/README.md
Labels: Mentor Needed, Merge Needed

#111 Create Folder & Update README.md
  README.md
  preludezdev/README.md
Labels: Mentor Needed, Merge Needed

#112 Class03/init readme
  README.md
  wkdehdlr/README.md
Labels: Mentor Needed, Merge Needed

#90 Create README.md
  README.md
  wswon/README.md
Labels: Mentor Needed, Merge Needed

#114 HW 사전과제(스터디 초반 셋팅)
  dlwls5201/MyArchitecture/.gitignore
  dlwls5201/MyArchitecture/.idea/codeStyles/Project.xml
  dlwls5201/MyArchitecture/.idea/codeStyles/codeStyleConfig.xml
  dlwls5201/MyArchitecture/.idea/gradle.xml
  dlwls5201/MyArchitecture/.idea/runConfigurations.xml
  dlwls5201/MyArchitecture/.idea/vcs.xml
  dlwls5201/MyArchitecture/app/.gitignore
  dlwls5201/MyArchitecture/app/build.gradle
  dlwls5201/MyArchitecture/app/proguard-rules.pro
  dlwls5201/MyArchitecture/app/src/androidTest/java/study/architecture/myarchitecture/ExampleInstrumentedTest.kt
  dlwls5201/MyArchitecture/app/src/main/AndroidManifest.xml
  dlwls5201/MyArchitecture/app/src/main/java/study/architecture/myarchitecture/MainActivity.kt
  dlwls5201/MyArchitecture/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  dlwls5201/MyArchitecture/app/src/main/res/drawable/ic_launcher_background.xml
  dlwls5201/MyArchitecture/app/src/main/res/layout/activity_main.xml
  dlwls5201/MyArchitecture/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  dlwls5201/MyArchitecture/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  dlwls5201/MyArchitecture/app/src/main/res/mipmap-hdpi/ic_launcher.png
  dlwls5201/MyArchitecture/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  dlwls5201/MyArchitecture/app/src/main/res/mipmap-mdpi/ic_launcher.png
  dlwls5201/MyArchitecture/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  dlwls5201/MyArchitecture/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  dlwls5201/MyArchitecture/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  dlwls5201/MyArchitecture/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  dlwls5201/MyArchitecture/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  dlwls5201/MyArchitecture/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  dlwls5201/MyArchitecture/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  dlwls5201/MyArchitecture/app/src/main/res/values/colors.xml
  dlwls5201/MyArchitecture/app/src/main/res/values/strings.xml
  dlwls5201/MyArchitecture/app/src/main/res/values/styles.xml
  dlwls5201/MyArchitecture/app/src/test/java/study/architecture/myarchitecture/ExampleUnitTest.kt
  dlwls5201/MyArchitecture/build.gradle
  dlwls5201/MyArchitecture/gradle.properties
  dlwls5201/MyArchitecture/gradle/wrapper/gradle-wrapper.jar
  dlwls5201/MyArchitecture/gradle/wrapper/gradle-wrapper.properties
  dlwls5201/MyArchitecture/gradlew
  dlwls5201/MyArchitecture/gradlew.bat
  dlwls5201/MyArchitecture/settings.gradle
Labels: Mentor Needed, Merge Needed

#92 HW-5 MVVM Review 적용
  BeokBeok/.idea/codeStyles/Project.xml
  BeokBeok/app/build.gradle
  BeokBeok/app/src/main/java/com/architecturestudy/base/BaseFragment.kt
  BeokBeok/app/src/main/java/com/architecturestudy/base/BasePresenter.kt
  BeokBeok/app/src/main/java/com/architecturestudy/base/BaseView.kt
  BeokBeok/app/src/main/java/com/architecturestudy/base/BaseViewModel.kt
  BeokBeok/app/src/main/java/com/architecturestudy/data/common/MarketTypes.kt
  BeokBeok/app/src/main/java/com/architecturestudy/data/upbit/UpbitRepository.kt
  BeokBeok/app/src/main/java/com/architecturestudy/data/upbit/source/UpbitDataSource.kt
  BeokBeok/app/src/main/java/com/architecturestudy/data/upbit/source/UpbitRetrofitDataSource.kt
  BeokBeok/app/src/main/java/com/architecturestudy/ext/RecyclerViewExt.kt
  BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/UpbitContract.kt
  BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/UpbitFragment.kt
  BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/UpbitPresenter.kt
  BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/UpbitViewModel.kt
  BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/adapter/UpbitAdapter.kt
  BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/recyclerview/DividerItemDecoration.kt
  BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/recyclerview/UpbitAdapter.kt
  BeokBeok/app/src/main/res/drawable/line_divider.xml
  BeokBeok/app/src/main/res/layout/fragment_upbit.xml
  BeokBeok/app/src/main/res/layout/rv_upbit_item.xml
  BeokBeok/app/src/test/java/com/architecturestudy/ExampleUnitTest.kt
  BeokBeok/build.gradle
  BeokBeok/gradle/wrapper/gradle-wrapper.properties
Labels: Mentor Needed, Merge Needed

#118 안드로이드 프로젝트 생성 및 gitignore 추가
  wkdehdlr/AndroidStudy/.gitignore
  wkdehdlr/AndroidStudy/.idea/codeStyles/Project.xml
  wkdehdlr/AndroidStudy/.idea/codeStyles/codeStyleConfig.xml
  wkdehdlr/AndroidStudy/.idea/runConfigurations.xml
  wkdehdlr/AndroidStudy/app/.gitignore
  wkdehdlr/AndroidStudy/app/build.gradle
  wkdehdlr/AndroidStudy/app/proguard-rules.pro
  wkdehdlr/AndroidStudy/app/src/androidTest/java/kr/schoolsharing/androidstudy/ExampleInstrumentedTest.kt
  wkdehdlr/AndroidStudy/app/src/main/AndroidManifest.xml
  wkdehdlr/AndroidStudy/app/src/main/java/kr/schoolsharing/androidstudy/MainActivity.kt
  wkdehdlr/AndroidStudy/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  wkdehdlr/AndroidStudy/app/src/main/res/drawable/ic_launcher_background.xml
  wkdehdlr/AndroidStudy/app/src/main/res/layout/activity_main.xml
  wkdehdlr/AndroidStudy/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  wkdehdlr/AndroidStudy/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  wkdehdlr/AndroidStudy/app/src/main/res/mipmap-hdpi/ic_launcher.png
  wkdehdlr/AndroidStudy/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  wkdehdlr/AndroidStudy/app/src/main/res/mipmap-mdpi/ic_launcher.png
  wkdehdlr/AndroidStudy/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  wkdehdlr/AndroidStudy/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  wkdehdlr/AndroidStudy/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  wkdehdlr/AndroidStudy/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  wkdehdlr/AndroidStudy/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  wkdehdlr/AndroidStudy/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  wkdehdlr/AndroidStudy/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  wkdehdlr/AndroidStudy/app/src/main/res/values/colors.xml
  wkdehdlr/AndroidStudy/app/src/main/res/values/strings.xml
  wkdehdlr/AndroidStudy/app/src/main/res/values/styles.xml
  wkdehdlr/AndroidStudy/app/src/test/java/kr/schoolsharing/androidstudy/ExampleUnitTest.kt
  wkdehdlr/AndroidStudy/build.gradle
  wkdehdlr/AndroidStudy/gradle.properties
  wkdehdlr/AndroidStudy/gradle/wrapper/gradle-wrapper.jar
  wkdehdlr/AndroidStudy/gradle/wrapper/gradle-wrapper.properties
  wkdehdlr/AndroidStudy/gradlew
  wkdehdlr/AndroidStudy/gradlew.bat
  wkdehdlr/AndroidStudy/settings.gradle
Labels: Mentor Needed, Merge Needed

#115 초기 프로젝트 생성 및 gitignore 적용 (사전과제-2)
  preludezdev/ArchitectureStudy/.gitignore
  preludezdev/ArchitectureStudy/.idea/codeStyles/Project.xml
  preludezdev/ArchitectureStudy/.idea/codeStyles/codeStyleConfig.xml
  preludezdev/ArchitectureStudy/.idea/runConfigurations.xml
  preludezdev/ArchitectureStudy/app/.gitignore
  preludezdev/ArchitectureStudy/app/build.gradle
  preludezdev/ArchitectureStudy/app/proguard-rules.pro
  preludezdev/ArchitectureStudy/app/src/androidTest/java/com/example/architecturestudy/ExampleInstrumentedTest.kt
  preludezdev/ArchitectureStudy/app/src/main/AndroidManifest.xml
  preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/MainActivity.kt
  preludezdev/ArchitectureStudy/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  preludezdev/ArchitectureStudy/app/src/main/res/drawable/ic_launcher_background.xml
  preludezdev/ArchitectureStudy/app/src/main/res/layout/activity_main.xml
  preludezdev/ArchitectureStudy/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  preludezdev/ArchitectureStudy/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  preludezdev/ArchitectureStudy/app/src/main/res/mipmap-hdpi/ic_launcher.png
  preludezdev/ArchitectureStudy/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  preludezdev/ArchitectureStudy/app/src/main/res/mipmap-mdpi/ic_launcher.png
  preludezdev/ArchitectureStudy/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  preludezdev/ArchitectureStudy/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  preludezdev/ArchitectureStudy/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  preludezdev/ArchitectureStudy/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  preludezdev/ArchitectureStudy/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  preludezdev/ArchitectureStudy/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  preludezdev/ArchitectureStudy/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  preludezdev/ArchitectureStudy/app/src/main/res/values/colors.xml
  preludezdev/ArchitectureStudy/app/src/main/res/values/strings.xml
  preludezdev/ArchitectureStudy/app/src/main/res/values/styles.xml
  preludezdev/ArchitectureStudy/app/src/test/java/com/example/architecturestudy/ExampleUnitTest.kt
  preludezdev/ArchitectureStudy/build.gradle
  preludezdev/ArchitectureStudy/gradle.properties
  preludezdev/ArchitectureStudy/gradle/wrapper/gradle-wrapper.jar
  preludezdev/ArchitectureStudy/gradle/wrapper/gradle-wrapper.properties
  preludezdev/ArchitectureStudy/gradlew
  preludezdev/ArchitectureStudy/gradlew.bat
  preludezdev/ArchitectureStudy/settings.gradle
Labels: Mentor Needed, Merge Needed

#117 Class03/zojae031
  zojae031/Project/.gitignore
  zojae031/Project/.idea/codeStyles/Project.xml
  zojae031/Project/.idea/codeStyles/codeStyleConfig.xml
  zojae031/Project/.idea/gradle.xml
  zojae031/Project/.idea/misc.xml
  zojae031/Project/.idea/runConfigurations.xml
  zojae031/Project/app/.gitignore
  zojae031/Project/app/build.gradle
  zojae031/Project/app/proguard-rules.pro
  zojae031/Project/app/src/androidTest/java/study/architecture/ExampleInstrumentedTest.kt
  zojae031/Project/app/src/main/AndroidManifest.xml
  zojae031/Project/app/src/main/java/study/architecture/MainActivity.kt
  zojae031/Project/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  zojae031/Project/app/src/main/res/drawable/ic_launcher_background.xml
  zojae031/Project/app/src/main/res/layout/activity_main.xml
  zojae031/Project/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  zojae031/Project/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  zojae031/Project/app/src/main/res/mipmap-hdpi/ic_launcher.png
  zojae031/Project/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  zojae031/Project/app/src/main/res/mipmap-mdpi/ic_launcher.png
  zojae031/Project/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  zojae031/Project/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  zojae031/Project/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  zojae031/Project/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  zojae031/Project/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  zojae031/Project/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  zojae031/Project/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  zojae031/Project/app/src/main/res/values/colors.xml
  zojae031/Project/app/src/main/res/values/strings.xml
  zojae031/Project/app/src/main/res/values/styles.xml
  zojae031/Project/app/src/test/java/study/architecture/ExampleUnitTest.kt
  zojae031/Project/build.gradle
  zojae031/Project/gradle.properties
  zojae031/Project/gradle/wrapper/gradle-wrapper.jar
  zojae031/Project/gradle/wrapper/gradle-wrapper.properties
  zojae031/Project/gradlew
  zojae031/Project/gradlew.bat
  zojae031/Project/settings.gradle
Labels: Mentor Needed, Merge Needed

#88 HW-3 mvvm 변환
  Nanamare/SampleProject/app/build.gradle
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/adapter/TickerAdapter.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/adapter/viewholder/TickerViewHolder.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/api/upbit/CoinModel.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/api/upbit/UpBitService.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/api/upbit/UpBitServiceManager.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/base/BaseActivity.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/base/BaseAdapter.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/base/BaseFragment.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/base/BasePresenter.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/base/BaseView.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/base/BaseViewHolder.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/base/BaseViewModel.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/data/coin/CoinRemoteDataSource.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/data/coin/CoinRepository.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/data/coin/CoinSource.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/ext/RecyclerViewExt.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/ui/MainActivity.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/ui/coin/CoinContract.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/ui/coin/CoinFragment.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/ui/coin/CoinPresenter.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/ui/market/MarketContract.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/ui/market/MarketListFragment.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/vm/CoinViewModel.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/vm/MarketViewModel.kt
  Nanamare/SampleProject/app/src/main/res/layout/activity_main.xml
  Nanamare/SampleProject/app/src/main/res/layout/fragment_coin_list.xml
  Nanamare/SampleProject/app/src/main/res/layout/fragment_market_list_viewpager.xml
  Nanamare/SampleProject/app/src/main/res/layout/item_ticker.xml
Labels: Mentor Needed, Merge Needed

#108 HW-3 MVVM + Databinding 적용하기
  zion830/StudyFirstProject/app/build.gradle
  zion830/StudyFirstProject/app/src/main/AndroidManifest.xml
  zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/BasePresenter.kt
  zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/BaseView.kt
  zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/adapter/CoinBindingAdapter.kt
  zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/adapter/CoinRecyclerViewAdapter.kt
  zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/base/BaseActivity.kt
  zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/base/BaseViewHolder.kt
  zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/data/CoinDataSource.kt
  zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/data/CoinRepository.kt
  zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/showcoin/CoinContract.kt
  zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/showcoin/CoinPresenter.kt
  zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/showcoin/CoinViewModel.kt
  zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/showcoin/view/MainActivity.kt
  zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/util/NumberFormatUtil.kt
  zion830/StudyFirstProject/app/src/main/res/layout/activity_main.xml
  zion830/StudyFirstProject/app/src/main/res/layout/item_coin_info.xml
  zion830/StudyFirstProject/build.gradle
Labels: Mentor Needed, Merge Needed

#110 HW-5 MVVM DataBinding 리뷰 반영
  machine-human/AndroidArchitectureStudy/.idea/codeStyles/Project.xml
  machine-human/AndroidArchitectureStudy/.idea/runConfigurations.xml
  machine-human/AndroidArchitectureStudy/app/build.gradle
  machine-human/AndroidArchitectureStudy/app/src/androidTest/java/org/study/kotlin/androidarchitecturestudy/ExampleInstrumentedTest.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/adapter/recyclerviewadapter/MainListAdapter.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/adapter/viewpageradapter/MainViewPagerAdapter.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/base/BaseActivity.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/base/BaseDataSource.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/base/BaseFragment.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/base/BasePresenter.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/base/BaseRecyclerView.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/base/BaseView.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/base/BaseViewModel.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/data/TickerRepository.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/data/source/remote/TickerRemoteDataSource.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/view/activity/main/MainActivity.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/view/activity/main/MainContract.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/view/activity/main/MainFragment.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/view/activity/main/MainPresenter.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/view/activity/main/MainViewModel.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/view/bindingadapter/bindTickerData.kt
  machine-human/AndroidArchitectureStudy/app/src/main/res/layout/activity_main.xml
  machine-human/AndroidArchitectureStudy/app/src/main/res/layout/fragment_main.xml
  machine-human/AndroidArchitectureStudy/app/src/main/res/layout/item_ticker.xml
  machine-human/AndroidArchitectureStudy/build.gradle
  machine-human/AndroidArchitectureStudy/gradle.properties
Labels: Mentor Needed, Merge Needed

#116 Class03/onemask
  onemask/ArchitectureStudy/.gitignore
  onemask/ArchitectureStudy/.idea/codeStyles/Project.xml
  onemask/ArchitectureStudy/.idea/codeStyles/codeStyleConfig.xml
  onemask/ArchitectureStudy/.idea/gradle.xml
  onemask/ArchitectureStudy/.idea/misc.xml
  onemask/ArchitectureStudy/.idea/runConfigurations.xml
  onemask/ArchitectureStudy/.idea/vcs.xml
  onemask/ArchitectureStudy/app/.gitignore
  onemask/ArchitectureStudy/app/build.gradle
  onemask/ArchitectureStudy/app/proguard-rules.pro
  onemask/ArchitectureStudy/app/src/androidTest/java/com/android/studyfork/ExampleInstrumentedTest.kt
  onemask/ArchitectureStudy/app/src/main/AndroidManifest.xml
  onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/MainActivity.kt
  onemask/ArchitectureStudy/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  onemask/ArchitectureStudy/app/src/main/res/drawable/ic_launcher_background.xml
  onemask/ArchitectureStudy/app/src/main/res/layout/activity_main.xml
  onemask/ArchitectureStudy/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  onemask/ArchitectureStudy/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  onemask/ArchitectureStudy/app/src/main/res/mipmap-hdpi/ic_launcher.png
  onemask/ArchitectureStudy/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  onemask/ArchitectureStudy/app/src/main/res/mipmap-mdpi/ic_launcher.png
  onemask/ArchitectureStudy/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  onemask/ArchitectureStudy/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  onemask/ArchitectureStudy/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  onemask/ArchitectureStudy/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  onemask/ArchitectureStudy/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  onemask/ArchitectureStudy/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  onemask/ArchitectureStudy/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  onemask/ArchitectureStudy/app/src/main/res/values/colors.xml
  onemask/ArchitectureStudy/app/src/main/res/values/strings.xml
  onemask/ArchitectureStudy/app/src/main/res/values/styles.xml
  onemask/ArchitectureStudy/app/src/test/java/com/android/studyfork/ExampleUnitTest.kt
  onemask/ArchitectureStudy/build.gradle
  onemask/ArchitectureStudy/gradle.properties
  onemask/ArchitectureStudy/gradle/wrapper/gradle-wrapper.jar
  onemask/ArchitectureStudy/gradle/wrapper/gradle-wrapper.properties
  onemask/ArchitectureStudy/gradlew
  onemask/ArchitectureStudy/gradlew.bat
  onemask/ArchitectureStudy/settings.gradle
Labels: Mentor Needed, Merge Needed

#93 HW-4 MVVM 패턴 적용
  NackUn/StudyFirst/app/build.gradle
  NackUn/StudyFirst/app/build/intermediates/blame/res/debug/multi-v2/values-b+sr+Latn.json
  NackUn/StudyFirst/app/build/intermediates/blame/res/debug/multi-v2/values-en-rAU.json
  NackUn/StudyFirst/app/build/intermediates/blame/res/debug/multi-v2/values-en-rCA.json
  NackUn/StudyFirst/app/build/intermediates/blame/res/debug/multi-v2/values-en-rGB.json
  NackUn/StudyFirst/app/build/intermediates/blame/res/debug/multi-v2/values-en-rIN.json
  NackUn/StudyFirst/app/build/intermediates/blame/res/debug/multi-v2/values-en-rXC.json
  NackUn/StudyFirst/app/build/intermediates/blame/res/debug/multi-v2/values-es-rUS.json
  NackUn/StudyFirst/app/build/intermediates/blame/res/debug/multi-v2/values-fr-rCA.json
  NackUn/StudyFirst/app/build/intermediates/blame/res/debug/multi-v2/values-h720dp-v13.json
  NackUn/StudyFirst/app/build/intermediates/blame/res/debug/multi-v2/values-hdpi-v4.json
  NackUn/StudyFirst/app/build/intermediates/blame/res/debug/multi-v2/values-land.json
  NackUn/StudyFirst/app/build/intermediates/blame/res/debug/multi-v2/values-large-v4.json
  NackUn/StudyFirst/app/build/intermediates/blame/res/debug/multi-v2/values-ldltr-v21.json
  NackUn/StudyFirst/app/build/intermediates/blame/res/debug/multi-v2/values-night-v8.json
  NackUn/StudyFirst/app/build/intermediates/blame/res/debug/multi-v2/values-port.json
  NackUn/StudyFirst/app/build/intermediates/blame/res/debug/multi-v2/values-pt-rBR.json
  NackUn/StudyFirst/app/build/intermediates/blame/res/debug/multi-v2/values-pt-rPT.json
  NackUn/StudyFirst/app/build/intermediates/blame/res/debug/multi-v2/values-sw600dp-v13.json
  NackUn/StudyFirst/app/build/intermediates/blame/res/debug/multi-v2/values-v28.json
  NackUn/StudyFirst/app/build/intermediates/blame/res/debug/multi-v2/values-watch-v20.json
  NackUn/StudyFirst/app/build/intermediates/blame/res/debug/multi-v2/values-watch-v21.json
  NackUn/StudyFirst/app/build/intermediates/blame/res/debug/multi-v2/values-xlarge-v4.json
  NackUn/StudyFirst/app/build/intermediates/blame/res/debug/multi-v2/values-zh-rCN.json
  NackUn/StudyFirst/app/build/intermediates/blame/res/debug/multi-v2/values-zh-rHK.json
  NackUn/StudyFirst/app/build/intermediates/blame/res/debug/multi-v2/values-zh-rTW.json
  NackUn/StudyFirst/app/src/main/AndroidManifest.xml
  NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/Base/BasePresenter.kt
  NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/Base/BaseView.kt
  NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/base/BaseActivity.kt
  NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/base/BaseFragment.kt
  NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/base/BaseViewModel.kt
  NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/data/DataSource.kt
  NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/data/Repository.kt
  NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/data/remote/RemoteDataSource.kt
  NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/main/MainActivity.kt
  NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/main/MainContract.kt
  NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/main/MainFragment.kt
  NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/main/MainPresenter.kt
  NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerActivity.kt
  NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerAdapter.kt
  NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerFragment.kt
  NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerFragmentExt.kt
  NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerRecyclerViewExt.kt
  NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerViewModel.kt
  NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/util/TickerFormatter.kt
  NackUn/StudyFirst/app/src/main/res/layout/activity_ticker.xml
  NackUn/StudyFirst/app/src/main/res/layout/main_fragment.xml
  NackUn/StudyFirst/app/src/main/res/layout/ticker_fragment.xml
  NackUn/StudyFirst/app/src/main/res/layout/ticker_item.xml
Labels: Mentor Needed, Merge Needed

#119 HW-0 Class03/wswon 프로젝트 세팅
  wswon/AndroidArchitectureStudy/.gitignore
  wswon/AndroidArchitectureStudy/.idea/codeStyles/Project.xml
  wswon/AndroidArchitectureStudy/.idea/codeStyles/codeStyleConfig.xml
  wswon/AndroidArchitectureStudy/.idea/encodings.xml
  wswon/AndroidArchitectureStudy/.idea/gradle.xml
  wswon/AndroidArchitectureStudy/.idea/misc.xml
  wswon/AndroidArchitectureStudy/.idea/runConfigurations.xml
  wswon/AndroidArchitectureStudy/app/.gitignore
  wswon/AndroidArchitectureStudy/app/build.gradle
  wswon/AndroidArchitectureStudy/app/proguard-rules.pro
  wswon/AndroidArchitectureStudy/app/src/androidTest/java/com/architecture/study/ExampleInstrumentedTest.kt
  wswon/AndroidArchitectureStudy/app/src/main/AndroidManifest.xml
  wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/MainActivity.kt
  wswon/AndroidArchitectureStudy/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  wswon/AndroidArchitectureStudy/app/src/main/res/drawable/ic_launcher_background.xml
  wswon/AndroidArchitectureStudy/app/src/main/res/layout/activity_main.xml
  wswon/AndroidArchitectureStudy/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  wswon/AndroidArchitectureStudy/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  wswon/AndroidArchitectureStudy/app/src/main/res/mipmap-hdpi/ic_launcher.png
  wswon/AndroidArchitectureStudy/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  wswon/AndroidArchitectureStudy/app/src/main/res/mipmap-mdpi/ic_launcher.png
  wswon/AndroidArchitectureStudy/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  wswon/AndroidArchitectureStudy/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  wswon/AndroidArchitectureStudy/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  wswon/AndroidArchitectureStudy/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  wswon/AndroidArchitectureStudy/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  wswon/AndroidArchitectureStudy/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  wswon/AndroidArchitectureStudy/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  wswon/AndroidArchitectureStudy/app/src/main/res/values/colors.xml
  wswon/AndroidArchitectureStudy/app/src/main/res/values/strings.xml
  wswon/AndroidArchitectureStudy/app/src/main/res/values/styles.xml
  wswon/AndroidArchitectureStudy/app/src/test/java/com/architecture/study/ExampleUnitTest.kt
  wswon/AndroidArchitectureStudy/build.gradle
  wswon/AndroidArchitectureStudy/gradle.properties
  wswon/AndroidArchitectureStudy/gradle/wrapper/gradle-wrapper.jar
  wswon/AndroidArchitectureStudy/gradle/wrapper/gradle-wrapper.properties
  wswon/AndroidArchitectureStudy/gradlew
  wswon/AndroidArchitectureStudy/gradlew.bat
  wswon/AndroidArchitectureStudy/settings.gradle
Labels: Mentor Needed, Merge Needed

#121 HW-6 LiveData 적용
  BeokBeok/app/build.gradle
  BeokBeok/app/src/main/AndroidManifest.xml
  BeokBeok/app/src/main/java/com/architecturestudy/base/BaseFragment.kt
  BeokBeok/app/src/main/java/com/architecturestudy/base/BaseRecyclerView.kt
  BeokBeok/app/src/main/java/com/architecturestudy/base/BaseViewModel.kt
  BeokBeok/app/src/main/java/com/architecturestudy/customlistener/TabSelectedListener.kt
  BeokBeok/app/src/main/java/com/architecturestudy/ext/RecyclerViewExt.kt
  BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/UpbitContentsFragment.kt
  BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/UpbitFragment.kt
  BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/UpbitOutlineFragment.kt
  BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/UpbitViewModel.kt
  BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/UpbitViewPagerAdapter.kt
  BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/adapter/UpbitAdapter.kt
  BeokBeok/app/src/main/res/layout/activity_upbit.xml
  BeokBeok/app/src/main/res/layout/fragment_upbit.xml
  BeokBeok/app/src/main/res/layout/fragment_upbit_contents.xml
  BeokBeok/app/src/main/res/layout/fragment_upbit_outline.xml
  BeokBeok/app/src/main/res/layout/rv_upbit_item.xml
  BeokBeok/app/src/main/res/values/styles.xml
  BeokBeok/build.gradle
Labels: Mentor Needed, Merge Needed

#120 HW-5 LiveData 적용
  sport0102/.idea/inspectionProfiles/Project_Default.xml
  sport0102/app/build.gradle
  sport0102/app/src/main/AndroidManifest.xml
  sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/MainApplication.kt
  sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/api/Retrofit.kt
  sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/api/model/TickerResponse.kt
  sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/base/BaseFragment.kt
  sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/data/source/UpbitDataSource.kt
  sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/data/source/UpbitRepository.kt
  sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/data/source/local/UpbitLocalDataSource.kt
  sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/data/source/remote/UpbitRemoteDataSource.kt
  sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/domain/UpbitDatabase.kt
  sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/domain/dao/TickerDao.kt
  sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ext/RecyclerViewExt.kt
  sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/MainFragment.kt
  sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/MainViewModel.kt
  sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/util/StringUtil.kt
  sport0102/app/src/main/res/drawable-anydpi/close.xml
  sport0102/app/src/main/res/drawable-anydpi/search.xml
  sport0102/app/src/main/res/drawable-hdpi/close.png
  sport0102/app/src/main/res/drawable-hdpi/search.png
  sport0102/app/src/main/res/drawable-mdpi/close.png
  sport0102/app/src/main/res/drawable-mdpi/search.png
  sport0102/app/src/main/res/drawable-xhdpi/close.png
  sport0102/app/src/main/res/drawable-xhdpi/search.png
  sport0102/app/src/main/res/drawable-xxhdpi/close.png
  sport0102/app/src/main/res/drawable-xxhdpi/search.png
  sport0102/app/src/main/res/drawable/stroke_1dp_pink.xml
  sport0102/app/src/main/res/layout/activity_main.xml
  sport0102/app/src/main/res/layout/fragment_main.xml
  sport0102/app/src/main/res/layout/item_ticker.xml
  sport0102/app/src/main/res/values/colors.xml
Labels: Mentor Needed, Merge Needed

#125 HW-4 LiveData 적용하기
  zion830/StudyFirstProject/app/build.gradle
  zion830/StudyFirstProject/app/src/androidTest/java/com/studyfirstproject/ExampleInstrumentedTest.kt
  zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/adapter/CoinBindingAdapter.kt
  zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/adapter/CoinRecyclerViewAdapter.kt
  zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/base/BaseActivity.kt
  zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/base/BaseRecyclerView.kt
  zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/base/BaseViewHolder.kt
  zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/showcoin/CoinViewModel.kt
  zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/showcoin/view/MainActivity.kt
  zion830/StudyFirstProject/app/src/main/res/layout/activity_main.xml
  zion830/StudyFirstProject/app/src/main/res/layout/item_coin_info.xml
  zion830/StudyFirstProject/app/src/main/res/values/strings.xml
  zion830/StudyFirstProject/gradle.properties
Labels: Mentor Needed, Merge Needed

#127 HW-4 LiveData 적용
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/base/BaseViewModel.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/ui/MainActivity.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/ui/coin/CoinFragment.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/vm/CoinViewModel.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/vm/MarketViewModel.kt
Labels: Mentor Needed, Merge Needed

#130 HW-1 코인헬퍼 Clone Project
  preludezdev/ArchitectureStudy/.idea/codeStyles/Project.xml
  preludezdev/ArchitectureStudy/.idea/gradle.xml
  preludezdev/ArchitectureStudy/.idea/vcs.xml
  preludezdev/ArchitectureStudy/app/build.gradle
  preludezdev/ArchitectureStudy/app/src/androidTest/java/com/example/architecturestudy/ExampleInstrumentedTest.kt
  preludezdev/ArchitectureStudy/app/src/main/AndroidManifest.xml
  preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/MainActivity.kt
  preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/CoinMarketResponse.kt
  preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/CoinTickerResponse.kt
  preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/network/CoinApiService.kt
  preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/network/NetworkHelper.kt
  preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MainActivity.kt
  preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/MarketFragment.kt
  preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/RecyclerViewAdapter.kt
  preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/SplashActivity.kt
  preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/VpAdapter.kt
  preludezdev/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/util/Util.kt
  preludezdev/ArchitectureStudy/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  preludezdev/ArchitectureStudy/app/src/main/res/drawable/ic_launcher_background.xml
  preludezdev/ArchitectureStudy/app/src/main/res/layout/activity_main.xml
  preludezdev/ArchitectureStudy/app/src/main/res/layout/activity_splash.xml
  preludezdev/ArchitectureStudy/app/src/main/res/layout/fragment_market.xml
  preludezdev/ArchitectureStudy/app/src/main/res/layout/item_coin.xml
  preludezdev/ArchitectureStudy/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  preludezdev/ArchitectureStudy/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  preludezdev/ArchitectureStudy/app/src/main/res/values/styles.xml
  preludezdev/ArchitectureStudy/app/src/test/java/com/example/architecturestudy/ExampleUnitTest.kt
  preludezdev/ArchitectureStudy/gradle.properties
  preludezdev/ArchitectureStudy/gradle/wrapper/gradle-wrapper.properties
Labels: Mentor Needed, Merge Needed

#131 HW-1 코인헬퍼 따라잡기
  wswon/AndroidArchitectureStudy/.idea/codeStyles/Project.xml
  wswon/AndroidArchitectureStudy/.idea/misc.xml
  wswon/AndroidArchitectureStudy/app/build.gradle
  wswon/AndroidArchitectureStudy/app/src/androidTest/java/com/architecture/study/ExampleInstrumentedTest.kt
  wswon/AndroidArchitectureStudy/app/src/main/AndroidManifest.xml
  wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/MainActivity.kt
  wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/activity/MainActivity.kt
  wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/adapter/CoinListAdapter.kt
  wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/adapter/TabPagerAdapter.kt
  wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/adapter/viewholder/CoinViewHolder.kt
  wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/fragment/CoinListFragment.kt
  wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/item/Ticker.kt
  wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/model/MarketResponse.kt
  wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/model/TickerResponse.kt
  wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/server/ApiService.kt
  wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/server/UpbitRequest.kt
  wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/server/UpbitRequestListener.kt
  wswon/AndroidArchitectureStudy/app/src/main/res/layout/activity_main.xml
  wswon/AndroidArchitectureStudy/app/src/main/res/layout/activity_splash.xml
  wswon/AndroidArchitectureStudy/app/src/main/res/layout/fragment_coinlist.xml
  wswon/AndroidArchitectureStudy/app/src/main/res/layout/item_coin.xml
  wswon/AndroidArchitectureStudy/app/src/main/res/values/colors.xml
  wswon/AndroidArchitectureStudy/app/src/main/res/values/strings.xml
  wswon/AndroidArchitectureStudy/app/src/main/res/values/styles.xml
  wswon/AndroidArchitectureStudy/gradle.properties
Labels: Mentor Needed, Merge Needed

#122 HW-6 LiveData 적용
  machine-human/AndroidArchitectureStudy/.idea/runConfigurations.xml
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/adapter/viewpageradapter/MainViewPagerAdapter.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/api/model/ConvertTickerModel.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/api/model/TickerModel.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/base/BaseDataSource.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/base/BaseFragment.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/base/BaseViewModel.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/ext/BaseRecyclerViewExt.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/util/FormatUtil.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/view/activity/main/MainFragment.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/view/activity/main/MainViewModel.kt
  machine-human/AndroidArchitectureStudy/app/src/main/res/layout/item_ticker.xml
Labels: Mentor Needed, Merge Needed

#132 HW-1 코인헬퍼 만들기
  onemask/ArchitectureStudy/.idea/codeStyles/Project.xml
  onemask/ArchitectureStudy/.idea/misc.xml
  onemask/ArchitectureStudy/app/build.gradle
  onemask/ArchitectureStudy/app/src/androidTest/java/com/android/studyfork/ExampleInstrumentedTest.kt
  onemask/ArchitectureStudy/app/src/main/AndroidManifest.xml
  onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/MainActivity.kt
  onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/app/StudyForkApplication.kt
  onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/network/api/UpbitService.kt
  onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/network/remote/model/MarketResponse.kt
  onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/network/remote/model/TickerResponse.kt
  onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/network/repository/UpbitDataSource.kt
  onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/network/repository/UpbitRepository.kt
  onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/network/repository/UpbitRepositoryImpl.kt
  onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/MainActivity.kt
  onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/TikcerListFragment.kt
  onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/adpater/CoinItemAdapter.kt
  onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/adpater/ViewpagerAdapter.kt
  onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/utill/Fragment.kt
  onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/utill/Textview.kt
  onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/utill/View.kt
  onemask/ArchitectureStudy/app/src/main/res/drawable/rounded_rectangle_8dp.xml
  onemask/ArchitectureStudy/app/src/main/res/layout/activity_main.xml
  onemask/ArchitectureStudy/app/src/main/res/layout/fragment_krw.xml
  onemask/ArchitectureStudy/app/src/main/res/layout/item_coin.xml
  onemask/ArchitectureStudy/app/src/main/res/values/colors.xml
  onemask/ArchitectureStudy/app/src/main/res/values/strings.xml
  onemask/ArchitectureStudy/gradle.properties
Labels: Mentor Needed, Merge Needed

#124 HW-1 코인헬퍼 클론 프로젝트
  zojae031/Project/.idea/codeStyles/Project.xml
  zojae031/Project/app/build.gradle
  zojae031/Project/app/src/androidTest/java/study/architecture/ExampleInstrumentedTest.kt
  zojae031/Project/app/src/main/AndroidManifest.xml
  zojae031/Project/app/src/main/java/study/architecture/MainActivity.kt
  zojae031/Project/app/src/main/java/study/architecture/adapter/CoinDataAdapter.kt
  zojae031/Project/app/src/main/java/study/architecture/adapter/MainPageAdapter.kt
  zojae031/Project/app/src/main/java/study/architecture/mainjob/MainActivity.kt
  zojae031/Project/app/src/main/java/study/architecture/mainjob/MainContract.kt
  zojae031/Project/app/src/main/java/study/architecture/mainjob/MainFragment.kt
  zojae031/Project/app/src/main/java/study/architecture/mainjob/MainPresenter.kt
  zojae031/Project/app/src/main/java/study/architecture/model/Repository.kt
  zojae031/Project/app/src/main/java/study/architecture/model/UpbitApi.kt
  zojae031/Project/app/src/main/java/study/architecture/vo/Market.kt
  zojae031/Project/app/src/main/java/study/architecture/vo/Ticker.kt
  zojae031/Project/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  zojae031/Project/app/src/main/res/drawable/ic_launcher_background.xml
  zojae031/Project/app/src/main/res/drawable/item_background.xml
  zojae031/Project/app/src/main/res/layout/activity_main.xml
  zojae031/Project/app/src/main/res/layout/fragment_main.xml
  zojae031/Project/app/src/main/res/layout/list_item.xml
  zojae031/Project/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  zojae031/Project/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  zojae031/Project/app/src/main/res/mipmap-hdpi/icon.png
  zojae031/Project/app/src/main/res/values/colors.xml
  zojae031/Project/app/src/main/res/values/strings.xml
  zojae031/Project/app/src/main/res/values/styles.xml
  zojae031/Project/app/src/test/java/study/architecture/ExampleUnitTest.kt
  zojae031/Project/gradle.properties
Labels: Mentor Needed, Merge Needed

#133 HW-7 AAC ViewModel 적용
  NackUn/StudyFirst/app/build.gradle
  NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/base/BaseViewModel.kt
  NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/ui/ticker/TickerFragment.kt
Labels: Mentor Needed, Merge Needed

#141 HW-5 AAC ViewModel 적용하기
  zion830/StudyFirstProject/app/build.gradle
  zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/showcoin/CoinViewModel.kt
  zion830/StudyFirstProject/app/src/main/java/com/studyfirstproject/showcoin/view/MainActivity.kt
Labels: Mentor Needed, Merge Needed

#145 HW-6 AAC ViewModel 추가
  sport0102/app/build.gradle
  sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/base/BaseActivity.kt
  sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/MainActivity.kt
  sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/MainSearchFragment.kt
  sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/MainSearchViewModel.kt
  sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/MainTickerFragment.kt
  sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/MainTickerPagerAdapter.kt
  sport0102/app/src/main/java/com/aiden/aiden/architecturepatternstudy/ui/main/MainViewModel.kt
  sport0102/app/src/main/res/layout/activity_main.xml
  sport0102/app/src/main/res/layout/fragment_search_main.xml
  sport0102/app/src/main/res/layout/fragment_ticker_main.xml
Labels: Mentor Needed, Merge Needed

#142 HW-7 AAC ViewModel 적용
  machine-human/AndroidArchitectureStudy/app/build.gradle
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/api/model/ConvertTickerModel.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/api/model/TickerModel.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/base/BaseRecyclerView.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/base/BaseViewModel.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/util/FormatUtil.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/view/activity/main/MainFragment.kt
  machine-human/AndroidArchitectureStudy/app/src/main/java/org/study/kotlin/androidarchitecturestudy/view/activity/main/MainViewModel.kt
  machine-human/AndroidArchitectureStudy/app/src/main/res/layout/item_ticker.xml
Labels: Mentor Needed, Merge Needed

#136 HW-7 ViewModel 적용
  BeokBeok/app/build.gradle
  BeokBeok/app/src/main/java/com/architecturestudy/base/BaseRecyclerView.kt
  BeokBeok/app/src/main/java/com/architecturestudy/base/BaseViewModel.kt
  BeokBeok/app/src/main/java/com/architecturestudy/data/upbit/UpbitRepository.kt
  BeokBeok/app/src/main/java/com/architecturestudy/data/upbit/UpbitTicker.kt
  BeokBeok/app/src/main/java/com/architecturestudy/data/upbit/source/UpbitDataSource.kt
  BeokBeok/app/src/main/java/com/architecturestudy/data/upbit/source/UpbitRepository.kt
  BeokBeok/app/src/main/java/com/architecturestudy/data/upbit/source/UpbitRetrofitDataSource.kt
  BeokBeok/app/src/main/java/com/architecturestudy/data/upbit/source/local/UpbitDatabase.kt
  BeokBeok/app/src/main/java/com/architecturestudy/data/upbit/source/local/UpbitLocalDataSource.kt
  BeokBeok/app/src/main/java/com/architecturestudy/data/upbit/source/local/UpbitRoom.kt
  BeokBeok/app/src/main/java/com/architecturestudy/data/upbit/source/local/UpbitTickerDao.kt
  BeokBeok/app/src/main/java/com/architecturestudy/data/upbit/source/remote/UpbitRemoteDataSource.kt
  BeokBeok/app/src/main/java/com/architecturestudy/data/upbit/source/remote/UpbitRemoteService.kt
  BeokBeok/app/src/main/java/com/architecturestudy/data/upbit/source/remote/UpbitRetrofit.kt
  BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/UpbitContentsFragment.kt
  BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/UpbitOutlineFragment.kt
  BeokBeok/app/src/main/java/com/architecturestudy/upbitmarket/UpbitViewModel.kt
  BeokBeok/app/src/main/java/com/architecturestudy/util/NumberFormatter.kt
  BeokBeok/app/src/main/java/com/architecturestudy/util/RxEventBus.kt
  BeokBeok/app/src/main/res/drawable-nodpi/sort_down.png
  BeokBeok/app/src/main/res/drawable-nodpi/sort_up.png
  BeokBeok/app/src/main/res/layout/fragment_upbit_outline.xml
  BeokBeok/app/src/main/res/layout/rv_upbit_item.xml
  BeokBeok/app/src/main/res/values-ko/strings.xml
  BeokBeok/app/src/main/res/values/colors.xml
  BeokBeok/app/src/main/res/values/strings.xml
  BeokBeok/build.gradle
Labels: Mentor Needed, Merge Needed

#138 HW-02 Model 적용하기
  wswon/AndroidArchitectureStudy/app/src/main/AndroidManifest.xml
  wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/data/model/Ticker.kt
  wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/data/source/CoinDataSource.kt
  wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/data/source/CoinRemoteDataSource.kt
  wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/data/source/CoinRemoteDataSourceListener.kt
  wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/data/source/CoinRepository.kt
  wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/fragment/CoinListFragment.kt
  wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/model/TickerResponse.kt
  wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/network/api/UpbitApi.kt
  wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/network/model/MarketResponse.kt
  wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/network/model/TickerResponse.kt
  wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListActivity.kt
  wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/CoinListFragment.kt
  wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/adapter/CoinListAdapter.kt
  wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/adapter/CoinTabPagerAdapter.kt
  wswon/AndroidArchitectureStudy/app/src/main/java/com/architecture/study/view/coin/adapter/holder/CoinViewHolder.kt
  wswon/AndroidArchitectureStudy/app/src/main/res/layout/activity_main.xml
  wswon/AndroidArchitectureStudy/app/src/main/res/layout/fragment_coinlist.xml
Labels: Mentor Needed, Merge Needed

#144 HW-5 AAC 뷰모델 적용
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/base/BaseViewModel.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/ext/ViewModelExt.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/ui/MainActivity.kt
  Nanamare/SampleProject/app/src/main/java/com/nanamare/mac/sample/ui/coin/CoinFragment.kt
Labels: Mentor Needed, Merge Needed

#135 HW-02 Model 적용하기
  zojae031/Project/.idea/codeStyles/Project.xml
  zojae031/Project/.idea/misc.xml
  zojae031/Project/app/src/main/AndroidManifest.xml
  zojae031/Project/app/src/main/java/study/architecture/adapter/CoinDataAdapter.kt
  zojae031/Project/app/src/main/java/study/architecture/mainjob/MainContract.kt
  zojae031/Project/app/src/main/java/study/architecture/mainjob/MainPresenter.kt
  zojae031/Project/app/src/main/java/study/architecture/model/Repository.kt
  zojae031/Project/app/src/main/java/study/architecture/model/UpbitApi.kt
  zojae031/Project/app/src/main/java/study/architecture/model/datasource/RemoteDataSource.kt
  zojae031/Project/app/src/main/java/study/architecture/model/datasource/UpbitApi.kt
  zojae031/Project/app/src/main/java/study/architecture/model/repository/Repository.kt
  zojae031/Project/app/src/main/java/study/architecture/model/vo/Market.kt
  zojae031/Project/app/src/main/java/study/architecture/model/vo/ProcessingTicker.kt
  zojae031/Project/app/src/main/java/study/architecture/model/vo/Ticker.kt
  zojae031/Project/app/src/main/java/study/architecture/ui/MainActivity.kt
  zojae031/Project/app/src/main/java/study/architecture/ui/MainFragment.kt
  zojae031/Project/app/src/main/java/study/architecture/ui/adapter/CoinDataAdapter.kt
  zojae031/Project/app/src/main/java/study/architecture/ui/adapter/MainPageAdapter.kt
  zojae031/Project/app/src/main/java/study/architecture/util/TextUtil.kt
  zojae031/Project/app/src/main/res/anim/loading.xml
  zojae031/Project/app/src/main/res/drawable/loading.png
  zojae031/Project/app/src/main/res/layout/activity_main.xml
  zojae031/Project/app/src/main/res/layout/fragment_main.xml
  zojae031/Project/app/src/main/res/layout/list_item.xml
  zojae031/Project/app/src/main/res/values/colors.xml
  zojae031/Project/build.gradle
  zojae031/Project/gradle/wrapper/gradle-wrapper.properties
Labels: Mentor Needed, Merge Needed

#140 HW-02 Model 적용하기
  ganghee/MyStudy2/.gradle/5.1.1/executionHistory/executionHistory.lock
  ganghee/MyStudy2/.gradle/5.1.1/fileHashes/fileHashes.bin
  ganghee/MyStudy2/.gradle/5.1.1/fileHashes/fileHashes.lock
  ganghee/MyStudy2/.gradle/5.1.1/fileHashes/resourceHashesCache.bin
  ganghee/MyStudy2/.gradle/5.1.1/javaCompile/classAnalysis.bin
  ganghee/MyStudy2/.gradle/5.1.1/javaCompile/jarAnalysis.bin
  ganghee/MyStudy2/.gradle/5.1.1/javaCompile/javaCompile.lock
  ganghee/MyStudy2/.gradle/5.1.1/javaCompile/taskHistory.bin
  ganghee/MyStudy2/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  ganghee/MyStudy2/.gradle/buildOutputCleanup/outputFiles.bin
  ganghee/MyStudy2/.idea/misc.xml
  ganghee/MyStudy2/.idea/vcs.xml
  ganghee/MyStudy2/app/src/main/AndroidManifest.xml
  ganghee/MyStudy2/app/src/main/java/com/example/mystudy/activity/MainActivity.kt
  ganghee/MyStudy2/app/src/main/java/com/example/mystudy/adapter/RecyclerViewAdapter.kt
  ganghee/MyStudy2/app/src/main/java/com/example/mystudy/adapter/TickerAdapter.kt
  ganghee/MyStudy2/app/src/main/java/com/example/mystudy/adapter/UpbitHolder.kt
  ganghee/MyStudy2/app/src/main/java/com/example/mystudy/adapter/ViewPagerAdapter.kt
  ganghee/MyStudy2/app/src/main/java/com/example/mystudy/data/FormatTickers.kt
  ganghee/MyStudy2/app/src/main/java/com/example/mystudy/data/UpbitRepository.kt
  ganghee/MyStudy2/app/src/main/java/com/example/mystudy/data/remote/UpbitRemoteDataSource.kt
  ganghee/MyStudy2/app/src/main/java/com/example/mystudy/fragment/UpbitFragment.kt
  ganghee/MyStudy2/app/src/main/java/com/example/mystudy/network/AppController.kt
  ganghee/MyStudy2/app/src/main/java/com/example/mystudy/network/MarketResponse.kt
  ganghee/MyStudy2/app/src/main/java/com/example/mystudy/network/TickerResponse.kt
  ganghee/MyStudy2/app/src/main/java/com/example/mystudy/network/UpbitApi.kt
  ganghee/MyStudy2/app/src/main/java/com/example/mystudy/network/UpbitService.kt
  ganghee/MyStudy2/app/src/main/java/com/example/mystudy/ui/activity/MainActivity.kt
  ganghee/MyStudy2/app/src/main/java/com/example/mystudy/ui/fragment/UpbitFragment.kt
  ganghee/MyStudy2/app/src/main/java/com/example/mystudy/util/FormatText.kt
  ganghee/MyStudy2/app/src/main/res/layout/activity_main.xml
  ganghee/MyStudy2/app/src/main/res/layout/fragment_upbit.xml
  ganghee/MyStudy2/app/src/main/res/layout/rv_item_list.xml
  ganghee/MyStudy2/app/src/main/res/values/strings.xml
Labels: Mentor Needed, Merge Needed

#150 사전과제-1 update README.md file
  README.md
  jskim5923/README.md
Labels: Mentor Needed, Merge Needed

#152 사전과제
  README.md
  toctocbin/README.md
Labels: Mentor Needed, Merge Needed
