Repository StudyFork/GoogryAndroidArchitectureStudy, pull requests merged in 2019-11, with the labels that each got.

#245 HW-06 MVVM 패턴 적용하기.
  onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/base/BaseActivity.kt
  onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/base/BaseContract.kt
  onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/base/BaseFragment.kt
  onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/base/BasePresenter.kt
  onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/base/BaseViewModel.kt
  onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/network/model/TickerResponse.kt
  onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/network/model/Tikcer.kt
  onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/TickerListFragment.kt
  onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/main/MainActivity.kt
  onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/main/adapter/MainBindingAdapter.kt
  onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/main/presenter/MainContract.kt
  onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/main/presenter/MainPresenter.kt
  onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/main/viewmodel/MainViewModel.kt
  onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/tickerlist/adapter/CoinItemAdapter.kt
  onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/tickerlist/adapter/TickerListBindingAdapter.kt
  onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/tickerlist/presenter/TickerContract.kt
  onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/tickerlist/presenter/TickerPresenter.kt
  onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/tickerlist/viewmodel/TickerViewModel.kt
  onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/util/DataFormatutils.kt
  onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/util/String.kt
  onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/util/TextView.kt
  onemask/ArchitectureStudy/app/src/main/res/layout/activity_main.xml
  onemask/ArchitectureStudy/app/src/main/res/layout/fragment_ticker_list.xml
  onemask/ArchitectureStudy/app/src/main/res/layout/item_coin.xml
Labels: Mentor Needed, Merge Needed

#259 HW-1-과제 샘플 프로젝트 제작
  ironelder/AndroidArchitecture/.idea/codeStyles/codeStyleConfig.xml
  ironelder/AndroidArchitecture/app/build.gradle
  ironelder/AndroidArchitecture/app/src/main/AndroidManifest.xml
  ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/MainActivity.kt
  ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/common/Contants.kt
  ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/BaseFragment.kt
  ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/MainActivity.kt
  ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/MainApplication.kt
  ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/MainFragment.kt
  ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/data/ISearchForNaver.kt
  ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/data/RetrofitForNaver.kt
  ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/data/TotalModel.kt
  ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/CustomItemView.kt
  ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/CustomListViewAdapter.kt
  ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/ICustomItemView.kt
  ironelder/AndroidArchitecture/app/src/main/res/drawable/bg_button_selector.xml
  ironelder/AndroidArchitecture/app/src/main/res/drawable/bg_edittext.xml
  ironelder/AndroidArchitecture/app/src/main/res/layout/activity_main.xml
  ironelder/AndroidArchitecture/app/src/main/res/layout/fragment_main.xml
  ironelder/AndroidArchitecture/app/src/main/res/layout/item_custom_item_view.xml
  ironelder/AndroidArchitecture/app/src/main/res/layout/layout_search_listview.xml
  ironelder/AndroidArchitecture/app/src/main/res/menu/search_menu.xml
  ironelder/AndroidArchitecture/app/src/main/res/mipmap-hdpi/ic_normal_search.png
  ironelder/AndroidArchitecture/app/src/main/res/mipmap-hdpi/ic_press_search.png
  ironelder/AndroidArchitecture/app/src/main/res/mipmap-mdpi/ic_normal_search.png
  ironelder/AndroidArchitecture/app/src/main/res/mipmap-mdpi/ic_press_search.png
  ironelder/AndroidArchitecture/app/src/main/res/mipmap-xhdpi/ic_normal_search.png
  ironelder/AndroidArchitecture/app/src/main/res/mipmap-xhdpi/ic_press_search.png
  ironelder/AndroidArchitecture/app/src/main/res/mipmap-xxhdpi/ic_normal_search.png
  ironelder/AndroidArchitecture/app/src/main/res/mipmap-xxhdpi/ic_press_search.png
  ironelder/AndroidArchitecture/app/src/main/res/mipmap-xxxhdpi/ic_normal_search.png
  ironelder/AndroidArchitecture/app/src/main/res/mipmap-xxxhdpi/ic_press_search.png
  ironelder/AndroidArchitecture/app/src/main/res/values/colors.xml
  ironelder/AndroidArchitecture/app/src/main/res/values/strings.xml
  ironelder/AndroidArchitecture/build.gradle
Labels: Mentor Needed, Merge Needed

#263 HW-1 샘플 프로젝트 과제 제작
  taeiim/MyApplication/.idea/codeStyles/codeStyleConfig.xml
  taeiim/MyApplication/app/build.gradle
  taeiim/MyApplication/app/src/main/AndroidManifest.xml
  taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/MainActivity.kt
  taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/api/SearchApi.kt
  taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/api/SearchApiProvider.kt
  taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/api/model/SearchResult.kt
  taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/extensions/String.kt
  taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/BlogFragment.kt
  taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/BookFragment.kt
  taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/MainActivity.kt
  taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/MovieFragment.kt
  taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/NewsFragment.kt
  taeiim/MyApplication/app/src/main/res/drawable/ic_blog.xml
  taeiim/MyApplication/app/src/main/res/drawable/ic_book.xml
  taeiim/MyApplication/app/src/main/res/drawable/ic_movie.xml
  taeiim/MyApplication/app/src/main/res/drawable/ic_newspaper.xml
  taeiim/MyApplication/app/src/main/res/layout/activity_main.xml
  taeiim/MyApplication/app/src/main/res/layout/fragment_main.xml
  taeiim/MyApplication/app/src/main/res/layout/item_contents.xml
  taeiim/MyApplication/app/src/main/res/menu/menu_main_bottom_navigation.xml
  taeiim/MyApplication/app/src/main/res/values/strings.xml
  taeiim/MyApplication/build.gradle
Labels: Mentor Needed, Merge Needed

#262 HW-1 샘플 프로젝트 과제 제작
  2giwon/ArchitectureStudy/.gitignore
  2giwon/ArchitectureStudy/.idea/codeStyles/Project.xml
  2giwon/ArchitectureStudy/.idea/codeStyles/codeStyleConfig.xml
  2giwon/ArchitectureStudy/.idea/runConfigurations.xml
  2giwon/ArchitectureStudy/app/build.gradle
  2giwon/ArchitectureStudy/app/src/main/AndroidManifest.xml
  2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/MainActivity.kt
  2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/PagerAdapter.kt
  2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/TabsFragment.kt
  2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/base/BaseActivity.kt
  2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/base/BaseFragment.kt
  2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/data/Content.kt
  2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/data/ContentsService.kt
  2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/data/SearchCallback.kt
  2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/data/SearchService.kt
  2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/ext/StringExt.kt
  2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/tabs/ContentsAdapter.kt
  2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/tabs/ContentsFragment.kt
  2giwon/ArchitectureStudy/app/src/main/res/layout/activity_main.xml
  2giwon/ArchitectureStudy/app/src/main/res/layout/fg_contents.xml
  2giwon/ArchitectureStudy/app/src/main/res/layout/fg_tabs.xml
  2giwon/ArchitectureStudy/app/src/main/res/layout/rv_contents_item.xml
  2giwon/ArchitectureStudy/app/src/main/res/values/strings.xml
  2giwon/ArchitectureStudy/build.gradle
  2giwon/ArchitectureStudy/gradle.properties
  2giwon/ArchitectureStudy/gradle/wrapper/gradle-wrapper.jar
  2giwon/ArchitectureStudy/gradle/wrapper/gradle-wrapper.properties
  2giwon/ArchitectureStudy/gradlew
  2giwon/ArchitectureStudy/gradlew.bat
  2giwon/ArchitectureStudy/settings.gradle
Labels: Mentor Needed, Merge Needed

#266 HW-1 샘플 프로젝트 제작
  buddman1208/ArchitectureStudy/.idea/misc.xml
  buddman1208/ArchitectureStudy/app/build.gradle
  buddman1208/ArchitectureStudy/app/src/main/AndroidManifest.xml
  buddman1208/ArchitectureStudy/app/src/main/java/com/buddman1208/architecturestudy/MainActivity.kt
  buddman1208/ArchitectureStudy/app/src/main/java/com/buddman1208/architecturestudy/models/BookItem.kt
  buddman1208/ArchitectureStudy/app/src/main/java/com/buddman1208/architecturestudy/models/CommonItem.kt
  buddman1208/ArchitectureStudy/app/src/main/java/com/buddman1208/architecturestudy/models/CommonResponse.kt
  buddman1208/ArchitectureStudy/app/src/main/java/com/buddman1208/architecturestudy/models/MovieItem.kt
  buddman1208/ArchitectureStudy/app/src/main/java/com/buddman1208/architecturestudy/utils/Constants.kt
  buddman1208/ArchitectureStudy/app/src/main/java/com/buddman1208/architecturestudy/utils/Extensions.kt
  buddman1208/ArchitectureStudy/app/src/main/java/com/buddman1208/architecturestudy/utils/NetworkApi.kt
  buddman1208/ArchitectureStudy/app/src/main/java/com/buddman1208/architecturestudy/utils/NetworkExtensions.kt
  buddman1208/ArchitectureStudy/app/src/main/java/com/buddman1208/architecturestudy/utils/NetworkManager.kt
  buddman1208/ArchitectureStudy/app/src/main/java/com/buddman1208/architecturestudy/utils/NetworkServiceGenerator.kt
  buddman1208/ArchitectureStudy/app/src/main/res/color/main_bottom_bar.xml
  buddman1208/ArchitectureStudy/app/src/main/res/drawable/ic_blog.xml
  buddman1208/ArchitectureStudy/app/src/main/res/drawable/ic_book.xml
  buddman1208/ArchitectureStudy/app/src/main/res/drawable/ic_movie.xml
  buddman1208/ArchitectureStudy/app/src/main/res/drawable/ic_news.xml
  buddman1208/ArchitectureStudy/app/src/main/res/layout/activity_main.xml
  buddman1208/ArchitectureStudy/app/src/main/res/layout/content_book_item.xml
  buddman1208/ArchitectureStudy/app/src/main/res/layout/content_common_item.xml
  buddman1208/ArchitectureStudy/app/src/main/res/layout/content_movie_item.xml
  buddman1208/ArchitectureStudy/app/src/main/res/menu/menu_main.xml
  buddman1208/ArchitectureStudy/app/src/main/res/values/colors.xml
  buddman1208/ArchitectureStudy/app/src/main/res/values/strings.xml
  buddman1208/ArchitectureStudy/app/src/main/res/values/styles.xml
Labels: Mentor Needed, Merge Needed

#270 3기 이진성 후기
  README.md
Labels: Merge Needed

#260 HW-1 과제 샘플 프로젝트 제작
  bean628/MyProject/.idea/codeStyles/Project.xml
  bean628/MyProject/.idea/codeStyles/codeStyleConfig.xml
  bean628/MyProject/app/build.gradle
  bean628/MyProject/app/src/main/AndroidManifest.xml
  bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/MainActivity.kt
  bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/SearchBlogAndNewsAdapter.kt
  bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/SearchMovieAndBookAdapter.kt
  bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/model/ResultOfSearchingModel.kt
  bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/model/SearchedItem.kt
  bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/network/RetrofitClient.kt
  bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/network/RetrofitService.kt
  bean628/MyProject/app/src/main/java/common/Constant.kt
  bean628/MyProject/app/src/main/java/common/GlideWrapper.kt
  bean628/MyProject/app/src/main/res/drawable-hdpi/ic_empty_image.png
  bean628/MyProject/app/src/main/res/drawable-mdpi/ic_empty_image.png
  bean628/MyProject/app/src/main/res/drawable-xhdpi/ic_empty_image.png
  bean628/MyProject/app/src/main/res/drawable-xxhdpi/ic_empty_image.png
  bean628/MyProject/app/src/main/res/drawable-xxxhdpi/ic_empty_image.png
  bean628/MyProject/app/src/main/res/layout/activity_main.xml
  bean628/MyProject/app/src/main/res/layout/item_blog_and_news.xml
  bean628/MyProject/app/src/main/res/layout/item_book_and_movie.xml
  bean628/MyProject/app/src/main/res/values/colors.xml
  bean628/MyProject/app/src/main/res/values/strings.xml
Labels: Mentor Needed, Merge Needed

#265 HW-1 샘플 프로젝트 과제 제작
  developerkhm/AndroidStudy/app/build.gradle
  developerkhm/AndroidStudy/app/src/androidTest/java/com/example/androidstudy/ExampleInstrumentedTest.kt
  developerkhm/AndroidStudy/app/src/main/AndroidManifest.xml
  developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/MainActivity.kt
  developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/MainTabActivity.kt
  developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/adapter/AdapterSearch.kt
  developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/api/RetrofitBuilder.kt
  developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/api/data/TotalModel.kt
  developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/api/service/ApiNaverService.kt
  developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/common/CommonContant.kt
  developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/ui/base/BaseFragment.kt
  developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/ui/blog/BlogFragment.kt
  developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/ui/book/BookFragment.kt
  developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/ui/movie/MovieFragment.kt
  developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/ui/news/NewsFragment.kt
  developerkhm/AndroidStudy/app/src/main/res/drawable/ic_dashboard_black_24dp.xml
  developerkhm/AndroidStudy/app/src/main/res/drawable/ic_home_black_24dp.xml
  developerkhm/AndroidStudy/app/src/main/res/drawable/ic_notifications_black_24dp.xml
  developerkhm/AndroidStudy/app/src/main/res/layout/activity_main_tab.xml
  developerkhm/AndroidStudy/app/src/main/res/layout/fragment_blog.xml
  developerkhm/AndroidStudy/app/src/main/res/layout/fragment_book.xml
  developerkhm/AndroidStudy/app/src/main/res/layout/fragment_movie.xml
  developerkhm/AndroidStudy/app/src/main/res/layout/fragment_news.xml
  developerkhm/AndroidStudy/app/src/main/res/layout/item_blog_view.xml
  developerkhm/AndroidStudy/app/src/main/res/layout/layout_search_view.xml
  developerkhm/AndroidStudy/app/src/main/res/menu/bottom_nav_menu.xml
  developerkhm/AndroidStudy/app/src/main/res/navigation/mobile_navigation.xml
  developerkhm/AndroidStudy/app/src/main/res/values/dimens.xml
  developerkhm/AndroidStudy/app/src/main/res/values/strings.xml
  developerkhm/AndroidStudy/app/src/test/java/com/example/androidstudy/ExampleUnitTest.kt
Labels: Mentor Needed, Merge Needed

#274 HW-7 LiveData, AAC-ViewModel 적용
  jskim5923/ArchitectureStudy/app/build.gradle
  jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/base/BaseActivity.kt
  jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/base/BaseFragment.kt
  jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/base/BaseViewModel.kt
  jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/coin/CoinFragment.kt
  jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/coin/CoinViewModel.kt
  jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/main/MainActivity.kt
  jskim5923/ArchitectureStudy/app/src/main/java/com/jskim5923/architecturestudy/main/MainViewModel.kt
  jskim5923/ArchitectureStudy/app/src/main/res/layout/layout_coin_fragment.xml
Labels: Mentor Needed, Merge Needed

#269 HW-2-Model 적용을 위한 View에서 Remote 호출방식을 분리하여 repository와 source 추가
  ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/MainApplication.kt
  ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/component/MainFragment.kt
  ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/data/RetrofitForNaver.kt
  ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/data/SearchForNaver.kt
  ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/data/repository/SearchDataRepository.kt
  ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/data/repository/SearchDataRepositoryImpl.kt
  ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/data/source/SearchDataSource.kt
  ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/data/source/SearchDataSourceImpl.kt
  ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/CustomItemView.kt
  ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/CustomItemViewImpl.kt
  ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/CustomListViewAdapter.kt
  ironelder/AndroidArchitecture/app/src/main/java/com/ironelder/androidarchitecture/view/ICustomItemView.kt
Labels: Mentor Needed, Merge Needed

#272 HW-2 MVP의 Model 생성
  2giwon/ArchitectureStudy/.idea/codeStyles/Project.xml
  2giwon/ArchitectureStudy/.idea/codeStyles/codeStyleConfig.xml
  2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/PagerAdapter.kt
  2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/base/BaseFragment.kt
  2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/data/Content.kt
  2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/data/SearchCallback.kt
  2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/data/SearchService.kt
  2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/data/source/NaverDataRepository.kt
  2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/data/source/NaverDataSource.kt
  2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/data/source/remote/ContentsService.kt
  2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/data/source/remote/NaverRemoteDataSource.kt
  2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/data/source/service/RetrofitApi.kt
  2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/tabs/ContentsFragment.kt
  2giwon/ArchitectureStudy/app/src/main/res/values/strings.xml
Labels: Answer Needed, Merge Needed

#279 HW-7 AAC-ViewModel, LiveData 적용
  onemask/ArchitectureStudy/app/build.gradle
  onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/base/BaseActivity.kt
  onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/base/BaseFragment.kt
  onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/base/BaseViewModel.kt
  onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/TickerListFragment.kt
  onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/main/MainActivity.kt
  onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/main/adapter/MainBindingAdapter.kt
  onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/main/adapter/ViewPagerAdapter.kt
  onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/main/viewmodel/MainViewModel.kt
  onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/tickerlist/viewmodel/TickerViewModel.kt
  onemask/ArchitectureStudy/app/src/main/java/com/android/studyfork/ui/tickerlist/viewmodel/TickerViewModelFactory.kt
Labels: Mentor Needed, Merge Needed

#281 HW-2 Model 적용
  bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/AppCompatActivityExtension.kt
  bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/MainActivity.kt
  bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/SearchBlogAndNewsAdapter.kt
  bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/SearchMovieAndBookAdapter.kt
  bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/data/source/remote/NaverRemoteDataSource.kt
  bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/data/source/remote/NaverRemoteDataSourceImpl.kt
  bean628/MyProject/app/src/main/java/com/practice/achitecture/myproject/network/RetrofitFailureHandler.kt
  bean628/MyProject/app/src/main/res/values/strings.xml
Labels: Mentor Needed, Merge Needed

#277 HW-7 AAC-ViewModel, LiveData 적용
  seonoh/ArchitectureStudy/app/build.gradle
  seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/BaseActivity.kt
  seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/BaseFragment.kt
  seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/CoinFragment.kt
  seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/MainActivity.kt
  seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/TabPagerAdapter.kt
  seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/model/BaseViewModel.kt
  seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/model/CoinViewModel.kt
  seonoh/ArchitectureStudy/app/src/main/java/com/example/seonoh/seonohapp/model/MainViewModel.kt
  seonoh/ArchitectureStudy/dependencies.gradle
Labels: Mentor Needed, Merge Needed

#284 3기 김강희 후기 작성
  README.md
Labels: Mentor Needed

#276 HW-07 AAC ViewModel, LiveData 적용하기
  junghum21/ArchStudy/app/build.gradle
  junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/base/BaseActivity.kt
  junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/base/BaseFragment.kt
  junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/base/BaseViewModel.kt
  junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/ui/main/MainActivity.kt
  junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/ui/main/MainViewModel.kt
  junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/ui/tickers/TickersFragment.kt
  junghum21/ArchStudy/app/src/main/java/com/jake/archstudy/ui/tickers/TickersViewModel.kt
Labels: Mentor Needed, Review Needed

#271 HW-2 Model 과제
  taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/Tabs.kt
  taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/data/NaverRepository.kt
  taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/data/NaverRepositoryImpl.kt
  taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/data/source/NaverDataSource.kt
  taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/data/source/NaverRemoteDataSourceImpl.kt
  taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/BlogFragment.kt
  taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/BookFragment.kt
  taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/ContentsFragment.kt
  taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/MainActivity.kt
  taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/MovieFragment.kt
  taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/NewsFragment.kt
  taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/SearchResultRecyclerAdapter.kt
  taeiim/MyApplication/app/src/main/res/layout/fragment_main.xml
  taeiim/MyApplication/app/src/main/res/values/strings.xml
Labels: Mentor Needed, Merge Needed

#275 HW-7 AAC-ViewModel, LiveData 적용
  toctocbin/AndroidArchitecture/app/build.gradle
  toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/base/BaseActivity.kt
  toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/base/BaseFragment.kt
  toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/base/BaseViewModel.kt
  toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/market/MarketActivity.kt
  toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/market/MarketViewModel.kt
  toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/ticker/TickerFragment.kt
  toctocbin/AndroidArchitecture/app/src/main/java/com/test/androidarchitecture/ui/ticker/TickerViewModel.kt
Labels: Mentor Needed, Merge Needed

#289 Update README.md
  README.md
  wooooooak/README.md
Labels: Mentor Needed, Merge Needed

#298 Update README File
  README.md
  dksush/README.md
Labels: Mentor Needed, Merge Needed

#287 HW-3 MVP 구조 변경 작업
  taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/extensions/GlideExt.kt
  taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/ContentsContract.kt
  taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/ContentsFragment.kt
  taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/ContentsPresenter.kt
  taeiim/MyApplication/app/src/main/java/com/god/taeiim/myapplication/ui/SearchResultRecyclerAdapter.kt
  taeiim/MyApplication/app/src/main/res/drawable/ic_photo.xml
  taeiim/MyApplication/app/src/main/res/values/strings.xml
Labels: Mentor Needed, Merge Needed

#286 HW-3 MVP 구조 변경 작업
  2giwon/ArchitectureStudy/.idea/codeStyles/Project.xml
  2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/PagerAdapter.kt
  2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/Tab.kt
  2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/TabsFragment.kt
  2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/TabsPresenter.kt
  2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/base/BaseContentViewHolder.kt
  2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/base/BaseContract.kt
  2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/base/BaseFragment.kt
  2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/base/BasePresenter.kt
  2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/ext/ImageViewExt.kt
  2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/tabs/ContentsAdapter.kt
  2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/tabs/ContentsContract.kt
  2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/tabs/ContentsFragment.kt
  2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/tabs/ContentsPresenter.kt
  2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/tabs/ImageContentViewHolder.kt
  2giwon/ArchitectureStudy/app/src/main/java/com/egiwon/architecturestudy/tabs/TextContentViewHolder.kt
  2giwon/ArchitectureStudy/app/src/main/res/layout/rv_text_contents_item.xml
  2giwon/ArchitectureStudy/app/src/main/res/values/strings.xml
  2giwon/ArchitectureStudy/build.gradle
Labels: Mentor Needed, Merge Needed

#301 HW-0 README.md 파일수정
  README.md
  chanhoparkcj/README.md
Labels: Mentor Needed, Merge Needed

#291 update README
  JayYi/README.md
  README.md
Labels: Mentor Needed, Merge Needed

#293 update Readme file
  README.md
  jjunji/README.md
Labels: Mentor Needed, Merge Needed

#300 6기 수형 저장공간
  README.md
  doubleclutch30/create readme.
Labels: Mentor Needed, Merge Needed

#280 HW-2 Model과제
  developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/model/data/NaverRemoteData.kt
  developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/model/data/NaverRemoteDataImpl.kt
  developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/model/repository/NaverDataRepository.kt
  developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/model/repository/NaverDataRepositoryImpl.kt
  developerkhm/AndroidStudy/app/src/main/java/com/example/androidstudy/ui/base/BaseFragment.kt
Labels: Mentor Needed, Merge Needed
