Repository StudyFork/GoogryAndroidArchitectureStudy, pull requests merged in 2020-04, with the labels that each got.

#551 feat: create initial project
  2004/kyudong3/.gitignore
  2004/kyudong3/.idea/.gitignore
  2004/kyudong3/.idea/codeStyles/Project.xml
  2004/kyudong3/.idea/codeStyles/codeStyleConfig.xml
  2004/kyudong3/.idea/gradle.xml
  2004/kyudong3/.idea/runConfigurations.xml
  2004/kyudong3/app/.gitignore
  2004/kyudong3/app/build.gradle
  2004/kyudong3/app/proguard-rules.pro
  2004/kyudong3/app/src/androidTest/java/com/example/kyudong3/ExampleInstrumentedTest.kt
  2004/kyudong3/app/src/main/AndroidManifest.xml
  2004/kyudong3/app/src/main/java/com/example/kyudong3/MainActivity.kt
  2004/kyudong3/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  2004/kyudong3/app/src/main/res/drawable/ic_launcher_background.xml
  2004/kyudong3/app/src/main/res/layout/activity_main.xml
  2004/kyudong3/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  2004/kyudong3/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  2004/kyudong3/app/src/main/res/mipmap-hdpi/ic_launcher.png
  2004/kyudong3/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  2004/kyudong3/app/src/main/res/mipmap-mdpi/ic_launcher.png
  2004/kyudong3/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  2004/kyudong3/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  2004/kyudong3/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  2004/kyudong3/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  2004/kyudong3/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  2004/kyudong3/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  2004/kyudong3/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  2004/kyudong3/app/src/main/res/values/colors.xml
  2004/kyudong3/app/src/main/res/values/strings.xml
  2004/kyudong3/app/src/main/res/values/styles.xml
  2004/kyudong3/app/src/test/java/com/example/kyudong3/ExampleUnitTest.kt
  2004/kyudong3/build.gradle
  2004/kyudong3/gradle.properties
  2004/kyudong3/gradle/wrapper/gradle-wrapper.jar
  2004/kyudong3/gradle/wrapper/gradle-wrapper.properties
  2004/kyudong3/gradlew
  2004/kyudong3/gradlew.bat
  2004/kyudong3/settings.gradle
Labels: Mentor Needed, Merge Needed

#550 HW-5 Pure MVVM
  2003/sooakim/app/build.gradle
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/SASplashActivity.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/SASplashContractor.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/SASplashNavigator.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/SASplashPresenter.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/SASplashViewModel.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/application/SAApplication.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/base/SAActivity.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/base/SABasePresenter.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/base/SABaseView.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/base/SAClickable.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/base/SANavigationProvider.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/base/SANavigationProviderImpl.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/base/SANavigator.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/base/SARecyclerViewAdapter.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/base/SAViewModel.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/base/SAViewModelLifecycle.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/login/SALoginActivity.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/login/SALoginContractor.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/login/SALoginNavigator.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/login/SALoginPresenter.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/login/SALoginViewModel.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/movie/SAMovieSearchActivity.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/movie/SAMovieSearchContractor.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/movie/SAMovieSearchNavigator.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/movie/SAMovieSearchPresenter.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/movie/SAMovieSearchViewModel.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/movie/adapter/SAMovieSearchResultAdapter.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/movie/model/SAMoviePresentation.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/util/NotNullObservableField.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/util/ResourceProvider.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/util/ResourceProviderImpl.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/util/ext/ObservableField.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/util/ext/RecyclerView.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/util/ext/TextInputLayout.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/util/ext/View.kt
  2003/sooakim/app/src/main/res/layout/activity_login.xml
  2003/sooakim/app/src/main/res/layout/activity_movie_search.xml
Labels: Mentor Needed, Merge Needed

#549 Feat: add create project(프로젝트 생성)
  2004/taeseongyun/.gitignore
  2004/taeseongyun/.idea/codeStyles/Project.xml
  2004/taeseongyun/.idea/codeStyles/codeStyleConfig.xml
  2004/taeseongyun/.idea/runConfigurations.xml
  2004/taeseongyun/app/.gitignore
  2004/taeseongyun/app/build.gradle
  2004/taeseongyun/app/proguard-rules.pro
  2004/taeseongyun/app/src/androidTest/java/com/tsdev/tsandroid/ExampleInstrumentedTest.kt
  2004/taeseongyun/app/src/main/AndroidManifest.xml
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/MainActivity.kt
  2004/taeseongyun/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  2004/taeseongyun/app/src/main/res/drawable/ic_launcher_background.xml
  2004/taeseongyun/app/src/main/res/layout/activity_main.xml
  2004/taeseongyun/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  2004/taeseongyun/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  2004/taeseongyun/app/src/main/res/mipmap-hdpi/ic_launcher.png
  2004/taeseongyun/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  2004/taeseongyun/app/src/main/res/mipmap-mdpi/ic_launcher.png
  2004/taeseongyun/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  2004/taeseongyun/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  2004/taeseongyun/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  2004/taeseongyun/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  2004/taeseongyun/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  2004/taeseongyun/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  2004/taeseongyun/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  2004/taeseongyun/app/src/main/res/values/colors.xml
  2004/taeseongyun/app/src/main/res/values/strings.xml
  2004/taeseongyun/app/src/main/res/values/styles.xml
  2004/taeseongyun/app/src/test/java/com/tsdev/tsandroid/ExampleUnitTest.kt
  2004/taeseongyun/build.gradle
  2004/taeseongyun/gradle.properties
  2004/taeseongyun/gradle/wrapper/gradle-wrapper.jar
  2004/taeseongyun/gradle/wrapper/gradle-wrapper.properties
  2004/taeseongyun/gradlew
  2004/taeseongyun/gradlew.bat
  2004/taeseongyun/settings.gradle
Labels: Mentor Needed, Merge Needed

#557 Initial project, add gitignore
  2004/invitejay/.gitignore
  2004/invitejay/.idea/.name
  2004/invitejay/.idea/codeStyles/Project.xml
  2004/invitejay/.idea/codeStyles/codeStyleConfig.xml
  2004/invitejay/.idea/gradle.xml
  2004/invitejay/.idea/misc.xml
  2004/invitejay/.idea/runConfigurations.xml
  2004/invitejay/.idea/vcs.xml
  2004/invitejay/app/.gitignore
  2004/invitejay/app/build.gradle
  2004/invitejay/app/proguard-rules.pro
  2004/invitejay/app/src/androidTest/java/com/example/studyforkandroid/ExampleInstrumentedTest.kt
  2004/invitejay/app/src/main/AndroidManifest.xml
  2004/invitejay/app/src/main/java/com/example/studyforkandroid/MainActivity.kt
  2004/invitejay/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  2004/invitejay/app/src/main/res/drawable/ic_launcher_background.xml
  2004/invitejay/app/src/main/res/layout/activity_main.xml
  2004/invitejay/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  2004/invitejay/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  2004/invitejay/app/src/main/res/mipmap-hdpi/ic_launcher.png
  2004/invitejay/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  2004/invitejay/app/src/main/res/mipmap-mdpi/ic_launcher.png
  2004/invitejay/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  2004/invitejay/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  2004/invitejay/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  2004/invitejay/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  2004/invitejay/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  2004/invitejay/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  2004/invitejay/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  2004/invitejay/app/src/main/res/values/colors.xml
  2004/invitejay/app/src/main/res/values/strings.xml
  2004/invitejay/app/src/main/res/values/styles.xml
  2004/invitejay/app/src/test/java/com/example/studyforkandroid/ExampleUnitTest.kt
  2004/invitejay/build.gradle
  2004/invitejay/gradle.properties
  2004/invitejay/gradle/wrapper/gradle-wrapper.jar
  2004/invitejay/gradle/wrapper/gradle-wrapper.properties
  2004/invitejay/gradlew
  2004/invitejay/gradlew.bat
  2004/invitejay/settings.gradle
Labels: Mentor Needed, Merge Needed

#556 HW-5 MVVM 적용
  2003/byiryu/app/src/main/AndroidManifest.xml
  2003/byiryu/app/src/main/java/com/byiryu/study/model/Repository.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/enums/NetStatus.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/mvp/base/BaseActivity.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/mvp/base/BaseContract.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/mvp/base/BasePresenter.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/mvp/intro/IntroActivity.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/mvp/intro/IntroContract.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/mvp/intro/IntroPresenter.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/mvp/login/LoginActivity.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/mvp/login/LoginContract.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/mvp/login/LoginPresenter.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/mvp/main/MainActivity.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/mvp/main/MainConract.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/mvp/main/MainPresenter.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/mvp/main/MainRecyclerAdapter.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/mvp/main/MainRecyclerHolder.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/mvvm/base/viewmodel/BaseViewModel.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/mvvm/base/views/BaseActivity.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/mvvm/login/viewmodel/LoginViewModel.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/mvvm/login/views/LoginActivity.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/mvvm/main/viewmodel/MainViewModel.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/mvvm/main/views/MainActivity.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/mvvm/main/views/adapter/MainRecyclerAdapter.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/mvvm/main/views/adapter/MainRecyclerHolder.kt
  2003/byiryu/app/src/main/res/layout/activity_login.xml
  2003/byiryu/app/src/main/res/layout/activity_main.xml
  2003/byiryu/app/src/main/res/layout/layout_loading.xml
Labels: Mentor Needed, Merge Needed

#558 HW-5 MVVM 적용
  2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/ui/SearchMovieActivity.kt
  2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/ui/SearchMovieAdapter.kt
  2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/ui/SearchMovieContract.kt
  2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/ui/SearchMoviePresenter.kt
  2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/ui/SearchMovieViewModel.kt
  2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/util/addItems.kt
  2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/util/toHtml.kt
  2003/tjdwlsl1021/app/src/main/res/layout/activity_search_movie.xml
  2003/tjdwlsl1021/app/src/main/res/layout/item_movie.xml
Labels: Mentor Needed, Merge Needed

#553 HW-5 MVVM 적용
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/base/BaseActivity.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/login/LoginActivity.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/login/LoginContract.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/login/LoginPresenter.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/login/LoginViewModel.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/search/MovieAdapter.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/search/MovieSearchActivity.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/search/MovieSearchContract.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/search/MovieSearchPresenter.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/search/MovieSearchViewModel.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/splash/SplashActivity.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/splash/SplashContract.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/splash/SplashPresenter.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/splash/SplashViewModel.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/utils/DataBindingAdapters.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/res/layout/activity_login.xml
  2003/mtjin/AndroidArchitectureStudy/app/src/main/res/layout/activity_movie_search.xml
  2003/mtjin/AndroidArchitectureStudy/app/src/main/res/layout/item_movie.xml
Labels: Mentor Needed, Merge Needed

#555 HW-5 Use MVVM
  2003/kangraemin/app/src/main/java/com/example/kangraemin/base/KangBasePresenter.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/base/KangBaseViewModel.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginActivity.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginContract.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginPresenter.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginViewModel.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/main/MainActivity.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/main/MainContract.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/main/MainViewModel.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/splash/SplashActivity.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/splash/SplashContract.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/splash/SplashViewModel.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/util/BIndingAdapter.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/util/NonNullObservableField.kt
  2003/kangraemin/app/src/main/res/layout/activity_login.xml
  2003/kangraemin/app/src/main/res/layout/activity_main.xml
Labels: Mentor Needed, Merge Needed

#559 HW-6 LiveData and ViewModel
  2003/sooakim/app/build.gradle
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/SASplashActivity.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/SASplashNavigator.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/SASplashState.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/SASplashViewModel.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/base/SAActivity.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/base/SAState.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/base/SAViewModel.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/base/SAViewModelLifecycle.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/login/SALoginActivity.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/login/SALoginNavigator.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/login/SALoginState.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/login/SALoginViewModel.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/movie/SAMovieSearchActivity.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/movie/SAMovieSearchNavigator.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/movie/SAMovieSearchState.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/movie/SAMovieSearchViewModel.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/util/NotNullMutableLiveData.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/util/NotNullObservableField.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/util/SingleEvent.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/util/ext/MutableLiveData.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/util/ext/ObservableField.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/util/ext/ViewModel.kt
  2003/sooakim/build.gradle
Labels: Mentor Needed, Merge Needed

#564 HW-6 AAC ViewModel, LiveData 적용
  2003/mtjin/AndroidArchitectureStudy/app/build.gradle
  2003/mtjin/AndroidArchitectureStudy/app/src/main/AndroidManifest.xml
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/login/LoginActivity.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/login/LoginViewModel.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/search/MovieSearchActivity.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/search/MovieSearchViewModel.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/splash/SplashActivity.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/splash/SplashViewModel.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/res/layout/activity_movie_search.xml
  2003/mtjin/AndroidArchitectureStudy/app/src/main/res/values/strings.xml
Labels: Mentor Needed, Merge Needed

#565 HW-1 Add Movie Search API
  2004/invitejay/.gitignore
  2004/invitejay/.idea/codeStyles/codeStyleConfig.xml
  2004/invitejay/app/build.gradle
  2004/invitejay/app/src/main/AndroidManifest.xml
  2004/invitejay/app/src/main/java/com/example/studyforkandroid/MainActivity.kt
  2004/invitejay/app/src/main/java/com/example/studyforkandroid/adapter/MovieAdapter.kt
  2004/invitejay/app/src/main/java/com/example/studyforkandroid/data/MovieResponse.kt
  2004/invitejay/app/src/main/java/com/example/studyforkandroid/network/RetrofitApi.kt
  2004/invitejay/app/src/main/java/com/example/studyforkandroid/network/RetrofitService.kt
  2004/invitejay/app/src/main/java/com/example/studyforkandroid/utils/StringUtils.kt
  2004/invitejay/app/src/main/res/layout/activity_main.xml
  2004/invitejay/app/src/main/res/layout/item_movie.xml
  2004/invitejay/app/src/main/res/values/strings.xml
  2004/invitejay/app/src/main/res/values/styles.xml
  2004/invitejay/appkey.properties
Labels: Mentor Needed, Merge Needed

#566 HW-6 Use Livedata / AAC Viewmodel
  2003/kangraemin/app/build.gradle
  2003/kangraemin/app/src/main/java/com/example/kangraemin/base/KangBaseViewModel.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginActivity.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginViewModel.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/main/MainActivity.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/main/MainViewModel.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/splash/SplashActivity.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/splash/SplashViewModel.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/util/NonNullObservableField.kt
Labels: Mentor Needed, Merge Needed

#560 HW-1 Add search movie info app
  2004/eunjin-hong/.gitignore
  2004/eunjin-hong/app/build.gradle
  2004/eunjin-hong/app/src/main/AndroidManifest.xml
  2004/eunjin-hong/app/src/main/java/com/eunice/eunicehong/MainActivity.kt
  2004/eunjin-hong/app/src/main/java/com/eunice/eunicehong/data/remote/Movie.kt
  2004/eunjin-hong/app/src/main/java/com/eunice/eunicehong/data/remote/MovieAPI.kt
  2004/eunjin-hong/app/src/main/java/com/eunice/eunicehong/data/remote/MovieClient.kt
  2004/eunjin-hong/app/src/main/java/com/eunice/eunicehong/data/remote/MovieService.kt
  2004/eunjin-hong/app/src/main/java/com/eunice/eunicehong/ui/MainActivity.kt
  2004/eunjin-hong/app/src/main/java/com/eunice/eunicehong/ui/MovieAdapter.kt
  2004/eunjin-hong/app/src/main/res/drawable/ic_search.xml
  2004/eunjin-hong/app/src/main/res/layout/activity_main.xml
  2004/eunjin-hong/app/src/main/res/layout/item_movie.xml
  2004/eunjin-hong/app/src/main/res/values/colors.xml
  2004/eunjin-hong/app/src/main/res/values/dimen.xml
  2004/eunjin-hong/app/src/main/res/values/strings.xml
  2004/eunjin-hong/app/src/main/res/values/styles.xml
  2004/eunjin-hong/build.gradle
  2004/eunjin-hong/settings.gradle
Labels: Mentor Needed, Merge Needed

#563 HW-1 Add NAVER search API(네이버 검색 api)
  2004/taeseongyun/app/build.gradle
  2004/taeseongyun/app/src/main/AndroidManifest.xml
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/CreateRetrofit.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/MainActivity.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/MovieInterface.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/MovieResponse.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/NaverAPI.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ToastExt.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/base/BaseRecyclerAdapter.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/base/BaseRecyclerViewHolder.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/base/RecyclerViewModel.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/MainActivity.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/adapter/MovieRecyclerAdapter.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/viewholder/MovieRecyclerViewViewHolder.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/util/StringExt.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/util/widget/CustomImageWithGlide.kt
  2004/taeseongyun/app/src/main/res/drawable/edit_text_background.xml
  2004/taeseongyun/app/src/main/res/drawable/ic_search_black_24dp.xml
  2004/taeseongyun/app/src/main/res/drawable/ic_sentiment_very_dissatisfied_black_24dp.xml
  2004/taeseongyun/app/src/main/res/layout/activity_main.xml
  2004/taeseongyun/app/src/main/res/layout/movie_recycler_item.xml
  2004/taeseongyun/app/src/main/res/values/colors.xml
  2004/taeseongyun/app/src/main/res/values/dimens.xml
  2004/taeseongyun/app/src/main/res/values/strings.xml
  2004/taeseongyun/app/src/main/res/values/styles.xml
  2004/taeseongyun/build.gradle
  2004/taeseongyun/dependency.gradle
Labels: Mentor Needed, Merge Needed

#567 HW-1 Naver Movie Project
  2004/jesterz91/.gitignore
  2004/jesterz91/app/build.gradle
  2004/jesterz91/app/src/main/AndroidManifest.xml
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/MainActivity.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/data/model/Movie.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/data/model/MovieResponse.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/data/remote/MovieService.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/data/remote/api/MovieApi.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/data/remote/interceptor/MovieInterceptor.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/common/BaseActivity.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/common/BaseAdapter.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/common/BaseViewHolder.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/constant/Constant.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/extension/ContextExtension.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/extension/ViewExtension.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/ui/MovieSearchActivity.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/ui/MovieSearchAdapter.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/ui/MovieSearchViewHolder.kt
  2004/jesterz91/app/src/main/res/drawable/ic_search.xml
  2004/jesterz91/app/src/main/res/layout/activity_main.xml
  2004/jesterz91/app/src/main/res/layout/activity_movie_search.xml
  2004/jesterz91/app/src/main/res/layout/item_movie.xml
  2004/jesterz91/app/src/main/res/menu/menu_search.xml
  2004/jesterz91/app/src/main/res/values/strings.xml
  2004/jesterz91/build.gradle
Labels: Mentor Needed, Merge Needed

#562 HW-1 네이버 영화 검색
  2004/nukeolaf/.idea/kotlinc.xml
  2004/nukeolaf/.idea/render.experimental.xml
  2004/nukeolaf/app/build.gradle
  2004/nukeolaf/app/src/main/AndroidManifest.xml
  2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MainActivity.kt
  2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MovieAdapter.kt
  2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MovieItem.kt
  2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MovieItemListener.kt
  2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MovieItemViewHolder.kt
  2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MovieResponse.kt
  2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/RetrofitClient.kt
  2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/RetrofitInterface.kt
  2004/nukeolaf/app/src/main/res/layout/activity_main.xml
  2004/nukeolaf/app/src/main/res/layout/item_movies_rv.xml
  2004/nukeolaf/gradle.properties
Labels: Mentor Needed, Merge Needed

#561 HW-1 add Naver movie search API
  2004/kyudong3/.gitignore
  2004/kyudong3/app/build.gradle
  2004/kyudong3/app/src/main/AndroidManifest.xml
  2004/kyudong3/app/src/main/java/com/example/kyudong3/MainActivity.kt
  2004/kyudong3/app/src/main/java/com/example/kyudong3/adapter/SearchMovieRvAdapter.kt
  2004/kyudong3/app/src/main/java/com/example/kyudong3/extension/StringExtension.kt
  2004/kyudong3/app/src/main/java/com/example/kyudong3/model/Movie.kt
  2004/kyudong3/app/src/main/java/com/example/kyudong3/network/NaverApiService.kt
  2004/kyudong3/app/src/main/java/com/example/kyudong3/network/NaverApiServiceImpl.kt
  2004/kyudong3/app/src/main/java/com/example/kyudong3/network/RetrofitClient.kt
  2004/kyudong3/app/src/main/java/com/example/kyudong3/util/RecyclerViewItemDivider.kt
  2004/kyudong3/app/src/main/res/drawable/divider_rv.xml
  2004/kyudong3/app/src/main/res/layout/activity_main.xml
  2004/kyudong3/app/src/main/res/layout/item_movie.xml
  2004/kyudong3/app/src/main/res/values/styles.xml
  2004/kyudong3/build.gradle
  2004/kyudong3/gradle.properties
Labels: Mentor Needed, Merge Needed

#568 HW-6 AAC ViewModel, LiveData 적용
  2003/tjdwlsl1021/app/build.gradle
  2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/ui/SearchMovieActivity.kt
  2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/ui/SearchMovieViewModel.kt
Labels: Mentor Needed, Merge Needed

#574 HW-7 Koin for DI
  2003/sooakim/app/build.gradle
  2003/sooakim/app/src/main/java/io/github/sooakim/data/remote/SANetworkService.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/data/remote/SANetworkServiceImpl.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/di/LocalModule.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/di/ProviderModule.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/di/RemoteModule.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/di/RepositoryModule.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/di/ViewModelModule.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/SASplashActivity.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/application/SAApplication.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/login/SALoginActivity.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/movie/SAMovieSearchActivity.kt
Labels: Mentor Needed, Merge Needed

#569 HW-6 ViewModel 적용
  2003/byiryu/app/build.gradle
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/BRApplication.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/mvvm/base/BRViewModelFactory.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/mvvm/base/viewmodel/BaseViewModel.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/mvvm/login/viewmodel/LoginViewModel.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/mvvm/login/views/LoginActivity.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/mvvm/main/viewmodel/MainViewModel.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/mvvm/main/views/MainActivity.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/mvvm/main/views/adapter/MainRecyclerAdapter.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/mvvm/main/views/adapter/MainRecyclerHolder.kt
Labels: Mentor Needed, Merge Needed

#582 [ADD]Create hwaniiidev folder & Update README.md
  2005/README.md
  2005/hwaniiidev/README.md
Labels: Mentor Needed, Merge Needed

#581 make folder and change readme
  2005/README.md
  2005/sangjinKIM93/README.md
Labels: Mentor Needed, Merge Needed

#587 2005/init readme
  2005/README.md
  2005/RyuC0605/README.md
Labels: Mentor Needed, Merge Needed

#576 Update README.md
  2005/README.md
  2005/chuuuul/README.md
Labels: Mentor Needed, Merge Needed

#578 2005/init readme
  2005/README.md
  2005/leechungwoo92/README.md
Labels: Mentor Needed, Merge Needed

#583 HW-2 Model Apply
  2004/invitejay/app/src/main/AndroidManifest.xml
  2004/invitejay/app/src/main/java/com/example/studyforkandroid/MainActivity.kt
  2004/invitejay/app/src/main/java/com/example/studyforkandroid/adapter/MovieAdapter.kt
  2004/invitejay/app/src/main/java/com/example/studyforkandroid/data/MovieResponse.kt
  2004/invitejay/app/src/main/java/com/example/studyforkandroid/data/source/MovieRepository.kt
  2004/invitejay/app/src/main/java/com/example/studyforkandroid/data/source/MovieRepositoryImpl.kt
  2004/invitejay/app/src/main/java/com/example/studyforkandroid/data/source/local/MovieLocalDataSource.kt
  2004/invitejay/app/src/main/java/com/example/studyforkandroid/data/source/local/MovieLocalDataSourceImpl.kt
  2004/invitejay/app/src/main/java/com/example/studyforkandroid/data/source/remote/MovieRemoteDataSource.kt
  2004/invitejay/app/src/main/java/com/example/studyforkandroid/data/source/remote/MovieRemoteDataSourceImpl.kt
  2004/invitejay/app/src/main/java/com/example/studyforkandroid/network/MovieApi.kt
  2004/invitejay/app/src/main/java/com/example/studyforkandroid/network/MovieClient.kt
  2004/invitejay/app/src/main/java/com/example/studyforkandroid/ui/MainActivity.kt
  2004/invitejay/app/src/main/res/layout/activity_main.xml
Labels: Mentor Needed, Merge Needed

#580 HW-7 Koin 적용
  2003/mtjin/AndroidArchitectureStudy/app/build.gradle
  2003/mtjin/AndroidArchitectureStudy/app/src/main/AndroidManifest.xml
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/api/ApiClient.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/data/search/source/MovieRepositoryImpl.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/data/search/source/local/MovieDatabase.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/di/KoinApplication.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/module/ApiModule.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/module/LocalDataModule.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/module/NetworkModule.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/module/RemoteDataModule.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/module/RepositoryModule.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/module/ViewModelModule.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/login/LoginActivity.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/search/MovieSearchActivity.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/splash/SplashActivity.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/utils/MyApplication.kt
Labels: Mentor Needed, Merge Needed

#572 HW-2 add Model Layer (Model 적용)
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/NaverAPI.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ToastExt.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/api/NaverAPI.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/base/BaseRecyclerViewHolder.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/data/MovieResponse.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/data/repository/NaverReopsitory.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/data/repository/NaverRepositoryImpl.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/data/source/NaverRemoteDataSource.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/data/source/NaverRemoteDataSourceImpl.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ext/ToastExt.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/network/CreateRetrofit.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/network/NaverMovieInterface.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/MainActivity.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/adapter/MovieRecyclerAdapter.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/viewholder/MovieRecyclerViewViewHolder.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/util/AbstractMapConverter.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/util/MapConverter.kt
Labels: Mentor Needed, Merge Needed

#570 HW-2 apply Model
  2004/eunjin-hong/app/src/main/java/com/eunice/eunicehong/data/model/Movie.kt
  2004/eunjin-hong/app/src/main/java/com/eunice/eunicehong/data/remote/MovieClient.kt
  2004/eunjin-hong/app/src/main/java/com/eunice/eunicehong/data/remote/MovieRemoteDataSource.kt
  2004/eunjin-hong/app/src/main/java/com/eunice/eunicehong/data/remote/MovieService.kt
  2004/eunjin-hong/app/src/main/java/com/eunice/eunicehong/data/repository/MovieRepository.kt
  2004/eunjin-hong/app/src/main/java/com/eunice/eunicehong/ui/MainActivity.kt
  2004/eunjin-hong/app/src/main/java/com/eunice/eunicehong/ui/MovieAdapter.kt
Labels: Mentor Needed, Merge Needed

#586 HW-7 Use Koin for DI
  2003/kangraemin/app/build.gradle
  2003/kangraemin/app/src/main/AndroidManifest.xml
  2003/kangraemin/app/src/main/java/com/example/kangraemin/base/KangBaseApplication.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/module/LocalDataModule.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/module/NetworkUtilModule.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/module/RemoteDataModule.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/module/RepositoryModule.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/module/ViewModelModule.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginActivity.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/main/MainActivity.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/splash/SplashActivity.kt
Labels: Mentor Needed, Merge Needed

#575 HW-2 apply Model Layer
  2004/kyudong3/.idea/gradle.xml
  2004/kyudong3/.idea/kotlinc.xml
  2004/kyudong3/app/build.gradle
  2004/kyudong3/app/src/main/java/com/example/kyudong3/MainActivity.kt
  2004/kyudong3/app/src/main/java/com/example/kyudong3/adapter/SearchMovieRvAdapter.kt
  2004/kyudong3/app/src/main/java/com/example/kyudong3/data/model/Movie.kt
  2004/kyudong3/app/src/main/java/com/example/kyudong3/data/remote/MovieRemoteDataSource.kt
  2004/kyudong3/app/src/main/java/com/example/kyudong3/data/remote/MovieRemoteDataSourceImpl.kt
  2004/kyudong3/app/src/main/java/com/example/kyudong3/data/repository/MovieRepository.kt
  2004/kyudong3/app/src/main/java/com/example/kyudong3/data/repository/MovieRepositoryImpl.kt
  2004/kyudong3/app/src/main/java/com/example/kyudong3/extension/Toast.kt
  2004/kyudong3/app/src/main/java/com/example/kyudong3/network/NaverApiService.kt
  2004/kyudong3/app/src/main/java/com/example/kyudong3/network/NaverApiServiceImpl.kt
  2004/kyudong3/app/src/main/java/com/example/kyudong3/network/RetrofitClient.kt
  2004/kyudong3/gradle.properties
Labels: Mentor Needed, Merge Needed

#590 2005/init-readme branch 기본 세팅
  2005/README.md
  2005/developer-sungjae/README.md
Labels: Mentor Needed, Merge Needed

#591 HW-2 apply Model Layer
  2004/jesterz91/app/build.gradle
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/data/local/MovieDatabase.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/data/local/dao/BaseDao.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/data/local/dao/MovieDao.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/data/local/model/MovieLocal.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/data/local/source/MovieLocalDataSource.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/data/local/source/MovieLocalDataSourceImpl.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/data/remote/api/MovieApi.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/data/remote/model/MovieRemote.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/data/remote/model/MovieSearchResponse.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/data/remote/source/MovieRemoteDataSource.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/data/remote/source/MovieRemoteDataSourceImpl.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/domain/entity/Movie.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/domain/mapper/Mapper.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/domain/mapper/MovieLocalMapper.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/domain/mapper/MovieRemoteMapper.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/domain/repository/MovieRepository.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/domain/repository/MovieRepositoryImpl.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/domain/usecase/GetMovieUseCase.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/domain/usecase/UseCase.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/common/BaseAdapter.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/constant/Constant.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/extension/ViewExtension.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/ui/MovieSearchActivity.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/ui/MovieSearchAdapter.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/ui/MovieSearchViewHolder.kt
  2004/jesterz91/build.gradle
Labels: Mentor Needed, Merge Needed

#589 HW-7 Koin 적용
  2003/byiryu/app/build.gradle
  2003/byiryu/app/src/main/java/com/byiryu/study/di/ActivityModule.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/di/ApplicationModule.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/di/ViewModelModule.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/model/remote/NaverHeaderInterceptor.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/model/remote/RemoteDataSource.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/network/NetworkService.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/BRApplication.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/mvvm/base/BRViewModelFactory.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/mvvm/login/views/LoginActivity.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/mvvm/main/views/MainActivity.kt
  2003/byiryu/build.gradle
Labels: Mentor Needed, Merge Needed

#588 HW-7 Koin 적용
  2003/tjdwlsl1021/app/build.gradle
  2003/tjdwlsl1021/app/src/main/AndroidManifest.xml
  2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/data/local/MovieDatabase.kt
  2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/data/remote/ServerURL.kt
  2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/data/remote/api/NaverMovieApi.kt
  2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/data/remote/network/NetworkService.kt
  2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/data/remote/network/RequestNaverApi.kt
  2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/data/remote/source/MovieRemoteDataSourceImpl.kt
  2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/data/repository/MovieRepositoryDataSet.kt
  2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/di/LocalDataModule.kt
  2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/di/RemoteDataModule.kt
  2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/di/RepositoryModule.kt
  2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/di/ViewModelModule.kt
  2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/ui/SearchMovieActivity.kt
  2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/ui/SearchMoviePresenter.kt
  2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/ui/base/AppApplication.kt
Labels: Mentor Needed, Merge Needed

#577 HW-2 Model layer 적용
  2004/nukeolaf/app/src/main/AndroidManifest.xml
  2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MainActivity.kt
  2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MovieItemListener.kt
  2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/RetrofitInterface.kt
  2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/data/local/MovieLocalDataSource.kt
  2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/data/local/MovieLocalDataSourceImpl.kt
  2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/data/model/MovieItem.kt
  2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/data/model/MovieResponse.kt
  2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/data/remote/MovieRemoteDataSource.kt
  2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/data/remote/MovieRemoteDataSourceImpl.kt
  2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/data/repository/MovieRepository.kt
  2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/data/repository/MovieRepositoryImpl.kt
  2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/network/RetrofitClient.kt
  2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/network/RetrofitInterface.kt
  2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/ui/MainActivity.kt
  2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/ui/MovieAdapter.kt
  2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/ui/MovieItemViewHolder.kt
  2004/nukeolaf/app/src/main/res/layout/activity_main.xml
  2004/nukeolaf/app/src/main/res/values/strings.xml
Labels: Mentor Needed, Merge Needed

#603 4. 본인저장소 2005/your_name 브랜치에서 StudyFork저장소의 2005/your_name 브랜치로 pr 생성 하시면 됩니다.
  2005/RyuC0605/Android_X/.gitignore
  2005/RyuC0605/Android_X/app/.gitignore
  2005/RyuC0605/Android_X/app/build.gradle
  2005/RyuC0605/Android_X/app/proguard-rules.pro
  2005/RyuC0605/Android_X/app/src/androidTest/java/r/test/rapp/ExampleInstrumentedTest.kt
  2005/RyuC0605/Android_X/app/src/main/AndroidManifest.xml
  2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/MainActivity.kt
  2005/RyuC0605/Android_X/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  2005/RyuC0605/Android_X/app/src/main/res/drawable/ic_launcher_background.xml
  2005/RyuC0605/Android_X/app/src/main/res/layout/activity_main.xml
  2005/RyuC0605/Android_X/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  2005/RyuC0605/Android_X/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  2005/RyuC0605/Android_X/app/src/main/res/mipmap-hdpi/ic_launcher.png
  2005/RyuC0605/Android_X/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  2005/RyuC0605/Android_X/app/src/main/res/mipmap-mdpi/ic_launcher.png
  2005/RyuC0605/Android_X/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  2005/RyuC0605/Android_X/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  2005/RyuC0605/Android_X/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  2005/RyuC0605/Android_X/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  2005/RyuC0605/Android_X/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  2005/RyuC0605/Android_X/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  2005/RyuC0605/Android_X/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  2005/RyuC0605/Android_X/app/src/main/res/values/colors.xml
  2005/RyuC0605/Android_X/app/src/main/res/values/strings.xml
  2005/RyuC0605/Android_X/app/src/main/res/values/styles.xml
  2005/RyuC0605/Android_X/app/src/test/java/r/test/rapp/ExampleUnitTest.kt
  2005/RyuC0605/Android_X/build.gradle
  2005/RyuC0605/Android_X/gradle.properties
  2005/RyuC0605/Android_X/gradle/wrapper/gradle-wrapper.jar
  2005/RyuC0605/Android_X/gradle/wrapper/gradle-wrapper.properties
  2005/RyuC0605/Android_X/gradlew
  2005/RyuC0605/Android_X/gradlew.bat
  2005/RyuC0605/Android_X/settings.gradle
Labels: Mentor Needed, Merge Needed

#606 android 프로젝트 추가
  2005/sangjinKIM93/newproject/.gitignore
  2005/sangjinKIM93/newproject/.idea/codeStyles/Project.xml
  2005/sangjinKIM93/newproject/.idea/codeStyles/codeStyleConfig.xml
  2005/sangjinKIM93/newproject/.idea/gradle.xml
  2005/sangjinKIM93/newproject/.idea/kotlinc.xml
  2005/sangjinKIM93/newproject/.idea/runConfigurations.xml
  2005/sangjinKIM93/newproject/app/.gitignore
  2005/sangjinKIM93/newproject/app/build.gradle
  2005/sangjinKIM93/newproject/app/proguard-rules.pro
  2005/sangjinKIM93/newproject/app/src/androidTest/java/com/sangjin/newproject/ExampleInstrumentedTest.kt
  2005/sangjinKIM93/newproject/app/src/main/AndroidManifest.xml
  2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MainActivity.kt
  2005/sangjinKIM93/newproject/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  2005/sangjinKIM93/newproject/app/src/main/res/drawable/ic_launcher_background.xml
  2005/sangjinKIM93/newproject/app/src/main/res/layout/activity_main.xml
  2005/sangjinKIM93/newproject/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  2005/sangjinKIM93/newproject/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  2005/sangjinKIM93/newproject/app/src/main/res/mipmap-hdpi/ic_launcher.png
  2005/sangjinKIM93/newproject/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  2005/sangjinKIM93/newproject/app/src/main/res/mipmap-mdpi/ic_launcher.png
  2005/sangjinKIM93/newproject/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  2005/sangjinKIM93/newproject/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  2005/sangjinKIM93/newproject/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  2005/sangjinKIM93/newproject/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  2005/sangjinKIM93/newproject/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  2005/sangjinKIM93/newproject/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  2005/sangjinKIM93/newproject/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  2005/sangjinKIM93/newproject/app/src/main/res/values/colors.xml
  2005/sangjinKIM93/newproject/app/src/main/res/values/strings.xml
  2005/sangjinKIM93/newproject/app/src/main/res/values/styles.xml
  2005/sangjinKIM93/newproject/app/src/test/java/com/sangjin/newproject/ExampleUnitTest.kt
  2005/sangjinKIM93/newproject/build.gradle
  2005/sangjinKIM93/newproject/gradle.properties
  2005/sangjinKIM93/newproject/gradle/wrapper/gradle-wrapper.jar
  2005/sangjinKIM93/newproject/gradle/wrapper/gradle-wrapper.properties
  2005/sangjinKIM93/newproject/gradlew
  2005/sangjinKIM93/newproject/gradlew.bat
  2005/sangjinKIM93/newproject/settings.gradle
Labels: Mentor Needed, Merge Needed

#604 프로젝트 생성 및 .gitignore 추가
  2005/developer-sungjae/ArchitectureStudy/.gitignore
  2005/developer-sungjae/ArchitectureStudy/.idea/codeStyles/Project.xml
  2005/developer-sungjae/ArchitectureStudy/.idea/codeStyles/codeStyleConfig.xml
  2005/developer-sungjae/ArchitectureStudy/.idea/runConfigurations.xml
  2005/developer-sungjae/ArchitectureStudy/app/.gitignore
  2005/developer-sungjae/ArchitectureStudy/app/build.gradle
  2005/developer-sungjae/ArchitectureStudy/app/proguard-rules.pro
  2005/developer-sungjae/ArchitectureStudy/app/src/androidTest/java/com/project/architecturestudy/ExampleInstrumentedTest.kt
  2005/developer-sungjae/ArchitectureStudy/app/src/main/AndroidManifest.xml
  2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/MainActivity.kt
  2005/developer-sungjae/ArchitectureStudy/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  2005/developer-sungjae/ArchitectureStudy/app/src/main/res/drawable/ic_launcher_background.xml
  2005/developer-sungjae/ArchitectureStudy/app/src/main/res/layout/activity_main.xml
  2005/developer-sungjae/ArchitectureStudy/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  2005/developer-sungjae/ArchitectureStudy/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  2005/developer-sungjae/ArchitectureStudy/app/src/main/res/mipmap-hdpi/ic_launcher.png
  2005/developer-sungjae/ArchitectureStudy/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  2005/developer-sungjae/ArchitectureStudy/app/src/main/res/mipmap-mdpi/ic_launcher.png
  2005/developer-sungjae/ArchitectureStudy/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  2005/developer-sungjae/ArchitectureStudy/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  2005/developer-sungjae/ArchitectureStudy/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  2005/developer-sungjae/ArchitectureStudy/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  2005/developer-sungjae/ArchitectureStudy/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  2005/developer-sungjae/ArchitectureStudy/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  2005/developer-sungjae/ArchitectureStudy/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  2005/developer-sungjae/ArchitectureStudy/app/src/main/res/values/colors.xml
  2005/developer-sungjae/ArchitectureStudy/app/src/main/res/values/strings.xml
  2005/developer-sungjae/ArchitectureStudy/app/src/main/res/values/styles.xml
  2005/developer-sungjae/ArchitectureStudy/app/src/test/java/com/project/architecturestudy/ExampleUnitTest.kt
  2005/developer-sungjae/ArchitectureStudy/build.gradle
  2005/developer-sungjae/ArchitectureStudy/gradle.properties
  2005/developer-sungjae/ArchitectureStudy/gradle/wrapper/gradle-wrapper.jar
  2005/developer-sungjae/ArchitectureStudy/gradle/wrapper/gradle-wrapper.properties
  2005/developer-sungjae/ArchitectureStudy/gradlew
  2005/developer-sungjae/ArchitectureStudy/gradlew.bat
  2005/developer-sungjae/ArchitectureStudy/settings.gradle
Labels: Mentor Needed, Merge Needed

#596 HW-3 Presneter 적용
  2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/ui/MainActivity.kt
  2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/ui/MainContract.kt
  2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/ui/MainPresenter.kt
Labels: Mentor Needed, Merge Needed

#607 사전과제2 - 프로젝트 생성
  2005/chuuuul/ArchitectureStudy/.gitignore
  2005/chuuuul/ArchitectureStudy/.idea/codeStyles/Project.xml
  2005/chuuuul/ArchitectureStudy/.idea/codeStyles/codeStyleConfig.xml
  2005/chuuuul/ArchitectureStudy/app/.gitignore
  2005/chuuuul/ArchitectureStudy/app/build.gradle
  2005/chuuuul/ArchitectureStudy/app/proguard-rules.pro
  2005/chuuuul/ArchitectureStudy/app/src/androidTest/java/com/example/architecture/ExampleInstrumentedTest.kt
  2005/chuuuul/ArchitectureStudy/app/src/main/AndroidManifest.xml
  2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/MainActivity.kt
  2005/chuuuul/ArchitectureStudy/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  2005/chuuuul/ArchitectureStudy/app/src/main/res/drawable/ic_launcher_background.xml
  2005/chuuuul/ArchitectureStudy/app/src/main/res/layout/activity_main.xml
  2005/chuuuul/ArchitectureStudy/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  2005/chuuuul/ArchitectureStudy/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  2005/chuuuul/ArchitectureStudy/app/src/main/res/mipmap-hdpi/ic_launcher.png
  2005/chuuuul/ArchitectureStudy/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  2005/chuuuul/ArchitectureStudy/app/src/main/res/mipmap-mdpi/ic_launcher.png
  2005/chuuuul/ArchitectureStudy/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  2005/chuuuul/ArchitectureStudy/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  2005/chuuuul/ArchitectureStudy/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  2005/chuuuul/ArchitectureStudy/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  2005/chuuuul/ArchitectureStudy/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  2005/chuuuul/ArchitectureStudy/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  2005/chuuuul/ArchitectureStudy/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  2005/chuuuul/ArchitectureStudy/app/src/main/res/values/colors.xml
  2005/chuuuul/ArchitectureStudy/app/src/main/res/values/strings.xml
  2005/chuuuul/ArchitectureStudy/app/src/main/res/values/styles.xml
  2005/chuuuul/ArchitectureStudy/app/src/test/java/com/example/architecture/ExampleUnitTest.kt
  2005/chuuuul/ArchitectureStudy/build.gradle
  2005/chuuuul/ArchitectureStudy/gradle.properties
  2005/chuuuul/ArchitectureStudy/gradle/wrapper/gradle-wrapper.jar
  2005/chuuuul/ArchitectureStudy/gradle/wrapper/gradle-wrapper.properties
  2005/chuuuul/ArchitectureStudy/gradlew
  2005/chuuuul/ArchitectureStudy/gradlew.bat
  2005/chuuuul/ArchitectureStudy/settings.gradle
Labels: Mentor Needed, Merge Needed

#601 HW-3 feat: add Presenter layer(프레젠터 추가)
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/base/BaseActivity.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/base/BaseRecyclerAdapter.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/base/RecyclerViewModel.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/network/CreateRetrofit.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/presenter/MovieContract.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/presenter/MoviePresenter.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/provider/ResourceProvider.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/provider/ResourceProviderImpl.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/MainActivity.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/adapter/MovieRecyclerAdapter.kt
  2004/taeseongyun/app/src/main/res/layout/activity_main.xml
  2004/taeseongyun/app/src/main/res/values/strings.xml
Labels: Mentor Needed, Merge Needed

#600 HW3 - Presenter Layer
  2004/invitejay/app/src/main/java/com/example/studyforkandroid/base/BasePresenter.kt
  2004/invitejay/app/src/main/java/com/example/studyforkandroid/presenter/MovieContract.kt
  2004/invitejay/app/src/main/java/com/example/studyforkandroid/presenter/MoviePresenter.kt
  2004/invitejay/app/src/main/java/com/example/studyforkandroid/ui/MainActivity.kt
Labels: Mentor Needed, Merge Needed

#597 HW-3 apply mvp pattern
  2004/kyudong3/app/build.gradle
  2004/kyudong3/app/src/main/AndroidManifest.xml
  2004/kyudong3/app/src/main/java/com/example/kyudong3/MainActivity.kt
  2004/kyudong3/app/src/main/java/com/example/kyudong3/data/local/MovieDao.kt
  2004/kyudong3/app/src/main/java/com/example/kyudong3/data/local/MovieDatabase.kt
  2004/kyudong3/app/src/main/java/com/example/kyudong3/data/local/MovieLocalDataSource.kt
  2004/kyudong3/app/src/main/java/com/example/kyudong3/data/local/MovieLocalDataSourceImpl.kt
  2004/kyudong3/app/src/main/java/com/example/kyudong3/data/local/MovieLocalEntity.kt
  2004/kyudong3/app/src/main/java/com/example/kyudong3/data/model/Movie.kt
  2004/kyudong3/app/src/main/java/com/example/kyudong3/data/remote/MovieRemote.kt
  2004/kyudong3/app/src/main/java/com/example/kyudong3/data/remote/MovieRemoteDataSourceImpl.kt
  2004/kyudong3/app/src/main/java/com/example/kyudong3/data/repository/MovieRepository.kt
  2004/kyudong3/app/src/main/java/com/example/kyudong3/data/repository/MovieRepositoryImpl.kt
  2004/kyudong3/app/src/main/java/com/example/kyudong3/mapper/Mapper.kt
  2004/kyudong3/app/src/main/java/com/example/kyudong3/mapper/MovieLocalMapper.kt
  2004/kyudong3/app/src/main/java/com/example/kyudong3/mapper/MovieRemoteMapper.kt
  2004/kyudong3/app/src/main/java/com/example/kyudong3/network/NaverApiService.kt
  2004/kyudong3/app/src/main/java/com/example/kyudong3/ui/MainActivity.kt
  2004/kyudong3/app/src/main/java/com/example/kyudong3/ui/movie/presenter/MovieContract.kt
  2004/kyudong3/app/src/main/java/com/example/kyudong3/ui/movie/presenter/MoviePresenter.kt
  2004/kyudong3/app/src/main/res/layout/activity_main.xml
Labels: Mentor Needed, Merge Needed

#608 HW-3 MVP pattern
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/data/local/dao/MovieDao.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/data/local/source/MovieLocalDataSourceImpl.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/domain/repository/MovieRepositoryImpl.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/common/BaseActivity.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/common/BaseContract.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/common/BasePresenter.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/ui/MovieSearchActivity.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/ui/MovieSearchContract.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/ui/MovieSearchPresenter.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/util/ResourceProvider.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/util/ResourceProviderImpl.kt
Labels: Mentor Needed, Merge Needed

#610 AndroidProject 생성 + gitignore추가
  2005/leechungwoo92/StudyForkProject/.gitignore
  2005/leechungwoo92/StudyForkProject/.idea/codeStyles/Project.xml
  2005/leechungwoo92/StudyForkProject/.idea/codeStyles/codeStyleConfig.xml
  2005/leechungwoo92/StudyForkProject/.idea/gradle.xml
  2005/leechungwoo92/StudyForkProject/.idea/runConfigurations.xml
  2005/leechungwoo92/StudyForkProject/app/.gitignore
  2005/leechungwoo92/StudyForkProject/app/build.gradle
  2005/leechungwoo92/StudyForkProject/app/proguard-rules.pro
  2005/leechungwoo92/StudyForkProject/app/src/androidTest/java/com/lllccww/studyforkproject/ExampleInstrumentedTest.kt
  2005/leechungwoo92/StudyForkProject/app/src/main/AndroidManifest.xml
  2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/MainActivity.kt
  2005/leechungwoo92/StudyForkProject/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  2005/leechungwoo92/StudyForkProject/app/src/main/res/drawable/ic_launcher_background.xml
  2005/leechungwoo92/StudyForkProject/app/src/main/res/layout/activity_main.xml
  2005/leechungwoo92/StudyForkProject/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  2005/leechungwoo92/StudyForkProject/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  2005/leechungwoo92/StudyForkProject/app/src/main/res/mipmap-hdpi/ic_launcher.png
  2005/leechungwoo92/StudyForkProject/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  2005/leechungwoo92/StudyForkProject/app/src/main/res/mipmap-mdpi/ic_launcher.png
  2005/leechungwoo92/StudyForkProject/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  2005/leechungwoo92/StudyForkProject/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  2005/leechungwoo92/StudyForkProject/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  2005/leechungwoo92/StudyForkProject/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  2005/leechungwoo92/StudyForkProject/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  2005/leechungwoo92/StudyForkProject/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  2005/leechungwoo92/StudyForkProject/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  2005/leechungwoo92/StudyForkProject/app/src/main/res/values/colors.xml
  2005/leechungwoo92/StudyForkProject/app/src/main/res/values/strings.xml
  2005/leechungwoo92/StudyForkProject/app/src/main/res/values/styles.xml
  2005/leechungwoo92/StudyForkProject/app/src/test/java/com/lllccww/studyforkproject/ExampleUnitTest.kt
  2005/leechungwoo92/StudyForkProject/build.gradle
  2005/leechungwoo92/StudyForkProject/gradle.properties
  2005/leechungwoo92/StudyForkProject/gradle/wrapper/gradle-wrapper.jar
  2005/leechungwoo92/StudyForkProject/gradle/wrapper/gradle-wrapper.properties
  2005/leechungwoo92/StudyForkProject/gradlew
  2005/leechungwoo92/StudyForkProject/gradlew.bat
  2005/leechungwoo92/StudyForkProject/settings.gradle
Labels: Mentor Needed, Merge Needed

#612 [ADD]Create Project with .gitignore
  .idea/.DS_Store
  2005/hwaniiidev/Architecture/.gitignore
  2005/hwaniiidev/Architecture/.idea/codeStyles/Project.xml
  2005/hwaniiidev/Architecture/.idea/codeStyles/codeStyleConfig.xml
  2005/hwaniiidev/Architecture/.idea/runConfigurations.xml
  2005/hwaniiidev/Architecture/app/.gitignore
  2005/hwaniiidev/Architecture/app/build.gradle
  2005/hwaniiidev/Architecture/app/proguard-rules.pro
  2005/hwaniiidev/Architecture/app/src/androidTest/java/com/hwaniiidev/architecture/ExampleInstrumentedTest.kt
  2005/hwaniiidev/Architecture/app/src/main/AndroidManifest.xml
  2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/MainActivity.kt
  2005/hwaniiidev/Architecture/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  2005/hwaniiidev/Architecture/app/src/main/res/drawable/ic_launcher_background.xml
  2005/hwaniiidev/Architecture/app/src/main/res/layout/activity_main.xml
  2005/hwaniiidev/Architecture/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  2005/hwaniiidev/Architecture/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  2005/hwaniiidev/Architecture/app/src/main/res/mipmap-hdpi/ic_launcher.png
  2005/hwaniiidev/Architecture/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  2005/hwaniiidev/Architecture/app/src/main/res/mipmap-mdpi/ic_launcher.png
  2005/hwaniiidev/Architecture/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  2005/hwaniiidev/Architecture/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  2005/hwaniiidev/Architecture/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  2005/hwaniiidev/Architecture/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  2005/hwaniiidev/Architecture/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  2005/hwaniiidev/Architecture/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  2005/hwaniiidev/Architecture/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  2005/hwaniiidev/Architecture/app/src/main/res/values/colors.xml
  2005/hwaniiidev/Architecture/app/src/main/res/values/strings.xml
  2005/hwaniiidev/Architecture/app/src/main/res/values/styles.xml
  2005/hwaniiidev/Architecture/app/src/test/java/com/hwaniiidev/architecture/ExampleUnitTest.kt
  2005/hwaniiidev/Architecture/build.gradle
  2005/hwaniiidev/Architecture/gradle.properties
  2005/hwaniiidev/Architecture/gradle/wrapper/gradle-wrapper.jar
  2005/hwaniiidev/Architecture/gradle/wrapper/gradle-wrapper.properties
  2005/hwaniiidev/Architecture/gradlew
  2005/hwaniiidev/Architecture/gradlew.bat
  2005/hwaniiidev/Architecture/settings.gradle
Labels: Answer Needed, Mentor Needed

#599 HW-3 apply MVP pattern
  2004/eunjin-hong/app/src/main/AndroidManifest.xml
  2004/eunjin-hong/app/src/main/java/com/eunice/eunicehong/data/repository/MovieRepository.kt
  2004/eunjin-hong/app/src/main/java/com/eunice/eunicehong/data/source/MovieDataSource.kt
  2004/eunjin-hong/app/src/main/java/com/eunice/eunicehong/data/source/MovieRepository.kt
  2004/eunjin-hong/app/src/main/java/com/eunice/eunicehong/data/source/remote/MovieClient.kt
  2004/eunjin-hong/app/src/main/java/com/eunice/eunicehong/data/source/remote/MovieRemoteDataSource.kt
  2004/eunjin-hong/app/src/main/java/com/eunice/eunicehong/data/source/remote/MovieService.kt
  2004/eunjin-hong/app/src/main/java/com/eunice/eunicehong/provider/SuggestionProvider.kt
  2004/eunjin-hong/app/src/main/java/com/eunice/eunicehong/ui/MainActivity.kt
  2004/eunjin-hong/app/src/main/java/com/eunice/eunicehong/ui/MovieAdapter.kt
  2004/eunjin-hong/app/src/main/java/com/eunice/eunicehong/ui/MovieCache.kt
  2004/eunjin-hong/app/src/main/java/com/eunice/eunicehong/ui/MovieContract.kt
  2004/eunjin-hong/app/src/main/java/com/eunice/eunicehong/ui/MoviePreferences.kt
  2004/eunjin-hong/app/src/main/java/com/eunice/eunicehong/ui/MoviePresenter.kt
  2004/eunjin-hong/app/src/main/java/com/eunice/eunicehong/util/ToastMessage.kt
  2004/eunjin-hong/app/src/main/res/drawable/ic_movie.xml
  2004/eunjin-hong/app/src/main/res/layout/activity_main.xml
  2004/eunjin-hong/app/src/main/res/menu/menu_main.xml
  2004/eunjin-hong/app/src/main/res/values/strings.xml
  2004/eunjin-hong/app/src/main/res/values/styles.xml
  2004/eunjin-hong/app/src/main/res/xml/searchable.xml
Labels: Review Needed
