Repository StudyFork/GoogryAndroidArchitectureStudy, pull requests merged in 2020-10, with the labels that each got.

#813 HW-2 : MODEL 구현
  class13/ddochi93/Dkarch/app/build.gradle
  class13/ddochi93/Dkarch/app/src/main/AndroidManifest.xml
  class13/ddochi93/Dkarch/app/src/main/java/com/example/dkarch/MyApplication.kt
  class13/ddochi93/Dkarch/app/src/main/java/com/example/dkarch/domain/globalconsts/Consts.kt
  class13/ddochi93/Dkarch/app/src/main/java/com/example/dkarch/domain/repository/LocalDataSourceRepository.kt
  class13/ddochi93/Dkarch/app/src/main/java/com/example/dkarch/domain/repository/NaverMovieRepository.kt
  class13/ddochi93/Dkarch/app/src/main/java/com/example/dkarch/domain/repository/RemoteDataSourceRepository.kt
  class13/ddochi93/Dkarch/app/src/main/java/com/example/dkarch/domain/repository/SharedPrefRepository.kt
  class13/ddochi93/Dkarch/app/src/main/java/com/example/dkarch/domain/repositoryImpl/LocalDataSourceRepositoryImpl.kt
  class13/ddochi93/Dkarch/app/src/main/java/com/example/dkarch/domain/repositoryImpl/NaverMovieRepositoryImpl.kt
  class13/ddochi93/Dkarch/app/src/main/java/com/example/dkarch/domain/repositoryImpl/RemoteDataSourceRepositoryImpl.kt
  class13/ddochi93/Dkarch/app/src/main/java/com/example/dkarch/domain/repositoryImpl/SharedPrefRepositoryImpl.kt
  class13/ddochi93/Dkarch/app/src/main/java/com/example/dkarch/domain/sharedpref/SharedPreferenceHelper.java
  class13/ddochi93/Dkarch/app/src/main/java/com/example/dkarch/domain/util/ImageViewUtil.kt
  class13/ddochi93/Dkarch/app/src/main/java/com/example/dkarch/domain/util/SharedPreferenceUtil.kt
  class13/ddochi93/Dkarch/app/src/main/java/com/example/dkarch/domain/util/loadUriCenterCrop.kt
  class13/ddochi93/Dkarch/app/src/main/java/com/example/dkarch/presentation/MainActivity.kt
  class13/ddochi93/Dkarch/app/src/main/java/com/example/dkarch/presentation/QueryHistoryAdapter.kt
  class13/ddochi93/Dkarch/app/src/main/java/com/example/dkarch/presentation/QueryHistoryFragment.kt
  class13/ddochi93/Dkarch/app/src/main/res/layout/activity_main.xml
  class13/ddochi93/Dkarch/app/src/main/res/layout/fragment_query_history.xml
  class13/ddochi93/Dkarch/app/src/main/res/layout/item_movie.xml
  class13/ddochi93/Dkarch/app/src/main/res/layout/item_query_history.xml
  class13/ddochi93/Dkarch/app/src/main/res/values/strings.xml
Labels: Mentor Needed, Merge Needed

#816 HW-4 databinding 적용
  class13/HyeJeongHan/project/app/build.gradle
  class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/Extension.kt
  class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/ui/MainActivity.kt
  class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/ui/MovieAdapter.kt
  class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/ui/QueryHistoryAdapter.kt
  class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/ui/QueryHistoryDialog.kt
  class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/ui/base/BaseActivity.kt
  class13/HyeJeongHan/project/app/src/main/res/layout/activity_main.xml
  class13/HyeJeongHan/project/app/src/main/res/layout/dialog_query_history.xml
  class13/HyeJeongHan/project/app/src/main/res/layout/item_movie.xml
  class13/HyeJeongHan/project/app/src/main/res/layout/item_query.xml
  class13/HyeJeongHan/project/build.gradle
  class13/HyeJeongHan/project/gradle/wrapper/gradle-wrapper.properties
Labels: Mentor Needed, Merge Needed

#819 HW-5 : MVVM
  class13/CmplxN/AAS/app/src/main/java/com/example/aas/base/BaseActivity.kt
  class13/CmplxN/AAS/app/src/main/java/com/example/aas/base/BaseContract.kt
  class13/CmplxN/AAS/app/src/main/java/com/example/aas/base/BaseDialogFragment.kt
  class13/CmplxN/AAS/app/src/main/java/com/example/aas/base/BaseViewModel.kt
  class13/CmplxN/AAS/app/src/main/java/com/example/aas/data/model/Movie.kt
  class13/CmplxN/AAS/app/src/main/java/com/example/aas/ui/BindingAdapters.kt
  class13/CmplxN/AAS/app/src/main/java/com/example/aas/ui/main/MainActivity.kt
  class13/CmplxN/AAS/app/src/main/java/com/example/aas/ui/main/MainContract.kt
  class13/CmplxN/AAS/app/src/main/java/com/example/aas/ui/main/MainPresenter.kt
  class13/CmplxN/AAS/app/src/main/java/com/example/aas/ui/main/MainViewModel.kt
  class13/CmplxN/AAS/app/src/main/java/com/example/aas/ui/main/MovieAdapter.kt
  class13/CmplxN/AAS/app/src/main/java/com/example/aas/ui/savedquerydialog/SavedQueryContract.kt
  class13/CmplxN/AAS/app/src/main/java/com/example/aas/ui/savedquerydialog/SavedQueryDialogFragment.kt
  class13/CmplxN/AAS/app/src/main/java/com/example/aas/ui/savedquerydialog/SavedQueryPresenter.kt
  class13/CmplxN/AAS/app/src/main/res/layout/activity_main.xml
Labels: Mentor Needed, Merge Needed

#818 HW-4 databinding 적용
  class13/Sangmeebee/MyProject/app/build.gradle
  class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/extension/BindingAdapters.kt
  class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/ui/MovieAdapter.kt
  class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/ui/TitleFragmentDialog.kt
  class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/ui/base/BaseActivity.kt
  class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/ui/main/MainActivity.kt
  class13/Sangmeebee/MyProject/app/src/main/res/layout/activity_main.xml
  class13/Sangmeebee/MyProject/app/src/main/res/layout/dialog_fragment_title.xml
  class13/Sangmeebee/MyProject/app/src/main/res/layout/movie_item.xml
Labels: Mentor Needed, Merge Needed

#817 HW-5 : MVVM
  class13/Hwangjunhong/ArchitectureStudy/app/build.gradle
  class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ext/ContextExt.kt
  class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ext/FuncExt.kt
  class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ext/RatingBarExt.kt
  class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ext/TextViewExt.kt
  class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ext/ViewExt.kt
  class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/main/MainActivity.kt
  class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/main/MainContract.kt
  class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/main/MainPresenter.kt
  class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/main/MainViewModel.kt
  class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/main/adapter/MovieAdapter.kt
  class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/moviedialog/MovieListDialogContract.kt
  class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/moviedialog/MovieListDialogFragment.kt
  class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/moviedialog/MovieListDialogPresenter.kt
  class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/moviedialog/MovieListDialogViewModel.kt
  class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/moviedialog/adapter/MovieSearchListAdapter.kt
  class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/moviedialog/holder/MovieSearchListViewHolder.kt
  class13/Hwangjunhong/ArchitectureStudy/app/src/main/res/layout/activity_main.xml
  class13/Hwangjunhong/ArchitectureStudy/app/src/main/res/layout/dialog_fragment_movie_list.xml
  class13/Hwangjunhong/ArchitectureStudy/app/src/main/res/layout/item_movie_list.xml
  class13/Hwangjunhong/ArchitectureStudy/app/src/main/res/layout/item_movie_search_list.xml
  class13/Hwangjunhong/ArchitectureStudy/app/src/main/res/values/strings.xml
Labels: Mentor Needed, Merge Needed

#821 HW-5 MVVM
  class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/ui/MainActivity.kt
  class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/ui/MainContract.kt
  class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/ui/MainPresenter.kt
  class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/ui/MainViewModel.kt
  class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/ui/MovieAdapter.kt
  class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/ui/QueryHistoryAdapter.kt
  class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/ui/QueryHistoryContract.kt
  class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/ui/QueryHistoryDialog.kt
  class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/ui/QueryHistoryPresenter.kt
  class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/ui/QueryHistoryViewModel.kt
  class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/ui/RecyclerViewExtension.kt
  class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/ui/base/BaseActivity.kt
  class13/HyeJeongHan/project/app/src/main/res/layout/activity_main.xml
  class13/HyeJeongHan/project/app/src/main/res/layout/dialog_query_history.xml
Labels: Mentor Needed, Merge Needed

#822 HW-5 : MVVM
  class13/Sangmeebee/MyProject/app/src/main/AndroidManifest.xml
  class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/data/model/Items.kt
  class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/data/sharedPreferences/App.kt
  class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/data/sharedPreferences/Preferences.kt
  class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/data/source/local/NaverLocalDataSourceImpl.kt
  class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/extension/BindingAdapters.kt
  class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/extension/ToastExt.kt
  class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/ui/MainActivity.kt
  class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/ui/MovieAdapter.kt
  class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/ui/OnListItemSelectedInterface.kt
  class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/ui/TitleAdapter.kt
  class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/ui/TitleFragmentDialog.kt
  class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/ui/base/BaseActivity.kt
  class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/ui/base/BaseContract.kt
  class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/ui/base/BasePresenter.kt
  class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/ui/main/MainActivity.kt
  class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/ui/main/MainContract.kt
  class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/ui/main/MainPresenter.kt
  class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/viewmodel/MainViewModel.kt
  class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/viewmodel/TitleViewModel.kt
  class13/Sangmeebee/MyProject/app/src/main/res/layout/activity_main.xml
  class13/Sangmeebee/MyProject/app/src/main/res/layout/dialog_fragment_title.xml
  class13/Sangmeebee/MyProject/app/src/main/res/layout/movie_item.xml
  class13/Sangmeebee/MyProject/app/src/main/res/layout/title_list.xml
  class13/Sangmeebee/MyProject/app/src/main/res/values/strings.xml
Labels: Mentor Needed, Review Needed

#823 HW-5 MVVM 적용
  class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/extension/BindingViewExtension.kt
  class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/observer/MainViewModel.kt
  class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/observer/RecentViewModel.kt
  class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/ui/main/MainActivity.kt
  class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/ui/main/MainContract.kt
  class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/ui/main/MainPresenter.kt
  class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/ui/main/MovieSearchAdapter.kt
  class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/ui/rencentdialog/RecentMovieContract.kt
  class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/ui/rencentdialog/RecentMovieDialog.kt
  class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/ui/rencentdialog/RecentMoviePresenter.kt
  class13/camai/ArchitectureStudy/app/src/main/res/layout/activity_main.xml
  class13/camai/ArchitectureStudy/app/src/main/res/layout/recent_movie_list_popup.xml
Labels: Mentor Needed, Merge Needed

#824 HW-6 : AAC ViewModel & LiveData
  class13/CmplxN/AAS/app/build.gradle
  class13/CmplxN/AAS/app/src/main/java/com/example/aas/base/BaseViewModel.kt
  class13/CmplxN/AAS/app/src/main/java/com/example/aas/ui/main/MainActivity.kt
  class13/CmplxN/AAS/app/src/main/java/com/example/aas/ui/main/MainViewModel.kt
  class13/CmplxN/AAS/app/src/main/java/com/example/aas/ui/main/MovieAdapter.kt
  class13/CmplxN/AAS/app/src/main/res/layout/activity_main.xml
Labels: Mentor Needed, Merge Needed

#826 HW-6 : AAC ViewModel & LiveData
  class13/HyeJeongHan/project/.idea/jarRepositories.xml
  class13/HyeJeongHan/project/.idea/kotlinc.xml
  class13/HyeJeongHan/project/.idea/misc.xml
  class13/HyeJeongHan/project/app/build.gradle
  class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/ui/MainActivity.kt
  class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/ui/MainViewModel.kt
  class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/ui/QueryHistoryDialog.kt
  class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/ui/QueryHistoryViewModel.kt
  class13/HyeJeongHan/project/app/src/main/res/layout/dialog_query_history.xml
Labels: Mentor Needed, Merge Needed

#828 HW-6 AAC ViewModel & LiveData 적용
  class13/camai/ArchitectureStudy/app/build.gradle
  class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/extension/BindingViewExtension.kt
  class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/observer/MainViewModel.kt
  class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/observer/MainViewModelFactory.kt
  class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/observer/RecentViewModel.kt
  class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/ui/main/MainActivity.kt
  class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/ui/rencentdialog/RecentMovieDialog.kt
  class13/camai/ArchitectureStudy/app/src/main/res/layout/recent_movie_list_popup.xml
Labels: Mentor Needed, Merge Needed

#827 HW-6 : AAC ViewModel & LiveData
  class13/Sangmeebee/MyProject/app/build.gradle
  class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/ui/MainActivity.kt
  class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/ui/TitleFragmentDialog.kt
  class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/viewmodel/MainViewModel.kt
  class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/viewmodel/TitleViewModel.kt
Labels: Mentor Needed, Merge Needed

#825 HW-6 : AAC ViewModel & LiveData
  class13/Hwangjunhong/ArchitectureStudy/app/build.gradle
  class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ext/ViewExt.kt
  class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/base/BaseActivity.kt
  class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/base/BaseViewModel.kt
  class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/main/MainActivity.kt
  class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/main/MainViewModel.kt
  class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/main/adapter/MovieAdapter.kt
  class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/moviedialog/MovieListDialogFragment.kt
  class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/moviedialog/MovieListDialogViewModel.kt
  class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/moviedialog/adapter/MovieSearchListAdapter.kt
  class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/moviedialog/holder/MovieSearchListViewHolder.kt
  class13/Hwangjunhong/ArchitectureStudy/app/src/main/res/layout/activity_main.xml
  class13/Hwangjunhong/ArchitectureStudy/app/src/main/res/layout/dialog_fragment_movie_list.xml
  class13/Hwangjunhong/ArchitectureStudy/app/src/main/res/layout/item_movie_search_list.xml
  class13/Hwangjunhong/ArchitectureStudy/app/src/main/res/values/strings.xml
Labels: Mentor Needed, Merge Needed

#834 첫번째 과제(15기 강지회)
  class15/README.md
  class15/jihoi-kang/README.md
Labels: Mentor Needed, Merge Needed

#832 HW-1 첫번째 과제 작업(15기 임규진)
  class15/README.md
  class15/dktsudgg/README.md
Labels: Mentor Needed, Merge Needed

#835 HW-1 첫번째 과제 작업(15기 이동훈)
  class15/README.md
  class15/realizer12/README.md
Labels: Mentor Needed, Merge Needed

#836 HW - 7 : DI(Hilt)
  class13/CmplxN/AAS/app/build.gradle
  class13/CmplxN/AAS/app/src/main/java/com/example/aas/MyApplication.kt
  class13/CmplxN/AAS/app/src/main/java/com/example/aas/data/network/RetrofitManager.kt
  class13/CmplxN/AAS/app/src/main/java/com/example/aas/data/repository/MovieSearchRepositoryImpl.kt
  class13/CmplxN/AAS/app/src/main/java/com/example/aas/data/source/local/LocalDataSourceImpl.kt
  class13/CmplxN/AAS/app/src/main/java/com/example/aas/data/source/remote/RemoteDataSourceImpl.kt
  class13/CmplxN/AAS/app/src/main/java/com/example/aas/ui/main/MainActivity.kt
  class13/CmplxN/AAS/app/src/main/java/com/example/aas/ui/main/MainViewModel.kt
  class13/CmplxN/AAS/build.gradle
Labels: Mentor Needed, Merge Needed

#837 HW-7 : Hilt
  class13/Hwangjunhong/ArchitectureStudy/app/build.gradle
  class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/MainModule.kt
  class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/MyApplication.kt
  class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/data/network/RetrofitCreator.kt
  class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/data/repository/RepositoryDataSourceImpl.kt
  class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/data/source/local/LocalDataSourceImpl.kt
  class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/data/source/remote/RemoteDataSourceImpl.kt
  class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/main/MainActivity.kt
  class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/main/MainViewModel.kt
  class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/moviedialog/MovieListDialogFragment.kt
  class13/Hwangjunhong/ArchitectureStudy/app/src/main/java/com/hong/architecturestudy/ui/moviedialog/MovieListDialogViewModel.kt
  class13/Hwangjunhong/ArchitectureStudy/build.gradle
Labels: Mentor Needed, Merge Needed

#845 14기 이재현 README template 추가
  class14/README.md
  class14/juan-rybczinski/README.md
Labels: Mentor Needed, Merge Needed

#850 14기 김상명 README template 추가
  class14/README.md
  class14/myung777/README.md
Labels: Mentor Needed, Merge Needed

#839 Class14/init readme
  class14/README.md
  class14/simuelunbo/README.md
Labels: Mentor Needed, Merge Needed

#848 14기 정상훈 README template 추가
  class14/README.md
  class14/hunihun/README.md
Labels: Mentor Needed, Merge Needed

#842 HW-1 첫번째 과제 (15기 한해인)
  class15/README.md
  class15/hhi-5258/README.md
Labels: Mentor Needed, Merge Needed

#851 Class14/init readme(14기 함도영)
  class14/README.md
  class14/onxmoreplz/README.md
Labels: Mentor Needed, Merge Needed

#847 HW-1 사전과제
  class14/README.md
  class14/dev-donghwan/README.md
Labels: Mentor Needed, Merge Needed

#849 HW-7 Hilt
  class13/HyeJeongHan/project/app/build.gradle
  class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/GlobalApplication.kt
  class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/data/network/ServiceClient.kt
  class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/data/repository/NaverRepositoryImpl.kt
  class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/data/source/local/NaverLocalDataSourceImpl.kt
  class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/data/source/remote/NaverRemoteDataSourceImpl.kt
  class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/ui/MainActivity.kt
  class13/HyeJeongHan/project/app/src/main/java/com/hjhan/hyejeong/ui/MainViewModel.kt
  class13/HyeJeongHan/project/build.gradle
Labels: Mentor Needed, Merge Needed

#846 HW-7 Hilt 적용
  class13/camai/ArchitectureStudy/app/build.gradle
  class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/data/network/MovieApiServiceImpl.kt
  class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/data/repository/MovieRepository.kt
  class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/data/repository/MovieRepositoryImpl.kt
  class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/data/source/local/MovieLocalDataSource.kt
  class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/data/source/local/MovieLocalDataSourceImpl.kt
  class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/data/source/remote/MovieRemoteDataSourceImpl.kt
  class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/observer/MainViewModel.kt
  class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/observer/MainViewModelFactory.kt
  class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/ui/ApplicationContext.kt
  class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/ui/main/MainActivity.kt
  class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/ui/rencentdialog/RecentMovieDialog.kt
  class13/camai/ArchitectureStudy/app/src/main/java/com/camai/archtecherstudy/utils/Constans.kt
  class13/camai/ArchitectureStudy/build.gradle
Labels: Mentor Needed, Merge Needed

#852 HW-8 : Multi Module
  class13/CmplxN/AAS/DataModule/.gitignore
  class13/CmplxN/AAS/DataModule/build.gradle
  class13/CmplxN/AAS/DataModule/consumer-rules.pro
  class13/CmplxN/AAS/DataModule/proguard-rules.pro
  class13/CmplxN/AAS/DataModule/src/androidTest/java/com/example/datamodule/ExampleInstrumentedTest.kt
  class13/CmplxN/AAS/DataModule/src/main/AndroidManifest.xml
  class13/CmplxN/AAS/DataModule/src/main/java/com/example/datamodule/data/model/ApiResult.kt
  class13/CmplxN/AAS/DataModule/src/main/java/com/example/datamodule/data/model/Movie.kt
  class13/CmplxN/AAS/DataModule/src/main/java/com/example/datamodule/data/network/NaverMoviesApi.kt
  class13/CmplxN/AAS/DataModule/src/main/java/com/example/datamodule/data/network/RetrofitManager.kt
  class13/CmplxN/AAS/DataModule/src/main/java/com/example/datamodule/data/repository/MovieSearchRepository.kt
  class13/CmplxN/AAS/DataModule/src/main/java/com/example/datamodule/data/repository/MovieSearchRepositoryImpl.kt
  class13/CmplxN/AAS/DataModule/src/main/java/com/example/datamodule/data/source/local/LocalDataSource.kt
  class13/CmplxN/AAS/DataModule/src/main/java/com/example/datamodule/data/source/local/LocalDataSourceImpl.kt
  class13/CmplxN/AAS/DataModule/src/main/java/com/example/datamodule/data/source/remote/RemoteDataSource.kt
  class13/CmplxN/AAS/DataModule/src/main/java/com/example/datamodule/data/source/remote/RemoteDataSourceImpl.kt
  class13/CmplxN/AAS/DataModule/src/test/java/com/example/datamodule/ExampleUnitTest.kt
  class13/CmplxN/AAS/app/build.gradle
  class13/CmplxN/AAS/app/src/main/java/com/example/aas/MyApplication.kt
  class13/CmplxN/AAS/app/src/main/java/com/example/aas/ui/BindingAdapters.kt
  class13/CmplxN/AAS/app/src/main/java/com/example/aas/ui/main/MainViewModel.kt
  class13/CmplxN/AAS/app/src/main/java/com/example/aas/ui/main/MovieAdapter.kt
  class13/CmplxN/AAS/app/src/main/java/com/example/aas/ui/main/MovieViewHolder.kt
  class13/CmplxN/AAS/app/src/main/res/layout/item_movie.xml
  class13/CmplxN/AAS/config.gradle
  class13/CmplxN/AAS/settings.gradle
Labels: Mentor Needed, Merge Needed

#853 2주차 과제: 프로젝트 생성, gitignore 수정
  class14/juan-rybczinski/GoogryAndroidArchitectureStudy/.gitignore
  class14/juan-rybczinski/GoogryAndroidArchitectureStudy/.idea/.gitignore
  class14/juan-rybczinski/GoogryAndroidArchitectureStudy/.idea/compiler.xml
  class14/juan-rybczinski/GoogryAndroidArchitectureStudy/.idea/gradle.xml
  class14/juan-rybczinski/GoogryAndroidArchitectureStudy/.idea/jarRepositories.xml
  class14/juan-rybczinski/GoogryAndroidArchitectureStudy/.idea/misc.xml
  class14/juan-rybczinski/GoogryAndroidArchitectureStudy/.idea/vcs.xml
  class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/.gitignore
  class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/build.gradle
  class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/proguard-rules.pro
  class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/androidTest/java/com/example/googryandroidarchitecturestudy/ExampleInstrumentedTest.kt
  class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/AndroidManifest.xml
  class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/java/com/example/googryandroidarchitecturestudy/MainActivity.kt
  class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/res/drawable/ic_launcher_background.xml
  class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/res/layout/activity_main.xml
  class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/res/mipmap-hdpi/ic_launcher.png
  class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/res/mipmap-mdpi/ic_launcher.png
  class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/res/values-night/themes.xml
  class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/res/values/colors.xml
  class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/res/values/strings.xml
  class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/main/res/values/themes.xml
  class14/juan-rybczinski/GoogryAndroidArchitectureStudy/app/src/test/java/com/example/googryandroidarchitecturestudy/ExampleUnitTest.kt
  class14/juan-rybczinski/GoogryAndroidArchitectureStudy/build.gradle
  class14/juan-rybczinski/GoogryAndroidArchitectureStudy/gradle.properties
  class14/juan-rybczinski/GoogryAndroidArchitectureStudy/gradle/wrapper/gradle-wrapper.jar
  class14/juan-rybczinski/GoogryAndroidArchitectureStudy/gradle/wrapper/gradle-wrapper.properties
  class14/juan-rybczinski/GoogryAndroidArchitectureStudy/gradlew
  class14/juan-rybczinski/GoogryAndroidArchitectureStudy/gradlew.bat
  class14/juan-rybczinski/GoogryAndroidArchitectureStudy/settings.gradle
Labels: Mentor Needed, Merge Needed

#860 Class14/hunihun
  class14/hunihun/.gitignore
  class14/hunihun/.idea/codeStyles/Project.xml
  class14/hunihun/.idea/codeStyles/codeStyleConfig.xml
  class14/hunihun/.idea/runConfigurations.xml
  class14/hunihun/app/.gitignore
  class14/hunihun/app/build.gradle
  class14/hunihun/app/proguard-rules.pro
  class14/hunihun/app/src/androidTest/java/com/wybh/androidarchitecturestudy/ExampleInstrumentedTest.kt
  class14/hunihun/app/src/main/AndroidManifest.xml
  class14/hunihun/app/src/main/java/com/wybh/androidarchitecturestudy/MainActivity.kt
  class14/hunihun/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  class14/hunihun/app/src/main/res/drawable/ic_launcher_background.xml
  class14/hunihun/app/src/main/res/layout/activity_main.xml
  class14/hunihun/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  class14/hunihun/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  class14/hunihun/app/src/main/res/mipmap-hdpi/ic_launcher.png
  class14/hunihun/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  class14/hunihun/app/src/main/res/mipmap-mdpi/ic_launcher.png
  class14/hunihun/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  class14/hunihun/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  class14/hunihun/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  class14/hunihun/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  class14/hunihun/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  class14/hunihun/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  class14/hunihun/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  class14/hunihun/app/src/main/res/values/colors.xml
  class14/hunihun/app/src/main/res/values/strings.xml
  class14/hunihun/app/src/main/res/values/styles.xml
  class14/hunihun/app/src/test/java/com/wybh/androidarchitecturestudy/ExampleUnitTest.kt
  class14/hunihun/build.gradle
  class14/hunihun/gradle.properties
  class14/hunihun/gradle/wrapper/gradle-wrapper.jar
  class14/hunihun/gradle/wrapper/gradle-wrapper.properties
  class14/hunihun/gradlew
  class14/hunihun/gradlew.bat
  class14/hunihun/settings.gradle
Labels: Mentor Needed, Merge Needed

#861 HW-2 androidx 기반의 프로젝트 생성 + gitgnore 추가
  class14/myung777/StudyFork/.gitignore
  class14/myung777/StudyFork/.idea/codeStyles/Project.xml
  class14/myung777/StudyFork/.idea/codeStyles/codeStyleConfig.xml
  class14/myung777/StudyFork/.idea/runConfigurations.xml
  class14/myung777/StudyFork/app/.gitignore
  class14/myung777/StudyFork/app/build.gradle
  class14/myung777/StudyFork/app/proguard-rules.pro
  class14/myung777/StudyFork/app/src/androidTest/java/com/deepco/studyfork/ExampleInstrumentedTest.kt
  class14/myung777/StudyFork/app/src/main/AndroidManifest.xml
  class14/myung777/StudyFork/app/src/main/java/com/deepco/studyfork/MainActivity.kt
  class14/myung777/StudyFork/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  class14/myung777/StudyFork/app/src/main/res/drawable/ic_launcher_background.xml
  class14/myung777/StudyFork/app/src/main/res/layout/activity_main.xml
  class14/myung777/StudyFork/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  class14/myung777/StudyFork/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  class14/myung777/StudyFork/app/src/main/res/mipmap-hdpi/ic_launcher.png
  class14/myung777/StudyFork/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  class14/myung777/StudyFork/app/src/main/res/mipmap-mdpi/ic_launcher.png
  class14/myung777/StudyFork/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  class14/myung777/StudyFork/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  class14/myung777/StudyFork/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  class14/myung777/StudyFork/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  class14/myung777/StudyFork/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  class14/myung777/StudyFork/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  class14/myung777/StudyFork/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  class14/myung777/StudyFork/app/src/main/res/values/colors.xml
  class14/myung777/StudyFork/app/src/main/res/values/strings.xml
  class14/myung777/StudyFork/app/src/main/res/values/styles.xml
  class14/myung777/StudyFork/app/src/test/java/com/deepco/studyfork/ExampleUnitTest.kt
  class14/myung777/StudyFork/build.gradle
  class14/myung777/StudyFork/gradle.properties
  class14/myung777/StudyFork/gradle/wrapper/gradle-wrapper.jar
  class14/myung777/StudyFork/gradle/wrapper/gradle-wrapper.properties
  class14/myung777/StudyFork/gradlew
  class14/myung777/StudyFork/gradlew.bat
  class14/myung777/StudyFork/settings.gradle
Labels: Mentor Needed, Merge Needed

#855 HW-2 androidx 기반의 프로젝트 생성 + gitgnore 추가
  class15/realizer12/AndroidArchitectureStudy/.gitignore
  class15/realizer12/AndroidArchitectureStudy/.idea/codeStyles/Project.xml
  class15/realizer12/AndroidArchitectureStudy/.idea/codeStyles/codeStyleConfig.xml
  class15/realizer12/AndroidArchitectureStudy/.idea/runConfigurations.xml
  class15/realizer12/AndroidArchitectureStudy/app/.gitignore
  class15/realizer12/AndroidArchitectureStudy/app/build.gradle
  class15/realizer12/AndroidArchitectureStudy/app/proguard-rules.pro
  class15/realizer12/AndroidArchitectureStudy/app/src/androidTest/java/com/example/androidarchitecturestudy/ExampleInstrumentedTest.kt
  class15/realizer12/AndroidArchitectureStudy/app/src/main/AndroidManifest.xml
  class15/realizer12/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/MainActivity.kt
  class15/realizer12/AndroidArchitectureStudy/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  class15/realizer12/AndroidArchitectureStudy/app/src/main/res/drawable/ic_launcher_background.xml
  class15/realizer12/AndroidArchitectureStudy/app/src/main/res/layout/activity_main.xml
  class15/realizer12/AndroidArchitectureStudy/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  class15/realizer12/AndroidArchitectureStudy/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  class15/realizer12/AndroidArchitectureStudy/app/src/main/res/mipmap-hdpi/ic_launcher.png
  class15/realizer12/AndroidArchitectureStudy/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  class15/realizer12/AndroidArchitectureStudy/app/src/main/res/mipmap-mdpi/ic_launcher.png
  class15/realizer12/AndroidArchitectureStudy/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  class15/realizer12/AndroidArchitectureStudy/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  class15/realizer12/AndroidArchitectureStudy/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  class15/realizer12/AndroidArchitectureStudy/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  class15/realizer12/AndroidArchitectureStudy/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  class15/realizer12/AndroidArchitectureStudy/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  class15/realizer12/AndroidArchitectureStudy/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  class15/realizer12/AndroidArchitectureStudy/app/src/main/res/values/colors.xml
  class15/realizer12/AndroidArchitectureStudy/app/src/main/res/values/strings.xml
  class15/realizer12/AndroidArchitectureStudy/app/src/main/res/values/styles.xml
  class15/realizer12/AndroidArchitectureStudy/app/src/test/java/com/example/androidarchitecturestudy/ExampleUnitTest.kt
  class15/realizer12/AndroidArchitectureStudy/build.gradle
  class15/realizer12/AndroidArchitectureStudy/gradle.properties
  class15/realizer12/AndroidArchitectureStudy/gradle/wrapper/gradle-wrapper.jar
  class15/realizer12/AndroidArchitectureStudy/gradle/wrapper/gradle-wrapper.properties
  class15/realizer12/AndroidArchitectureStudy/gradlew
  class15/realizer12/AndroidArchitectureStudy/gradlew.bat
  class15/realizer12/AndroidArchitectureStudy/settings.gradle
Labels: Mentor Needed, Merge Needed

#863 HW2 - create android project
  class14/dev-donghwan/studyfork/.gitignore
  class14/dev-donghwan/studyfork/.idea/codeStyles/Project.xml
  class14/dev-donghwan/studyfork/.idea/codeStyles/codeStyleConfig.xml
  class14/dev-donghwan/studyfork/.idea/runConfigurations.xml
  class14/dev-donghwan/studyfork/app/.gitignore
  class14/dev-donghwan/studyfork/app/build.gradle
  class14/dev-donghwan/studyfork/app/proguard-rules.pro
  class14/dev-donghwan/studyfork/app/src/androidTest/java/com/example/studyfork/ExampleInstrumentedTest.kt
  class14/dev-donghwan/studyfork/app/src/main/AndroidManifest.xml
  class14/dev-donghwan/studyfork/app/src/main/java/com/example/studyfork/MainActivity.kt
  class14/dev-donghwan/studyfork/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  class14/dev-donghwan/studyfork/app/src/main/res/drawable/ic_launcher_background.xml
  class14/dev-donghwan/studyfork/app/src/main/res/layout/activity_main.xml
  class14/dev-donghwan/studyfork/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  class14/dev-donghwan/studyfork/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  class14/dev-donghwan/studyfork/app/src/main/res/mipmap-hdpi/ic_launcher.png
  class14/dev-donghwan/studyfork/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  class14/dev-donghwan/studyfork/app/src/main/res/mipmap-mdpi/ic_launcher.png
  class14/dev-donghwan/studyfork/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  class14/dev-donghwan/studyfork/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  class14/dev-donghwan/studyfork/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  class14/dev-donghwan/studyfork/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  class14/dev-donghwan/studyfork/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  class14/dev-donghwan/studyfork/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  class14/dev-donghwan/studyfork/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  class14/dev-donghwan/studyfork/app/src/main/res/values/colors.xml
  class14/dev-donghwan/studyfork/app/src/main/res/values/strings.xml
  class14/dev-donghwan/studyfork/app/src/main/res/values/styles.xml
  class14/dev-donghwan/studyfork/app/src/test/java/com/example/studyfork/ExampleUnitTest.kt
  class14/dev-donghwan/studyfork/build.gradle
  class14/dev-donghwan/studyfork/gradle.properties
  class14/dev-donghwan/studyfork/gradle/wrapper/gradle-wrapper.jar
  class14/dev-donghwan/studyfork/gradle/wrapper/gradle-wrapper.properties
  class14/dev-donghwan/studyfork/gradlew
  class14/dev-donghwan/studyfork/gradlew.bat
  class14/dev-donghwan/studyfork/settings.gradle
Labels: Mentor Needed, Merge Needed

#866 HW-2 androidx 기반의 프로젝트 생성 + gitignore 추가
  .DS_Store
  class15/.DS_Store
  class15/hhi-5258/.DS_Store
  class15/hhi-5258/HHiApplication/.gitignore
  class15/hhi-5258/HHiApplication/.idea/codeStyles/Project.xml
  class15/hhi-5258/HHiApplication/.idea/codeStyles/codeStyleConfig.xml
  class15/hhi-5258/HHiApplication/.idea/runConfigurations.xml
  class15/hhi-5258/HHiApplication/app/.gitignore
  class15/hhi-5258/HHiApplication/app/build.gradle
  class15/hhi-5258/HHiApplication/app/proguard-rules.pro
  class15/hhi-5258/HHiApplication/app/src/androidTest/java/com/hhi/myapplication/ExampleInstrumentedTest.kt
  class15/hhi-5258/HHiApplication/app/src/main/AndroidManifest.xml
  class15/hhi-5258/HHiApplication/app/src/main/java/com/hhi/myapplication/MainActivity.kt
  class15/hhi-5258/HHiApplication/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  class15/hhi-5258/HHiApplication/app/src/main/res/drawable/ic_launcher_background.xml
  class15/hhi-5258/HHiApplication/app/src/main/res/layout/activity_main.xml
  class15/hhi-5258/HHiApplication/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  class15/hhi-5258/HHiApplication/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  class15/hhi-5258/HHiApplication/app/src/main/res/mipmap-hdpi/ic_launcher.png
  class15/hhi-5258/HHiApplication/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  class15/hhi-5258/HHiApplication/app/src/main/res/mipmap-mdpi/ic_launcher.png
  class15/hhi-5258/HHiApplication/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  class15/hhi-5258/HHiApplication/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  class15/hhi-5258/HHiApplication/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  class15/hhi-5258/HHiApplication/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  class15/hhi-5258/HHiApplication/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  class15/hhi-5258/HHiApplication/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  class15/hhi-5258/HHiApplication/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  class15/hhi-5258/HHiApplication/app/src/main/res/values/colors.xml
  class15/hhi-5258/HHiApplication/app/src/main/res/values/strings.xml
  class15/hhi-5258/HHiApplication/app/src/main/res/values/styles.xml
  class15/hhi-5258/HHiApplication/app/src/test/java/com/hhi/myapplication/ExampleUnitTest.kt
  class15/hhi-5258/HHiApplication/build.gradle
  class15/hhi-5258/HHiApplication/gradle.properties
  class15/hhi-5258/HHiApplication/gradle/wrapper/gradle-wrapper.jar
  class15/hhi-5258/HHiApplication/gradle/wrapper/gradle-wrapper.properties
  class15/hhi-5258/HHiApplication/gradlew
  class15/hhi-5258/HHiApplication/gradlew.bat
  class15/hhi-5258/HHiApplication/settings.gradle
Labels: Mentor Needed, Merge Needed

#864 HW2-프로젝트 추가
  class14/onxmoreplz/HW2_Project/.gitignore
  class14/onxmoreplz/HW2_Project/.idea/.gitignore
  class14/onxmoreplz/HW2_Project/.idea/compiler.xml
  class14/onxmoreplz/HW2_Project/.idea/gradle.xml
  class14/onxmoreplz/HW2_Project/.idea/jarRepositories.xml
  class14/onxmoreplz/HW2_Project/.idea/misc.xml
  class14/onxmoreplz/HW2_Project/.idea/vcs.xml
  class14/onxmoreplz/HW2_Project/app/.gitignore
  class14/onxmoreplz/HW2_Project/app/build.gradle
  class14/onxmoreplz/HW2_Project/app/proguard-rules.pro
  class14/onxmoreplz/HW2_Project/app/src/androidTest/java/com/example/hw2_project/ExampleInstrumentedTest.kt
  class14/onxmoreplz/HW2_Project/app/src/main/AndroidManifest.xml
  class14/onxmoreplz/HW2_Project/app/src/main/java/com/example/hw2_project/MainActivity.kt
  class14/onxmoreplz/HW2_Project/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  class14/onxmoreplz/HW2_Project/app/src/main/res/drawable/ic_launcher_background.xml
  class14/onxmoreplz/HW2_Project/app/src/main/res/layout/activity_main.xml
  class14/onxmoreplz/HW2_Project/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  class14/onxmoreplz/HW2_Project/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  class14/onxmoreplz/HW2_Project/app/src/main/res/mipmap-hdpi/ic_launcher.png
  class14/onxmoreplz/HW2_Project/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  class14/onxmoreplz/HW2_Project/app/src/main/res/mipmap-mdpi/ic_launcher.png
  class14/onxmoreplz/HW2_Project/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  class14/onxmoreplz/HW2_Project/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  class14/onxmoreplz/HW2_Project/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  class14/onxmoreplz/HW2_Project/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  class14/onxmoreplz/HW2_Project/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  class14/onxmoreplz/HW2_Project/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  class14/onxmoreplz/HW2_Project/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  class14/onxmoreplz/HW2_Project/app/src/main/res/values-night/themes.xml
  class14/onxmoreplz/HW2_Project/app/src/main/res/values/colors.xml
  class14/onxmoreplz/HW2_Project/app/src/main/res/values/strings.xml
  class14/onxmoreplz/HW2_Project/app/src/main/res/values/themes.xml
  class14/onxmoreplz/HW2_Project/app/src/test/java/com/example/hw2_project/ExampleUnitTest.kt
  class14/onxmoreplz/HW2_Project/build.gradle
  class14/onxmoreplz/HW2_Project/gradle.properties
  class14/onxmoreplz/HW2_Project/gradle/wrapper/gradle-wrapper.jar
  class14/onxmoreplz/HW2_Project/gradle/wrapper/gradle-wrapper.properties
  class14/onxmoreplz/HW2_Project/gradlew
  class14/onxmoreplz/HW2_Project/gradlew.bat
  class14/onxmoreplz/HW2_Project/settings.gradle
Labels: Mentor Needed, Merge Needed

#862 androidx 기반의 프로젝트 생성 + gitgnore 추가
  class14/simuelunbo/AndroidArchitectureStudy/.gitignore
  class14/simuelunbo/AndroidArchitectureStudy/.idea/codeStyles/Project.xml
  class14/simuelunbo/AndroidArchitectureStudy/.idea/codeStyles/codeStyleConfig.xml
  class14/simuelunbo/AndroidArchitectureStudy/.idea/gradle.xml
  class14/simuelunbo/AndroidArchitectureStudy/.idea/jarRepositories.xml
  class14/simuelunbo/AndroidArchitectureStudy/.idea/misc.xml
  class14/simuelunbo/AndroidArchitectureStudy/.idea/runConfigurations.xml
  class14/simuelunbo/AndroidArchitectureStudy/.idea/vcs.xml
  class14/simuelunbo/AndroidArchitectureStudy/app/.gitignore
  class14/simuelunbo/AndroidArchitectureStudy/app/build.gradle
  class14/simuelunbo/AndroidArchitectureStudy/app/proguard-rules.pro
  class14/simuelunbo/AndroidArchitectureStudy/app/src/androidTest/java/com/example/androidarchitecturestudy/ExampleInstrumentedTest.kt
  class14/simuelunbo/AndroidArchitectureStudy/app/src/main/AndroidManifest.xml
  class14/simuelunbo/AndroidArchitectureStudy/app/src/main/java/com/example/androidarchitecturestudy/MainActivity.kt
  class14/simuelunbo/AndroidArchitectureStudy/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  class14/simuelunbo/AndroidArchitectureStudy/app/src/main/res/drawable/ic_launcher_background.xml
  class14/simuelunbo/AndroidArchitectureStudy/app/src/main/res/layout/activity_main.xml
  class14/simuelunbo/AndroidArchitectureStudy/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  class14/simuelunbo/AndroidArchitectureStudy/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  class14/simuelunbo/AndroidArchitectureStudy/app/src/main/res/mipmap-hdpi/ic_launcher.png
  class14/simuelunbo/AndroidArchitectureStudy/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  class14/simuelunbo/AndroidArchitectureStudy/app/src/main/res/mipmap-mdpi/ic_launcher.png
  class14/simuelunbo/AndroidArchitectureStudy/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  class14/simuelunbo/AndroidArchitectureStudy/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  class14/simuelunbo/AndroidArchitectureStudy/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  class14/simuelunbo/AndroidArchitectureStudy/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  class14/simuelunbo/AndroidArchitectureStudy/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  class14/simuelunbo/AndroidArchitectureStudy/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  class14/simuelunbo/AndroidArchitectureStudy/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  class14/simuelunbo/AndroidArchitectureStudy/app/src/main/res/values/colors.xml
  class14/simuelunbo/AndroidArchitectureStudy/app/src/main/res/values/strings.xml
  class14/simuelunbo/AndroidArchitectureStudy/app/src/main/res/values/styles.xml
  class14/simuelunbo/AndroidArchitectureStudy/app/src/test/java/com/example/androidarchitecturestudy/ExampleUnitTest.kt
  class14/simuelunbo/AndroidArchitectureStudy/build.gradle
  class14/simuelunbo/AndroidArchitectureStudy/gradle.properties
  class14/simuelunbo/AndroidArchitectureStudy/gradle/wrapper/gradle-wrapper.jar
  class14/simuelunbo/AndroidArchitectureStudy/gradle/wrapper/gradle-wrapper.properties
  class14/simuelunbo/AndroidArchitectureStudy/gradlew
  class14/simuelunbo/AndroidArchitectureStudy/gradlew.bat
  class14/simuelunbo/AndroidArchitectureStudy/settings.gradle
Labels: Mentor Needed, Merge Needed

#867 HW-2 androidx기반 프로젝트 생성
  class15/jihoi-kang/aas/.gitignore
  class15/jihoi-kang/aas/.idea/codeStyles/Project.xml
  class15/jihoi-kang/aas/.idea/runConfigurations.xml
  class15/jihoi-kang/aas/app/.gitignore
  class15/jihoi-kang/aas/app/build.gradle
  class15/jihoi-kang/aas/app/proguard-rules.pro
  class15/jihoi-kang/aas/app/src/androidTest/java/com/jay/aas/ExampleInstrumentedTest.kt
  class15/jihoi-kang/aas/app/src/main/AndroidManifest.xml
  class15/jihoi-kang/aas/app/src/main/java/com/jay/aas/MainActivity.kt
  class15/jihoi-kang/aas/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  class15/jihoi-kang/aas/app/src/main/res/drawable/ic_launcher_background.xml
  class15/jihoi-kang/aas/app/src/main/res/layout/activity_main.xml
  class15/jihoi-kang/aas/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  class15/jihoi-kang/aas/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  class15/jihoi-kang/aas/app/src/main/res/mipmap-hdpi/ic_launcher.png
  class15/jihoi-kang/aas/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  class15/jihoi-kang/aas/app/src/main/res/mipmap-mdpi/ic_launcher.png
  class15/jihoi-kang/aas/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  class15/jihoi-kang/aas/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  class15/jihoi-kang/aas/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  class15/jihoi-kang/aas/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  class15/jihoi-kang/aas/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  class15/jihoi-kang/aas/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  class15/jihoi-kang/aas/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  class15/jihoi-kang/aas/app/src/main/res/values/colors.xml
  class15/jihoi-kang/aas/app/src/main/res/values/strings.xml
  class15/jihoi-kang/aas/app/src/main/res/values/styles.xml
  class15/jihoi-kang/aas/app/src/test/java/com/jay/aas/ExampleUnitTest.kt
  class15/jihoi-kang/aas/build.gradle
  class15/jihoi-kang/aas/gradle.properties
  class15/jihoi-kang/aas/gradle/wrapper/gradle-wrapper.jar
  class15/jihoi-kang/aas/gradle/wrapper/gradle-wrapper.properties
  class15/jihoi-kang/aas/gradlew
  class15/jihoi-kang/aas/gradlew.bat
  class15/jihoi-kang/aas/settings.gradle
Labels: Mentor Needed, Merge Needed

#858 HW-2 androidx 기반의 프로젝트 생성 + gitgnore 추가
  class15/dktsudgg/AndroidArchitectureStudy/.gitignore
  class15/dktsudgg/AndroidArchitectureStudy/.idea/codeStyles/Project.xml
  class15/dktsudgg/AndroidArchitectureStudy/.idea/codeStyles/codeStyleConfig.xml
  class15/dktsudgg/AndroidArchitectureStudy/.idea/jarRepositories.xml
  class15/dktsudgg/AndroidArchitectureStudy/.idea/misc.xml
  class15/dktsudgg/AndroidArchitectureStudy/.idea/runConfigurations.xml
  class15/dktsudgg/AndroidArchitectureStudy/app/.gitignore
  class15/dktsudgg/AndroidArchitectureStudy/app/build.gradle
  class15/dktsudgg/AndroidArchitectureStudy/app/proguard-rules.pro
  class15/dktsudgg/AndroidArchitectureStudy/app/src/androidTest/java/kr/dktsudgg/androidarchitecturestudy/ExampleInstrumentedTest.kt
  class15/dktsudgg/AndroidArchitectureStudy/app/src/main/AndroidManifest.xml
  class15/dktsudgg/AndroidArchitectureStudy/app/src/main/java/kr/dktsudgg/androidarchitecturestudy/MainActivity.kt
  class15/dktsudgg/AndroidArchitectureStudy/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  class15/dktsudgg/AndroidArchitectureStudy/app/src/main/res/drawable/ic_launcher_background.xml
  class15/dktsudgg/AndroidArchitectureStudy/app/src/main/res/layout/activity_main.xml
  class15/dktsudgg/AndroidArchitectureStudy/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  class15/dktsudgg/AndroidArchitectureStudy/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  class15/dktsudgg/AndroidArchitectureStudy/app/src/main/res/mipmap-hdpi/ic_launcher.png
  class15/dktsudgg/AndroidArchitectureStudy/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  class15/dktsudgg/AndroidArchitectureStudy/app/src/main/res/mipmap-mdpi/ic_launcher.png
  class15/dktsudgg/AndroidArchitectureStudy/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  class15/dktsudgg/AndroidArchitectureStudy/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  class15/dktsudgg/AndroidArchitectureStudy/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  class15/dktsudgg/AndroidArchitectureStudy/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  class15/dktsudgg/AndroidArchitectureStudy/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  class15/dktsudgg/AndroidArchitectureStudy/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  class15/dktsudgg/AndroidArchitectureStudy/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  class15/dktsudgg/AndroidArchitectureStudy/app/src/main/res/values/colors.xml
  class15/dktsudgg/AndroidArchitectureStudy/app/src/main/res/values/strings.xml
  class15/dktsudgg/AndroidArchitectureStudy/app/src/main/res/values/styles.xml
  class15/dktsudgg/AndroidArchitectureStudy/app/src/test/java/kr/dktsudgg/androidarchitecturestudy/ExampleUnitTest.kt
  class15/dktsudgg/AndroidArchitectureStudy/build.gradle
  class15/dktsudgg/AndroidArchitectureStudy/gradle.properties
  class15/dktsudgg/AndroidArchitectureStudy/gradle/wrapper/gradle-wrapper.jar
  class15/dktsudgg/AndroidArchitectureStudy/gradle/wrapper/gradle-wrapper.properties
  class15/dktsudgg/AndroidArchitectureStudy/gradlew
  class15/dktsudgg/AndroidArchitectureStudy/gradlew.bat
  class15/dktsudgg/AndroidArchitectureStudy/settings.gradle
Labels: Mentor Needed, Merge Needed

#868 HW-2 : Create new project
  class15/showmiso/ArchitectureStudy/.gitignore
  class15/showmiso/ArchitectureStudy/.idea/codeStyles/Project.xml
  class15/showmiso/ArchitectureStudy/.idea/codeStyles/codeStyleConfig.xml
  class15/showmiso/ArchitectureStudy/.idea/gradle.xml
  class15/showmiso/ArchitectureStudy/.idea/jarRepositories.xml
  class15/showmiso/ArchitectureStudy/.idea/misc.xml
  class15/showmiso/ArchitectureStudy/.idea/runConfigurations.xml
  class15/showmiso/ArchitectureStudy/.idea/vcs.xml
  class15/showmiso/ArchitectureStudy/app/.gitignore
  class15/showmiso/ArchitectureStudy/app/build.gradle
  class15/showmiso/ArchitectureStudy/app/proguard-rules.pro
  class15/showmiso/ArchitectureStudy/app/src/androidTest/java/com/showmiso/architecturestudy/ExampleInstrumentedTest.kt
  class15/showmiso/ArchitectureStudy/app/src/main/AndroidManifest.xml
  class15/showmiso/ArchitectureStudy/app/src/main/java/com/showmiso/architecturestudy/MainActivity.kt
  class15/showmiso/ArchitectureStudy/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  class15/showmiso/ArchitectureStudy/app/src/main/res/drawable/ic_launcher_background.xml
  class15/showmiso/ArchitectureStudy/app/src/main/res/layout/activity_main.xml
  class15/showmiso/ArchitectureStudy/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  class15/showmiso/ArchitectureStudy/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  class15/showmiso/ArchitectureStudy/app/src/main/res/mipmap-hdpi/ic_launcher.png
  class15/showmiso/ArchitectureStudy/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  class15/showmiso/ArchitectureStudy/app/src/main/res/mipmap-mdpi/ic_launcher.png
  class15/showmiso/ArchitectureStudy/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  class15/showmiso/ArchitectureStudy/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  class15/showmiso/ArchitectureStudy/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  class15/showmiso/ArchitectureStudy/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  class15/showmiso/ArchitectureStudy/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  class15/showmiso/ArchitectureStudy/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  class15/showmiso/ArchitectureStudy/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  class15/showmiso/ArchitectureStudy/app/src/main/res/values/colors.xml
  class15/showmiso/ArchitectureStudy/app/src/main/res/values/strings.xml
  class15/showmiso/ArchitectureStudy/app/src/main/res/values/styles.xml
  class15/showmiso/ArchitectureStudy/app/src/test/java/com/showmiso/architecturestudy/ExampleUnitTest.kt
  class15/showmiso/ArchitectureStudy/build.gradle
  class15/showmiso/ArchitectureStudy/gradle.properties
  class15/showmiso/ArchitectureStudy/gradle/wrapper/gradle-wrapper.jar
  class15/showmiso/ArchitectureStudy/gradle/wrapper/gradle-wrapper.properties
  class15/showmiso/ArchitectureStudy/gradlew
  class15/showmiso/ArchitectureStudy/gradlew.bat
  class15/showmiso/ArchitectureStudy/settings.gradle
Labels: Answer Needed, Mentor Needed

#869 HW-7 Hilt
  class13/Sangmeebee/MyProject/app/build.gradle
  class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/data/repository/NaverRepositoryImpl.kt
  class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/data/service/RetrofitClient.kt
  class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/data/sharedPreferences/App.kt
  class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/data/source/local/NaverLocalDataSourceImpl.kt
  class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/data/source/remote/NaverRemoteDataSourceImpl.kt
  class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/ui/MainActivity.kt
  class13/Sangmeebee/MyProject/app/src/main/java/com/example/myproject/viewmodel/MainViewModel.kt
  class13/Sangmeebee/MyProject/build.gradle
Labels: Mentor Needed, Merge Needed
