Repository StudyFork/GoogryAndroidArchitectureStudy, pull requests merged in 2020-03, with the labels that each got.

#504 Create androidx project including gitignore
  2003/tjdwlsl1021/.gitignore
  2003/tjdwlsl1021/app/.gitignore
  2003/tjdwlsl1021/app/build.gradle
  2003/tjdwlsl1021/app/proguard-rules.pro
  2003/tjdwlsl1021/app/src/androidTest/java/com/example/myapplication/ExampleInstrumentedTest.kt
  2003/tjdwlsl1021/app/src/main/AndroidManifest.xml
  2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/MainActivity.kt
  2003/tjdwlsl1021/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  2003/tjdwlsl1021/app/src/main/res/drawable/ic_launcher_background.xml
  2003/tjdwlsl1021/app/src/main/res/layout/activity_main.xml
  2003/tjdwlsl1021/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  2003/tjdwlsl1021/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  2003/tjdwlsl1021/app/src/main/res/mipmap-hdpi/ic_launcher.png
  2003/tjdwlsl1021/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  2003/tjdwlsl1021/app/src/main/res/mipmap-mdpi/ic_launcher.png
  2003/tjdwlsl1021/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  2003/tjdwlsl1021/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  2003/tjdwlsl1021/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  2003/tjdwlsl1021/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  2003/tjdwlsl1021/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  2003/tjdwlsl1021/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  2003/tjdwlsl1021/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  2003/tjdwlsl1021/app/src/main/res/values/colors.xml
  2003/tjdwlsl1021/app/src/main/res/values/strings.xml
  2003/tjdwlsl1021/app/src/main/res/values/styles.xml
  2003/tjdwlsl1021/app/src/test/java/com/example/myapplication/ExampleUnitTest.kt
  2003/tjdwlsl1021/build.gradle
  2003/tjdwlsl1021/gradle.properties
  2003/tjdwlsl1021/gradle/wrapper/gradle-wrapper.jar
  2003/tjdwlsl1021/gradle/wrapper/gradle-wrapper.properties
  2003/tjdwlsl1021/gradlew
  2003/tjdwlsl1021/gradlew.bat
  2003/tjdwlsl1021/settings.gradle
Labels: Mentor Needed, Merge Needed

#507 HW-1 NaverMovie Sample
  2003/sooakim/.idea/codeStyles/Project.xml
  2003/sooakim/app/build.gradle
  2003/sooakim/app/src/main/AndroidManifest.xml
  2003/sooakim/app/src/main/java/io/github/sooakim/MainActivity.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/network/SANetworkService.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/network/api/SANaverMovieApi.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/network/interceptor/SAInterceptor.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/network/interceptor/SANaverAuthInterceptor.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/network/model/SAModel.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/network/model/SAMovieModel.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/network/model/response/SANaverSearchResponse.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/network/model/response/SAResponse.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/SAMainActivity.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/SAMainSearchResultAdapter.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/base/SAIdentifiable.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/base/SARecyclerViewAdapter.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/base/SAViewHolder.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/base/SAViewHolderLifecycle.kt
  2003/sooakim/app/src/main/res/drawable/bg_placeholder_movie.xml
  2003/sooakim/app/src/main/res/drawable/bg_underline.xml
  2003/sooakim/app/src/main/res/layout/activity_main.xml
  2003/sooakim/app/src/main/res/layout/item_main_search_result.xml
  2003/sooakim/app/src/main/res/values/colors.xml
  2003/sooakim/app/src/main/res/values/strings.xml
  2003/sooakim/app/src/main/res/values/styles.xml
Labels: Mentor Needed, Merge Needed

#490 HW-8 multi module 적용
  AhnHyeonho/FirstProject/.idea/gradle.xml
  AhnHyeonho/FirstProject/app/build.gradle
  AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/di/MainApplication.kt
  AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/di/RepositoryModule.kt
  AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/ui/main/MainActivity.kt
  AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/ui/main/MainViewModel.kt
  AhnHyeonho/FirstProject/app/src/main/java/com/hansung/firstproject/ui/main/MainViewModelFactory.kt
  AhnHyeonho/FirstProject/build.gradle
  AhnHyeonho/FirstProject/remote/.gitignore
  AhnHyeonho/FirstProject/remote/build.gradle
  AhnHyeonho/FirstProject/remote/consumer-rules.pro
  AhnHyeonho/FirstProject/remote/proguard-rules.pro
  AhnHyeonho/FirstProject/remote/src/androidTest/java/com/hansung/remote/ExampleInstrumentedTest.kt
  AhnHyeonho/FirstProject/remote/src/main/AndroidManifest.xml
  AhnHyeonho/FirstProject/remote/src/main/java/com/hansung/remote/NaverRemoteDataSource.kt
  AhnHyeonho/FirstProject/remote/src/main/java/com/hansung/remote/NaverRemoteDataSourceImpl.kt
  AhnHyeonho/FirstProject/remote/src/main/java/com/hansung/remote/api/NaverApiService.kt
  AhnHyeonho/FirstProject/remote/src/main/java/com/hansung/remote/api/NaverApiServiceImpl.kt
  AhnHyeonho/FirstProject/remote/src/main/java/com/hansung/remote/data/ErrorStringResource.kt
  AhnHyeonho/FirstProject/remote/src/main/java/com/hansung/remote/data/MovieModel.kt
  AhnHyeonho/FirstProject/remote/src/main/java/com/hansung/remote/data/MovieResponseModel.kt
  AhnHyeonho/FirstProject/remote/src/main/java/com/hansung/remote/di/DataSourceModule.kt
  AhnHyeonho/FirstProject/remote/src/main/res/values/client_infos.xml
  AhnHyeonho/FirstProject/remote/src/main/res/values/errors.xml
  AhnHyeonho/FirstProject/remote/src/main/res/values/strings.xml
  AhnHyeonho/FirstProject/remote/src/test/java/com/hansung/remote/ExampleUnitTest.kt
  AhnHyeonho/FirstProject/repository/.gitignore
  AhnHyeonho/FirstProject/repository/build.gradle
  AhnHyeonho/FirstProject/repository/consumer-rules.pro
  AhnHyeonho/FirstProject/repository/proguard-rules.pro
  AhnHyeonho/FirstProject/repository/src/androidTest/java/com/hansung/repository/ExampleInstrumentedTest.kt
  AhnHyeonho/FirstProject/repository/src/main/AndroidManifest.xml
  AhnHyeonho/FirstProject/repository/src/main/java/com/hansung/repository/NaverRepository.kt
  AhnHyeonho/FirstProject/repository/src/main/java/com/hansung/repository/NaverRepositoryImpl.kt
  AhnHyeonho/FirstProject/repository/src/main/java/com/hansung/repository/di/RepositoryModule.kt
  AhnHyeonho/FirstProject/repository/src/main/res/values/strings.xml
  AhnHyeonho/FirstProject/repository/src/test/java/com/hansung/repository/ExampleUnitTest.kt
  AhnHyeonho/FirstProject/settings.gradle
Labels: Mentor Needed, Merge Needed

#510 HW-1 네이버 영화 검색 앱
  2003/mtjin/AndroidArchitectureStudy/app/build.gradle
  2003/mtjin/AndroidArchitectureStudy/app/src/main/AndroidManifest.xml
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/MainActivity.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/api/ApiClient.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/api/ApiInterface.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/api/AppInterceptor.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/data/Movie.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/data/MovieResponse.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/MainActivity.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/MovieAdapter.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/res/drawable/ic_default.png
  2003/mtjin/AndroidArchitectureStudy/app/src/main/res/layout/activity_main.xml
  2003/mtjin/AndroidArchitectureStudy/app/src/main/res/layout/item_movie.xml
  2003/mtjin/AndroidArchitectureStudy/app/src/main/res/values/colors.xml
  2003/mtjin/AndroidArchitectureStudy/app/src/main/res/values/strings.xml
  2003/mtjin/AndroidArchitectureStudy/app/src/main/res/values/styles.xml
Labels: Mentor Needed, Merge Needed

#459 HW-3 네이버 영화 검색 API 앱 , MVP 패턴 구현
  class08/HudsonPark/ArchtectStudy/app/app.iml
  class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/base/BaseActivity.kt
  class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/base/BasePresenter.kt
  class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/base/BaseView.kt
  class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/data/repository/NaverQueryRepository.kt
  class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/data/repository/NaverQueryRepositoryImpl.kt
  class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/data/source/local/MovieDataDao.kt
  class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/data/source/local/NaverQueryLocalDataSourceImpl.kt
  class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/ui/main/MainActivity.kt
  class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/ui/main/MainContract.kt
  class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/ui/main/MainPresenter.kt
  class08/HudsonPark/ArchtectStudy/app/src/main/res/values/strings.xml
Labels: Mentor Needed, Merge Needed

#516 HW-7 Koin 적용
  class08/slflfl12/Study/.idea/codeStyles/Project.xml
  class08/slflfl12/Study/app/build.gradle
  class08/slflfl12/Study/app/src/main/AndroidManifest.xml
  class08/slflfl12/Study/app/src/main/java/com/example/study/MyApplication.kt
  class08/slflfl12/Study/app/src/main/java/com/example/study/data/repository/NaverSearchRepositoryImpl.kt
  class08/slflfl12/Study/app/src/main/java/com/example/study/data/source/local/NaverSearchLocalDataSourceImpl.kt
  class08/slflfl12/Study/app/src/main/java/com/example/study/data/source/local/SearchResultDatabase.kt
  class08/slflfl12/Study/app/src/main/java/com/example/study/data/source/remote/NaverSearchRemoteDataSource.kt
  class08/slflfl12/Study/app/src/main/java/com/example/study/data/source/remote/NaverSearchRemoteDataSourceImpl.kt
  class08/slflfl12/Study/app/src/main/java/com/example/study/data/source/remote/network/NaverApiClient.kt
  class08/slflfl12/Study/app/src/main/java/com/example/study/data/source/remote/network/interceptor/ApplicationInterceptor.kt
  class08/slflfl12/Study/app/src/main/java/com/example/study/di/localModule.kt
  class08/slflfl12/Study/app/src/main/java/com/example/study/di/remoteModule.kt
  class08/slflfl12/Study/app/src/main/java/com/example/study/di/repositoryModule.kt
  class08/slflfl12/Study/app/src/main/java/com/example/study/di/viewmodelModule.kt
  class08/slflfl12/Study/app/src/main/java/com/example/study/ui/main/MainActivity.kt
  class08/slflfl12/Study/app/src/main/java/com/example/study/ui/main/MainViewModel.kt
  class08/slflfl12/Study/app/src/main/java/com/example/study/util/base/BaseActivity.kt
  class08/slflfl12/Study/app/src/main/res/layout/activity_main.xml
  class08/slflfl12/Study/gradle.properties
Labels: Mentor Needed, Merge Needed

#522 Or/class08/dev lib ch
  class08/devLibCH/Study/app/build.gradle
  class08/devLibCH/Study/app/src/main/java/app/ch/study/core/BaseActivity.kt
  class08/devLibCH/Study/app/src/main/java/app/ch/study/core/BaseViewModel.kt
  class08/devLibCH/Study/app/src/main/java/app/ch/study/ext/ImageViewExt.kt
  class08/devLibCH/Study/app/src/main/java/app/ch/study/ext/TextViewExt.kt
  class08/devLibCH/Study/app/src/main/java/app/ch/study/ext/WebViewExt.kt
  class08/devLibCH/Study/app/src/main/java/app/ch/study/ui/detail/DetailActivity.kt
  class08/devLibCH/Study/app/src/main/java/app/ch/study/ui/main/view/MainActivity.kt
  class08/devLibCH/Study/app/src/main/java/app/ch/study/ui/main/view/MovieAdapter.kt
  class08/devLibCH/Study/app/src/main/java/app/ch/study/ui/main/viewmodel/MainViewModel.kt
  class08/devLibCH/Study/app/src/main/res/layout/activity_detail.xml
  class08/devLibCH/Study/app/src/main/res/layout/list_item_movie.xml
Labels: Mentor Needed

#518 HW-1 Advanced
  2003/sooakim/app/build.gradle
  2003/sooakim/app/src/main/AndroidManifest.xml
  2003/sooakim/app/src/main/java/io/github/sooakim/network/SANetworkService.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/network/SANetworkServiceImpl.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/network/api/SAAuthApi.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/network/api/SAAuthApiImpl.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/network/model/request/SAAuthRequest.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/network/model/request/SARequest.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/pref/SAPreferencesHelper.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/pref/SAPreferencesHelperImpl.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/SASplashActivity.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/application/SAApplication.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/base/SAActivity.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/login/SALoginActivity.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/movie/SAMovieSearchActivity.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/movie/SAMovieSearchResultAdapter.kt
  2003/sooakim/app/src/main/res/drawable/bg_splash.xml
  2003/sooakim/app/src/main/res/layout/activity_login.xml
  2003/sooakim/app/src/main/res/layout/activity_movie_search.xml
  2003/sooakim/app/src/main/res/layout/item_movie_search_result.xml
  2003/sooakim/app/src/main/res/values/strings.xml
  2003/sooakim/app/src/main/res/values/styles.xml
Labels: Mentor Needed, Merge Needed

#521 HW-4 DataBinding 적용하기
  class08/HudsonPark/ArchtectStudy/app/app.iml
  class08/HudsonPark/ArchtectStudy/app/build.gradle
  class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/data/repository/NaverQueryRepositoryImpl.kt
  class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/ext/ImageViewExt.kt
  class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/ext/RatingBarExt.kt
  class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/ext/TextViewExt.kt
  class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/ui/main/MainActivity.kt
  class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/ui/main/MainPresenter.kt
  class08/HudsonPark/ArchtectStudy/app/src/main/java/com/example/archstudy/ui/main/MovieListAdapter.kt
  class08/HudsonPark/ArchtectStudy/app/src/main/res/layout/activity_main.xml
  class08/HudsonPark/ArchtectStudy/app/src/main/res/layout/item_movie.xml
Labels: Mentor Needed, Merge Needed

#520 HW-1(기능추가) 네이버 영화검색 앱
  2003/mtjin/AndroidArchitectureStudy/app/src/main/AndroidManifest.xml
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/LoginActivity.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/MovieSearchActivity.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/SplashActivity.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/utils/PreferenceManager.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/res/drawable-v24/bg_green_gradation.xml
  2003/mtjin/AndroidArchitectureStudy/app/src/main/res/drawable-v24/bg_splash.xml
  2003/mtjin/AndroidArchitectureStudy/app/src/main/res/drawable/ic_app_logo.png
  2003/mtjin/AndroidArchitectureStudy/app/src/main/res/layout/activity_login.xml
  2003/mtjin/AndroidArchitectureStudy/app/src/main/res/layout/activity_movie_search.xml
  2003/mtjin/AndroidArchitectureStudy/app/src/main/res/values/styles.xml
Labels: Mentor Needed, Merge Needed

#509 HW-7 코인 적용
  class08/YKW93/ArchitectureStudy/app/build.gradle
  class08/YKW93/ArchitectureStudy/app/src/main/java/com/studyfork/architecturestudy/base/BaseActivity.kt
  class08/YKW93/ArchitectureStudy/app/src/main/java/com/studyfork/architecturestudy/base/BaseApplication.kt
  class08/YKW93/ArchitectureStudy/app/src/main/java/com/studyfork/architecturestudy/data/repository/MovieRepositoryImpl.kt
  class08/YKW93/ArchitectureStudy/app/src/main/java/com/studyfork/architecturestudy/data/source/remote/MovieRemoteDataSourceImpl.kt
  class08/YKW93/ArchitectureStudy/app/src/main/java/com/studyfork/architecturestudy/di/NetworkModule.kt
  class08/YKW93/ArchitectureStudy/app/src/main/java/com/studyfork/architecturestudy/di/RemoteModule.kt
  class08/YKW93/ArchitectureStudy/app/src/main/java/com/studyfork/architecturestudy/di/RepositoryModule.kt
  class08/YKW93/ArchitectureStudy/app/src/main/java/com/studyfork/architecturestudy/di/UtilModule.kt
  class08/YKW93/ArchitectureStudy/app/src/main/java/com/studyfork/architecturestudy/di/ViewModelModule.kt
  class08/YKW93/ArchitectureStudy/app/src/main/java/com/studyfork/architecturestudy/network/ApiClient.kt
  class08/YKW93/ArchitectureStudy/app/src/main/java/com/studyfork/architecturestudy/ui/main/MainActivity.kt
  class08/YKW93/ArchitectureStudy/app/src/main/java/com/studyfork/architecturestudy/ui/main/MainViewModel.kt
Labels: Mentor Needed, Merge Needed

#515 HW-1 Add project for searching movie info
  2003/kangraemin/app/build.gradle
  2003/kangraemin/app/src/main/AndroidManifest.xml
  2003/kangraemin/app/src/main/java/com/example/kangraemin/LoginActivity.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/MainActivity.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/SplashActivity.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/adapter/SearchResultAdapter.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/base/KangBaseActivity.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/model/MovieSearchInterface.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/response/ResponseMovieSearch.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/util/NetworkUtil.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/util/RetrofitClient.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/util/Utils.kt
  2003/kangraemin/app/src/main/res/drawable/ic_popcorn.xml
  2003/kangraemin/app/src/main/res/layout/activity_login.xml
  2003/kangraemin/app/src/main/res/layout/activity_main.xml
  2003/kangraemin/app/src/main/res/layout/activity_splash.xml
  2003/kangraemin/app/src/main/res/layout/adapter_search_result.xml
  2003/kangraemin/app/src/main/res/values/colors.xml
  2003/kangraemin/app/src/main/res/values/dimens.xml
  2003/kangraemin/app/src/main/res/values/strings.xml
  2003/kangraemin/app/src/main/res/values/styles.xml
Labels: Mentor Needed, Merge Needed

#513 HW-1 NaverMovieAPI Project
  2003/tjdwlsl1021/app/build.gradle
  2003/tjdwlsl1021/app/src/main/AndroidManifest.xml
  2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/MainActivity.kt
  2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/activity/SearchMovieActivity.kt
  2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/adapter/SearchMovieAdapter.kt
  2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/item/SearchMovieInfo.kt
  2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/item/SearchMovieItem.kt
  2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/network/RetrofitHelper.kt
  2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/network/SearchMovieServerURL.kt
  2003/tjdwlsl1021/app/src/main/res/layout/activity_main.xml
  2003/tjdwlsl1021/app/src/main/res/layout/activity_search_movie.xml
  2003/tjdwlsl1021/app/src/main/res/layout/item_movie.xml
  2003/tjdwlsl1021/app/src/main/res/values/strings.xml
  2003/tjdwlsl1021/build.gradle
  class06/doubleclutch30/create readme.
Labels: Mentor Needed, Merge Needed

#512 HW-1 NaverMovieAPI Project
  2003/byiryu/app/build.gradle
  2003/byiryu/app/src/main/AndroidManifest.xml
  2003/byiryu/app/src/main/java/com/byiryu/study/MainActivity.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/api/Apis.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/api/model/MovieItem.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/api/model/MovieResponse.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/conf/AppConf.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/network/NetworkService.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/BaseActivity.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/MainActivity.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/MainRecyclerAdapter.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/MainRecyclerHolder.kt
  2003/byiryu/app/src/main/res/drawable/view_border.xml
  2003/byiryu/app/src/main/res/layout/activity_main.xml
  2003/byiryu/app/src/main/res/layout/view_main_item.xml
  2003/byiryu/app/src/main/res/values/colors.xml
  2003/byiryu/app/src/main/res/values/dimens.xml
  2003/byiryu/app/src/main/res/values/strings.xml
  2003/byiryu/app/src/main/res/values/styles.xml
  2003/byiryu/build.gradle
Labels: Mentor Needed, Merge Needed

#489 HW-5 DataBinding 적용
  doubleclutch30/ArchitectureStudy/app/build.gradle
  doubleclutch30/ArchitectureStudy/app/src/main/AndroidManifest.xml
  doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/MainActivity.kt
  doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/local/Dao/BlogDao.kt
  doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/local/Dao/ImageDao.kt
  doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/local/Dao/KinDao.kt
  doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/local/Dao/MovieDao.kt
  doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/local/NaverDataBase.kt
  doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/local/dao/BlogDao.kt
  doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/local/dao/ImageDao.kt
  doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/local/dao/KinDao.kt
  doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/local/dao/MovieDao.kt
  doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/local/entity/BlogEntity.kt
  doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/local/entity/ImageEntity.kt
  doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/local/entity/KinEntity.kt
  doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/local/entity/MovieEntity.kt
  doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/model/BlogItem.kt
  doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/model/ImageItem.kt
  doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/model/KinItem.kt
  doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/model/MovieItem.kt
  doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/repository/NaverSearchRepository.kt
  doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/repository/NaverSearchRepositoryImpl.kt
  doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/source/local/NaverSearchLocalDataSource.kt
  doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/source/local/NaverSearchLocalDataSourceImpl.kt
  doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/source/remote/NaverSearchRemoteDataSource.kt
  doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/data/source/remote/NaverSearchRemoteDataSourceImpl.kt
  doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ext/ImageViewExt.kt
  doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ext/TextViewExt.kt
  doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/network/Api.kt
  doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/network/ApiClient.kt
  doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/WebViewActivity.kt
  doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/blog/BlogAdapter.kt
  doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/blog/BlogContract.kt
  doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/blog/BlogFragment.kt
  doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/blog/BlogPresenter.kt
  doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/image/ImageAdapter.kt
  doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/image/ImageContract.kt
  doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/image/ImageFragment.kt
  doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/image/ImagePresenter.kt
  doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/kin/KinAdapter.kt
  doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/kin/KinContract.kt
  doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/kin/KinFragment.kt
  doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/kin/KinPresenter.kt
  doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/movie/MovieAdapter.kt
  doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/movie/MovieContract.kt
  doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/movie/MovieFragment.kt
  doubleclutch30/ArchitectureStudy/app/src/main/java/com/example/architecturestudy/ui/movie/MoviePresenter.kt
  doubleclutch30/ArchitectureStudy/app/src/main/res/layout/activity_main.xml
  doubleclutch30/ArchitectureStudy/app/src/main/res/layout/activity_webview.xml
  doubleclutch30/ArchitectureStudy/app/src/main/res/layout/fragment_blog.xml
  doubleclutch30/ArchitectureStudy/app/src/main/res/layout/fragment_image.xml
  doubleclutch30/ArchitectureStudy/app/src/main/res/layout/fragment_kin.xml
  doubleclutch30/ArchitectureStudy/app/src/main/res/layout/fragment_movie.xml
  doubleclutch30/ArchitectureStudy/app/src/main/res/layout/item_blog.xml
  doubleclutch30/ArchitectureStudy/app/src/main/res/layout/item_image.xml
  doubleclutch30/ArchitectureStudy/app/src/main/res/layout/item_kin.xml
  doubleclutch30/ArchitectureStudy/app/src/main/res/layout/item_movie.xml
  doubleclutch30/ArchitectureStudy/build.gradle
Labels: Mentor Needed, Merge Needed

#525 HW-2 네이버 영화검색 앱 Model 추가
  2003/mtjin/AndroidArchitectureStudy/app/build.gradle
  2003/mtjin/AndroidArchitectureStudy/app/src/main/AndroidManifest.xml
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/api/ApiInterface.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/data/Movie.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/data/source/MovieRepository.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/data/source/MovieRepositoryImpl.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/data/source/local/MovieDao.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/data/source/local/MovieDatabase.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/data/source/local/MovieLocalDataSource.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/data/source/local/MovieLocalDataSourceImpl.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/data/source/remote/MovieRemoteDataSource.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/data/source/remote/MovieRemoteDataSourceImpl.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/EndlessRecyclerViewScrollListener.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/MovieAdapter.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/MovieSearchActivity.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/utils/MyApplication.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/utils/NetworkManager.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/res/layout/activity_movie_search.xml
  2003/mtjin/AndroidArchitectureStudy/gradle.properties
Labels: Mentor Needed, Merge Needed

#527 HW-2 Model - Repository Pattern
  2003/byiryu/app/build.gradle
  2003/byiryu/app/src/main/AndroidManifest.xml
  2003/byiryu/app/src/main/java/com/byiryu/study/conf/AppConf.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/model/Apis.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/model/Repository.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/model/data/MovieItem.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/model/data/MovieResponse.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/model/local/LocalDataBase.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/model/local/LocalDataSource.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/model/local/MovieDao.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/model/local/pref/AppPreference.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/model/remote/RemoteDataSource.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/network/NetworkService.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/BRApplication.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/BaseActivity.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/base/BaseActivity.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/intro/IntroActivity.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/login/LoginActivity.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/main/MainActivity.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/main/MainRecyclerAdapter.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/main/MainRecyclerHolder.kt
  2003/byiryu/app/src/main/res/layout/activity_intro.xml
  2003/byiryu/app/src/main/res/layout/activity_login.xml
  2003/byiryu/app/src/main/res/values/colors.xml
  2003/byiryu/app/src/main/res/values/strings.xml
  2003/byiryu/build.gradle
Labels: Mentor Needed, Review Needed

#526 HW-2 Using repository & models
  2003/kangraemin/app/build.gradle
  2003/kangraemin/app/src/main/java/com/example/kangraemin/LoginActivity.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/MainActivity.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/adapter/SearchResultAdapter.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/model/AppDatabase.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/model/AuthRepository.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/model/MovieSearchRepository.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/model/local/datadao/AuthDao.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/model/local/datadao/AuthLocalDataSource.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/model/local/datadao/AuthLocalDataSourceImpl.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/model/local/datadao/LocalMovieDataSource.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/model/local/datadao/LocalMovieDataSourceImpl.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/model/local/datadao/MovieDao.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/model/local/datamodel/AuthModel.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/model/local/datamodel/MovieModel.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/model/remote/datadao/MovieApi.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/model/remote/datadao/MovieRemoteDataSource.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/model/remote/datadao/MovieRemoteDataSourceImpl.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/model/remote/datamodel/MovieDetail.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/util/RetrofitClient.kt
Labels: Mentor Needed, Merge Needed

#528 HW-2 Model - Repository Pattern
  2003/tjdwlsl1021/app/build.gradle
  2003/tjdwlsl1021/app/src/main/AndroidManifest.xml
  2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/activity/SearchMovieActivity.kt
  2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/adapter/SearchMovieAdapter.kt
  2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/data/local/MovieDao.kt
  2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/data/local/MovieDatabase.kt
  2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/data/local/source/MovieLocalDataSource.kt
  2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/data/local/source/MovieLocalDataSourceImpl.kt
  2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/data/remote/MovieRemoteDataSource.kt
  2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/data/remote/MovieRemoteDataSourceImpl.kt
  2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/data/repository/MovieRepository.kt
  2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/data/repository/MovieRepositoryDataSet.kt
  2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/data/repository/MovieRepositoryImpl.kt
  2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/item/SearchMovieItem.kt
  2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/model/MovieEntity.kt
  2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/model/SearchMovieInfoResponse.kt
  2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/network/NetworkService.kt
  2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/network/RequestNaverApi.kt
  2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/network/RetrofitHelper.kt
  2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/network/ServerURL.kt
  2003/tjdwlsl1021/build.gradle
Labels: Mentor Needed, Merge Needed

#523 HW-7 Koin 적용
  class08/devLibCH/Study/app/build.gradle
  class08/devLibCH/Study/app/src/main/java/app/ch/study/core/App.kt
  class08/devLibCH/Study/app/src/main/java/app/ch/study/data/local/source/NaverQueryLocalDataSource.kt
  class08/devLibCH/Study/app/src/main/java/app/ch/study/data/local/source/NaverQueryLocalDataSourceImpl.kt
  class08/devLibCH/Study/app/src/main/java/app/ch/study/data/remote/api/WebApiTask.kt
  class08/devLibCH/Study/app/src/main/java/app/ch/study/data/repository/NaverQueryRepository.kt
  class08/devLibCH/Study/app/src/main/java/app/ch/study/data/repository/NaverQueryRepositoryImpl.kt
  class08/devLibCH/Study/app/src/main/java/app/ch/study/di/ApiModule.kt
  class08/devLibCH/Study/app/src/main/java/app/ch/study/di/NetworkModule.kt
  class08/devLibCH/Study/app/src/main/java/app/ch/study/di/RepositoryModule.kt
  class08/devLibCH/Study/app/src/main/java/app/ch/study/di/ViewModelModule.kt
  class08/devLibCH/Study/app/src/main/java/app/ch/study/ui/main/view/MainActivity.kt
  class08/devLibCH/Study/app/src/main/java/app/ch/study/ui/main/viewmodel/MainViewModel.kt
Labels: Mentor Needed, Merge Needed

#530 HW-3 MVP
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/SASplashActivity.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/SASplashContractor.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/SASplashPresenter.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/base/SAActivity.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/base/SABasePresenter.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/base/SABaseView.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/login/SALoginActivity.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/login/SALoginContractor.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/login/SALoginPresenter.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/movie/SAMovieSearchActivity.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/movie/SAMovieSearchContractor.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/movie/SAMovieSearchPresenter.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/movie/adapter/SAMovieSearchResultAdapter.kt
Labels: Mentor Needed, Merge Needed

#533 HW-3 MVP 적용
  2003/byiryu/.idea/codeStyles/Project.xml
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/base/BaseActivity.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/base/BaseContract.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/base/BasePresenter.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/intro/IntroActivity.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/intro/IntroContract.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/intro/IntroPresenter.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/login/LoginActivity.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/login/LoginContract.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/login/LoginPresenter.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/main/MainActivity.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/main/MainConract.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/main/MainPresenter.kt
Labels: Mentor Needed, Merge Needed

#531 HW-3 Use MVP pattern
  2003/kangraemin/app/src/main/AndroidManifest.xml
  2003/kangraemin/app/src/main/java/com/example/kangraemin/LoginActivity.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/MainActivity.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/SplashActivity.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/base/KangBaseActivity.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/base/KangBasePresenter.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/model/MovieSearchRepository.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginActivity.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginContract.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginPresenter.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/main/MainActivity.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/main/MainContract.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/main/MainPresenter.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/splash/SplashActivity.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/splash/SplashContract.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/splash/SplashPresenter.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/util/NetworkUtil.kt
  2003/kangraemin/app/src/main/res/layout/activity_login.xml
  2003/kangraemin/app/src/main/res/layout/activity_main.xml
  2003/kangraemin/app/src/main/res/layout/activity_splash.xml
  2003/kangraemin/app/src/main/res/values/strings.xml
Labels: Mentor Needed, Merge Needed

#536 Feat: add Profile Link, add Personal room(개인공간생성)
  2004/README.md
  2004/taeseongyun/README.md
Labels: Mentor Needed, Merge Needed

#538 사전과제 완료
  2004/README.md
  2004/eunjin-hong/README.md
Labels: Mentor Needed, Merge Needed

#539 HW-4 DataBinding
  2003/sooakim/app/build.gradle
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/SASplashActivity.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/SASplashPresenter.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/base/SAActivity.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/base/SABasePresenter.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/login/SALoginActivity.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/movie/SAMovieSearchActivity.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/movie/SAMovieSearchPresenter.kt
  2003/sooakim/app/src/main/res/layout/activity_login.xml
  2003/sooakim/app/src/main/res/layout/activity_movie_search.xml
Labels: Mentor Needed, Merge Needed

#537 사전과제 완료
  2004/README.md
  2004/nukeolaf/README.md
Labels: Mentor Needed, Merge Needed

#544 Update README.md
  2004/README.md
  2004/jesterz91/README.md
Labels: Mentor Needed, Merge Needed

#540 사전과제 완료
  2004/README.md
  2004/kyudong3/README.md
Labels: Mentor Needed, Merge Needed

#541 HW-4 DataBinding
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/base/SARecyclerViewAdapter.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/base/SAViewHolder.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/ui/movie/adapter/SAMovieSearchResultAdapter.kt
  2003/sooakim/app/src/main/java/io/github/sooakim/util/ext/ImageView.kt
  2003/sooakim/app/src/main/res/layout/item_movie_search_result.xml
Labels: Mentor Needed, Merge Needed

#545 HW-4 DataBinding
  2003/tjdwlsl1021/app/build.gradle
  2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/data/local/MovieEntity.kt
  2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/ui/SearchMovieActivity.kt
  2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/ui/SearchMovieAdapter.kt
  2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/util/bindImage.kt
  2003/tjdwlsl1021/app/src/main/java/com/example/myapplication/util/toHtml.kt
  2003/tjdwlsl1021/app/src/main/res/layout/activity_search_movie.xml
  2003/tjdwlsl1021/app/src/main/res/layout/item_movie.xml
  2003/tjdwlsl1021/app/src/main/res/values/strings.xml
Labels: Mentor Needed, Merge Needed

#547 HW-4 Databindng 적용
  2003/byiryu/app/build.gradle
  2003/byiryu/app/src/main/java/com/byiryu/study/model/Repository.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/base/BaseActivity.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/intro/IntroActivity.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/login/LoginActivity.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/main/MainActivity.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/main/MainConract.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/main/MainPresenter.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/main/MainRecyclerAdapter.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/ui/main/MainRecyclerHolder.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/util/BindingAdapter.kt
  2003/byiryu/app/src/main/java/com/byiryu/study/wigets/OnViewClickListener.kt
  2003/byiryu/app/src/main/res/layout/activity_intro.xml
  2003/byiryu/app/src/main/res/layout/activity_login.xml
  2003/byiryu/app/src/main/res/layout/activity_main.xml
  2003/byiryu/app/src/main/res/layout/view_main_item.xml
  2003/byiryu/build.gradle
  2003/byiryu/gradle/wrapper/gradle-wrapper.properties
Labels: Mentor Needed, Merge Needed

#542 add invitejay space, update default README
  2004/README.md
  2004/invitejay/README.md
Labels: Mentor Needed, Merge Needed

#543 HW-4 DataBinding 적용
  2003/mtjin/AndroidArchitectureStudy/app/build.gradle
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/login/LoginActivity.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/search/MovieAdapter.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/ui/search/MovieSearchActivity.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/java/com/mtjin/androidarchitecturestudy/utils/DataBindingAdapters.kt
  2003/mtjin/AndroidArchitectureStudy/app/src/main/res/layout/activity_login.xml
  2003/mtjin/AndroidArchitectureStudy/app/src/main/res/layout/activity_movie_search.xml
  2003/mtjin/AndroidArchitectureStudy/app/src/main/res/layout/item_movie.xml
  2003/mtjin/AndroidArchitectureStudy/app/src/main/res/values/strings.xml
Labels: Mentor Needed, Merge Needed

#546 HW-4 Use databinding
  2003/kangraemin/app/build.gradle
  2003/kangraemin/app/src/main/java/com/example/kangraemin/adapter/SearchResultAdapter.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/login/LoginActivity.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/ui/main/MainActivity.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/util/BIndingAdapter.kt
  2003/kangraemin/app/src/main/java/com/example/kangraemin/util/Utils.kt
  2003/kangraemin/app/src/main/res/layout/activity_login.xml
  2003/kangraemin/app/src/main/res/layout/activity_main.xml
  2003/kangraemin/app/src/main/res/layout/adapter_search_result.xml
Labels: Mentor Needed, Merge Needed

#554 Create new project
  2004/nukeolaf/.gitignore
  2004/nukeolaf/.idea/codeStyles/Project.xml
  2004/nukeolaf/.idea/codeStyles/codeStyleConfig.xml
  2004/nukeolaf/.idea/runConfigurations.xml
  2004/nukeolaf/app/.gitignore
  2004/nukeolaf/app/build.gradle
  2004/nukeolaf/app/proguard-rules.pro
  2004/nukeolaf/app/src/androidTest/java/com/olaf/nukeolaf/ExampleInstrumentedTest.kt
  2004/nukeolaf/app/src/main/AndroidManifest.xml
  2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/MainActivity.kt
  2004/nukeolaf/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  2004/nukeolaf/app/src/main/res/drawable/ic_launcher_background.xml
  2004/nukeolaf/app/src/main/res/layout/activity_main.xml
  2004/nukeolaf/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  2004/nukeolaf/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  2004/nukeolaf/app/src/main/res/mipmap-hdpi/ic_launcher.png
  2004/nukeolaf/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  2004/nukeolaf/app/src/main/res/mipmap-mdpi/ic_launcher.png
  2004/nukeolaf/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  2004/nukeolaf/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  2004/nukeolaf/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  2004/nukeolaf/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  2004/nukeolaf/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  2004/nukeolaf/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  2004/nukeolaf/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  2004/nukeolaf/app/src/main/res/values/colors.xml
  2004/nukeolaf/app/src/main/res/values/strings.xml
  2004/nukeolaf/app/src/main/res/values/styles.xml
  2004/nukeolaf/app/src/test/java/com/olaf/nukeolaf/ExampleUnitTest.kt
  2004/nukeolaf/build.gradle
  2004/nukeolaf/gradle.properties
  2004/nukeolaf/gradle/wrapper/gradle-wrapper.jar
  2004/nukeolaf/gradle/wrapper/gradle-wrapper.properties
  2004/nukeolaf/gradlew
  2004/nukeolaf/gradlew.bat
  2004/nukeolaf/settings.gradle
  class06/doubleclutch30/create readme.
Labels: Mentor Needed, Merge Needed

#548 Create New Project
  2004/eunjin-hong/.gitignore
  2004/eunjin-hong/.idea/codeStyles/Project.xml
  2004/eunjin-hong/.idea/codeStyles/codeStyleConfig.xml
  2004/eunjin-hong/.idea/runConfigurations.xml
  2004/eunjin-hong/app/.gitignore
  2004/eunjin-hong/app/build.gradle
  2004/eunjin-hong/app/proguard-rules.pro
  2004/eunjin-hong/app/src/androidTest/java/com/eunice/eunicehong/ExampleInstrumentedTest.kt
  2004/eunjin-hong/app/src/main/AndroidManifest.xml
  2004/eunjin-hong/app/src/main/java/com/eunice/eunicehong/MainActivity.kt
  2004/eunjin-hong/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  2004/eunjin-hong/app/src/main/res/drawable/ic_launcher_background.xml
  2004/eunjin-hong/app/src/main/res/layout/activity_main.xml
  2004/eunjin-hong/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  2004/eunjin-hong/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  2004/eunjin-hong/app/src/main/res/mipmap-hdpi/ic_launcher.png
  2004/eunjin-hong/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  2004/eunjin-hong/app/src/main/res/mipmap-mdpi/ic_launcher.png
  2004/eunjin-hong/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  2004/eunjin-hong/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  2004/eunjin-hong/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  2004/eunjin-hong/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  2004/eunjin-hong/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  2004/eunjin-hong/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  2004/eunjin-hong/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  2004/eunjin-hong/app/src/main/res/values/colors.xml
  2004/eunjin-hong/app/src/main/res/values/strings.xml
  2004/eunjin-hong/app/src/main/res/values/styles.xml
  2004/eunjin-hong/app/src/test/java/com/eunice/eunicehong/ExampleUnitTest.kt
  2004/eunjin-hong/build.gradle
  2004/eunjin-hong/gradle.properties
  2004/eunjin-hong/gradle/wrapper/gradle-wrapper.jar
  2004/eunjin-hong/gradle/wrapper/gradle-wrapper.properties
  2004/eunjin-hong/gradlew
  2004/eunjin-hong/gradlew.bat
  2004/eunjin-hong/settings.gradle
Labels: Mentor Needed, Merge Needed

#552 init project
  2004/jesterz91/.gitignore
  2004/jesterz91/app/.gitignore
  2004/jesterz91/app/build.gradle
  2004/jesterz91/app/proguard-rules.pro
  2004/jesterz91/app/src/main/AndroidManifest.xml
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/MainActivity.kt
  2004/jesterz91/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  2004/jesterz91/app/src/main/res/drawable/ic_launcher_background.xml
  2004/jesterz91/app/src/main/res/layout/activity_main.xml
  2004/jesterz91/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  2004/jesterz91/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  2004/jesterz91/app/src/main/res/mipmap-hdpi/ic_launcher.png
  2004/jesterz91/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  2004/jesterz91/app/src/main/res/mipmap-mdpi/ic_launcher.png
  2004/jesterz91/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  2004/jesterz91/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  2004/jesterz91/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  2004/jesterz91/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  2004/jesterz91/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  2004/jesterz91/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  2004/jesterz91/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  2004/jesterz91/app/src/main/res/values/colors.xml
  2004/jesterz91/app/src/main/res/values/strings.xml
  2004/jesterz91/app/src/main/res/values/styles.xml
  2004/jesterz91/build.gradle
  2004/jesterz91/gradle.properties
  2004/jesterz91/gradle/wrapper/gradle-wrapper.jar
  2004/jesterz91/gradle/wrapper/gradle-wrapper.properties
  2004/jesterz91/gradlew
  2004/jesterz91/gradlew.bat
  2004/jesterz91/settings.gradle
Labels: Mentor Needed, Merge Needed
