Repository StudyFork/GoogryAndroidArchitectureStudy, pull requests merged in 2020-05, with the labels that each got.

#618 HW-1 NAVER API로 영화 검색 앱 만들기
  2005/sangjinKIM93/newproject/.idea/codeStyles/Project.xml
  2005/sangjinKIM93/newproject/.idea/gradle.xml
  2005/sangjinKIM93/newproject/app/build.gradle
  2005/sangjinKIM93/newproject/app/src/main/AndroidManifest.xml
  2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MainActivity.kt
  2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MovieListActivity.kt
  2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/RetrofitService.kt
  2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/adapter/Movie.kt
  2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/adapter/MovieListAdapter.kt
  2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/adapter/MovieListViewHolder.kt
  2005/sangjinKIM93/newproject/app/src/main/res/drawable-v24/img_default.png
  2005/sangjinKIM93/newproject/app/src/main/res/layout/activity_main.xml
  2005/sangjinKIM93/newproject/app/src/main/res/layout/activity_movie_list.xml
  2005/sangjinKIM93/newproject/app/src/main/res/layout/item_movie.xml
  2005/sangjinKIM93/newproject/app/src/main/res/values/strings.xml
Labels: Mentor Needed, Merge Needed

#621 HW-4 Add Databinding
  2004/invitejay/app/build.gradle
  2004/invitejay/app/src/main/java/com/example/studyforkandroid/adapter/MovieAdapter.kt
  2004/invitejay/app/src/main/java/com/example/studyforkandroid/ext/AppcompatActivityExt.kt
  2004/invitejay/app/src/main/java/com/example/studyforkandroid/ext/ImageViewExt.kt
  2004/invitejay/app/src/main/java/com/example/studyforkandroid/ext/StringUtils.kt
  2004/invitejay/app/src/main/java/com/example/studyforkandroid/ui/MainActivity.kt
  2004/invitejay/app/src/main/res/layout/activity_main.xml
  2004/invitejay/app/src/main/res/layout/item_movie.xml
Labels: Mentor Needed, Merge Needed

#622 과제1 네이버 영화 검색 앱
  2005/RyuC0605/Android_X/app/build.gradle
  2005/RyuC0605/Android_X/app/src/main/AndroidManifest.xml
  2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/MainActivity.kt
  2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/networks/NaverApi.kt
  2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/networks/RetrofitClient.kt
  2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/vo/Item.kt
  2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/vo/MovieVo.kt
  2005/RyuC0605/Android_X/app/src/main/res/drawable/no_image.png
  2005/RyuC0605/Android_X/app/src/main/res/layout/activity_main.xml
  2005/RyuC0605/Android_X/app/src/main/res/layout/layout_main_top.xml
  2005/RyuC0605/Android_X/app/src/main/res/layout/row_content.xml
  2005/RyuC0605/Android_X/app/src/main/res/values-ko/strings.xml
  2005/RyuC0605/Android_X/app/src/main/res/values/dimens.xml
  2005/RyuC0605/Android_X/app/src/main/res/values/strings.xml
  2005/RyuC0605/Android_X/build.gradle
Labels: Mentor Needed, Merge Needed

#617 HW-1 네이버API로 영화 검색
  2005/chuuuul/ArchitectureStudy/app/build.gradle
  2005/chuuuul/ArchitectureStudy/app/src/main/AndroidManifest.xml
  2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/ConstValue.kt
  2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/MainActivity.kt
  2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/activity/search/MovieListAdapter.kt
  2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/activity/search/SearchActivity.kt
  2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/retrofit/MovieSearchService.kt
  2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/vo/MovieResponseVO.kt
  2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/vo/MovieVO.kt
  2005/chuuuul/ArchitectureStudy/app/src/main/res/drawable-v24/ic_loading_black_24dp.xml
  2005/chuuuul/ArchitectureStudy/app/src/main/res/drawable/image_loaderror.xml
  2005/chuuuul/ArchitectureStudy/app/src/main/res/layout/activity_main.xml
  2005/chuuuul/ArchitectureStudy/app/src/main/res/layout/activity_search.xml
  2005/chuuuul/ArchitectureStudy/app/src/main/res/layout/item_movie.xml
  2005/chuuuul/ArchitectureStudy/app/src/main/res/values/strings.xml
  2005/chuuuul/ArchitectureStudy/build.gradle
  2005/chuuuul/ArchitectureStudy/gradle.properties
Labels: Mentor Needed, Merge Needed

#616 HW-1 Naver API를 이용한 영화 검색 리스트 구현
  2005/developer-sungjae/ArchitectureStudy/app/build.gradle
  2005/developer-sungjae/ArchitectureStudy/app/src/main/AndroidManifest.xml
  2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/MainActivity.kt
  2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/activities/MainActivity.kt
  2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/adapters/SearchAdapter.kt
  2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/components/Constants.kt
  2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/components/ExtensionFunc.kt
  2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/components/RetrofitService.kt
  2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/models/MovieData.kt
  2005/developer-sungjae/ArchitectureStudy/app/src/main/res/drawable-anydpi/ic_no_resource.xml
  2005/developer-sungjae/ArchitectureStudy/app/src/main/res/drawable-hdpi/ic_no_resource.png
  2005/developer-sungjae/ArchitectureStudy/app/src/main/res/drawable-mdpi/ic_no_resource.png
  2005/developer-sungjae/ArchitectureStudy/app/src/main/res/drawable-xhdpi/ic_no_resource.png
  2005/developer-sungjae/ArchitectureStudy/app/src/main/res/drawable-xxhdpi/ic_no_resource.png
  2005/developer-sungjae/ArchitectureStudy/app/src/main/res/layout/activity_main.xml
  2005/developer-sungjae/ArchitectureStudy/app/src/main/res/layout/movie_item.xml
  2005/developer-sungjae/ArchitectureStudy/app/src/main/res/values/strings.xml
  2005/developer-sungjae/ArchitectureStudy/app/src/main/res/values/styles.xml
  2005/developer-sungjae/ArchitectureStudy/build.gradle
  2005/developer-sungjae/ArchitectureStudy/gradle.properties
Labels: Mentor Needed, Merge Needed

#615 HW-4 DataBinding 적용
  2004/taeseongyun/app/build.gradle
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/base/BaseActivity.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/base/BaseContract.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/base/BasePresenter.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/base/BaseRecyclerAdapter.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/base/BaseRecyclerViewHolder.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/binding/ViewBindingAdapter.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/constant/Const.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/eventbus/RxEventBus.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/eventbus/RxEventBusImpl.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ext/ToastExt.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ext/ViewExt.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/presenter/MovieContract.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/presenter/MoviePresenter.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/MainActivity.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/adapter/MovieRecyclerAdapter.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/viewholder/MovieRecyclerViewViewHolder.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/util/widget/DebounceClickListener.kt
  2004/taeseongyun/app/src/main/res/layout/activity_main.xml
  2004/taeseongyun/app/src/main/res/layout/movie_recycler_item.xml
  2004/taeseongyun/app/src/main/res/values/strings.xml
Labels: Mentor Needed, Merge Needed

#625 HW-4 DataBinding 적용
  2004/nukeolaf/app/build.gradle
  2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/ui/BindingAdapter.kt
  2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/ui/MainActivity.kt
  2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/ui/MovieAdapter.kt
  2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/ui/MovieItemViewHolder.kt
  2004/nukeolaf/app/src/main/res/layout/activity_main.xml
  2004/nukeolaf/app/src/main/res/layout/item_movies_rv.xml
Labels: Mentor Needed, Merge Needed

#627 HW-4 DataBinding
  2004/jesterz91/app/build.gradle
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/common/BaseViewHolder.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/extension/ImageViewExtension.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/extension/RecyclerViewExtension.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/extension/TextViewExtension.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/ui/MovieSearchActivity.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/ui/MovieSearchViewHolder.kt
  2004/jesterz91/app/src/main/res/layout/activity_movie_search.xml
  2004/jesterz91/app/src/main/res/layout/item_movie.xml
  2004/jesterz91/build.gradle
Labels: Mentor Needed, Merge Needed

#620 HW-1 Naver Api 사용한 영화검색 앱
  2005/leechungwoo92/StudyForkProject/.idea/gradle.xml
  2005/leechungwoo92/StudyForkProject/app/build.gradle
  2005/leechungwoo92/StudyForkProject/app/src/main/AndroidManifest.xml
  2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/ApiService.kt
  2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/Constants.kt
  2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/MainActivity.kt
  2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/SearchRetrofit.kt
  2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/model/Movie.kt
  2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/model/MovieItem.kt
  2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/view/activity/MainActivity.kt
  2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/view/adapter/MovieListAdapter.kt
  2005/leechungwoo92/StudyForkProject/app/src/main/res/drawable-v24/bg_edittext_red.xml
  2005/leechungwoo92/StudyForkProject/app/src/main/res/drawable/ic_no_img.xml
  2005/leechungwoo92/StudyForkProject/app/src/main/res/layout/activity_main.xml
  2005/leechungwoo92/StudyForkProject/app/src/main/res/layout/item_movie_list.xml
  2005/leechungwoo92/StudyForkProject/app/src/main/res/values/styles.xml
Labels: Mentor Needed, Merge Needed

#614 HW-1 NAVER_API
  2005/hwaniiidev/Architecture/.gitignore
  2005/hwaniiidev/Architecture/app/build.gradle
  2005/hwaniiidev/Architecture/app/src/main/AndroidManifest.xml
  2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/AdapterMovieList.kt
  2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/ApiCall.kt
  2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/MainActivity.kt
  2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/RetrofitService.kt
  2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/model/Item.kt
  2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/model/ResponseMovieSearchData.kt
  2005/hwaniiidev/Architecture/app/src/main/res/drawable/item_border.xml
  2005/hwaniiidev/Architecture/app/src/main/res/layout/activity_main.xml
  2005/hwaniiidev/Architecture/app/src/main/res/layout/item_movie_list.xml
  2005/hwaniiidev/Architecture/build.gradle
Labels: Mentor Needed, Merge Needed

#626 [HW-4] apply databinding
  2004/eunjin-hong/app/build.gradle
  2004/eunjin-hong/app/src/main/java/com/eunice/eunicehong/ext/ImageViewExtension.kt
  2004/eunjin-hong/app/src/main/java/com/eunice/eunicehong/ext/StringExtension.kt
  2004/eunjin-hong/app/src/main/java/com/eunice/eunicehong/ext/TextViewExtension.kt
  2004/eunjin-hong/app/src/main/java/com/eunice/eunicehong/ui/MainActivity.kt
  2004/eunjin-hong/app/src/main/java/com/eunice/eunicehong/ui/MovieAdapter.kt
  2004/eunjin-hong/app/src/main/java/com/eunice/eunicehong/ui/MovieContract.kt
  2004/eunjin-hong/app/src/main/java/com/eunice/eunicehong/ui/MovieListPresenter.kt
  2004/eunjin-hong/app/src/main/res/layout/activity_main.xml
  2004/eunjin-hong/app/src/main/res/layout/item_movie.xml
  2004/eunjin-hong/app/src/main/res/values/strings.xml
Labels: Mentor Needed, Merge Needed

#624 HW-4 apply Databinding
  2004/kyudong3/app/build.gradle
  2004/kyudong3/app/src/main/java/com/example/kyudong3/adapter/SearchMovieRvAdapter.kt
  2004/kyudong3/app/src/main/java/com/example/kyudong3/data/local/MovieDatabase.kt
  2004/kyudong3/app/src/main/java/com/example/kyudong3/extension/ImageViewExt.kt
  2004/kyudong3/app/src/main/java/com/example/kyudong3/ui/MainActivity.kt
  2004/kyudong3/app/src/main/res/layout/activity_main.xml
  2004/kyudong3/app/src/main/res/layout/item_movie.xml
Labels: Mentor Needed, Merge Needed

#628 2005/ryu c0605 hw1
  2005/RyuC0605/Android_X/app/build.gradle
  2005/RyuC0605/Android_X/app/src/main/AndroidManifest.xml
  2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/MainActivity.kt
  2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/networks/NaverApi.kt
  2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/networks/RetrofitClient.kt
  2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/vo/Item.kt
  2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/vo/MovieVo.kt
  2005/RyuC0605/Android_X/app/src/main/res/drawable/no_image.png
  2005/RyuC0605/Android_X/app/src/main/res/layout/activity_main.xml
  2005/RyuC0605/Android_X/app/src/main/res/layout/layout_main_top.xml
  2005/RyuC0605/Android_X/app/src/main/res/layout/row_content.xml
  2005/RyuC0605/Android_X/app/src/main/res/values-ko/strings.xml
  2005/RyuC0605/Android_X/app/src/main/res/values/dimens.xml
  2005/RyuC0605/Android_X/app/src/main/res/values/strings.xml
  2005/RyuC0605/Android_X/build.gradle
Labels: Review Needed

#637 HW5 - Apply MVVM
  2004/invitejay/app/src/main/java/com/example/studyforkandroid/base/BasePresenter.kt
  2004/invitejay/app/src/main/java/com/example/studyforkandroid/ext/BindingAdapterExt.kt
  2004/invitejay/app/src/main/java/com/example/studyforkandroid/presenter/MovieContract.kt
  2004/invitejay/app/src/main/java/com/example/studyforkandroid/presenter/MoviePresenter.kt
  2004/invitejay/app/src/main/java/com/example/studyforkandroid/ui/MainActivity.kt
  2004/invitejay/app/src/main/java/com/example/studyforkandroid/viewmodel/MovieViewModel.kt
  2004/invitejay/app/src/main/res/layout/activity_main.xml
Labels: Mentor Needed, Merge Needed

#629 HW-5 apply viewModel
  2004/eunjin-hong/app/build.gradle
  2004/eunjin-hong/app/src/main/java/com/eunice/eunicehong/data/source/MovieDataSource.kt
  2004/eunjin-hong/app/src/main/java/com/eunice/eunicehong/data/source/remote/MovieRemoteDataSource.kt
  2004/eunjin-hong/app/src/main/java/com/eunice/eunicehong/ext/CardViewExtension.kt
  2004/eunjin-hong/app/src/main/java/com/eunice/eunicehong/ext/SearchView.kt
  2004/eunjin-hong/app/src/main/java/com/eunice/eunicehong/ui/MainActivity.kt
  2004/eunjin-hong/app/src/main/java/com/eunice/eunicehong/ui/MovieAdapter.kt
  2004/eunjin-hong/app/src/main/java/com/eunice/eunicehong/ui/MovieCache.kt
  2004/eunjin-hong/app/src/main/java/com/eunice/eunicehong/ui/MovieContract.kt
  2004/eunjin-hong/app/src/main/java/com/eunice/eunicehong/ui/MovieListPresenter.kt
  2004/eunjin-hong/app/src/main/java/com/eunice/eunicehong/ui/MoviePreferences.kt
  2004/eunjin-hong/app/src/main/java/com/eunice/eunicehong/viewmodel/MainViewModel.kt
  2004/eunjin-hong/app/src/main/res/layout/activity_main.xml
  2004/eunjin-hong/app/src/main/res/layout/item_movie.xml
  2004/eunjin-hong/app/src/main/res/layout/item_movie_placeholder.xml
  2004/eunjin-hong/app/src/main/res/menu/menu_main.xml
  2004/eunjin-hong/app/src/main/res/values/colors.xml
  2004/eunjin-hong/app/src/main/res/values/styles.xml
  2004/eunjin-hong/gradle.properties
Labels: Answer Needed, Mentor Needed

#632 HW-5 MVVM 적용
  2004/kyudong3/app/src/main/java/com/example/kyudong3/adapter/SearchMovieRvAdapter.kt
  2004/kyudong3/app/src/main/java/com/example/kyudong3/extension/BindingAdapters.kt
  2004/kyudong3/app/src/main/java/com/example/kyudong3/extension/ImageViewExt.kt
  2004/kyudong3/app/src/main/java/com/example/kyudong3/ui/MainActivity.kt
  2004/kyudong3/app/src/main/java/com/example/kyudong3/ui/movie/presenter/MovieContract.kt
  2004/kyudong3/app/src/main/java/com/example/kyudong3/ui/movie/presenter/MoviePresenter.kt
  2004/kyudong3/app/src/main/java/com/example/kyudong3/viewModel/MainViewModel.kt
  2004/kyudong3/app/src/main/res/layout/activity_main.xml
Labels: Answer Needed, Mentor Needed

#639 HW-5 MVVM pattern
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/domain/entity/Result.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/common/BaseActivity.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/common/BaseContract.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/common/BaseViewModel.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/constant/Constant.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/extension/ViewExtension.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/ui/MovieSearchActivity.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/ui/MovieSearchAdapter.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/ui/MovieSearchContract.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/ui/MovieSearchPresenter.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/ui/MovieSearchViewModel.kt
  2004/jesterz91/app/src/main/res/layout/activity_movie_search.xml
  2004/jesterz91/app/src/main/res/layout/item_movie.xml
Labels: Answer Needed, Mentor Needed

#630 HW-5 ViewModel적용
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/base/BaseActivity.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/base/BaseRecyclerAdapter.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/base/BaseRecyclerViewHolder.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/base/RecyclerViewModel.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/binding/RecyclerViewBindingAdapter.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/binding/ViewBindingAdapter.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/constant/Const.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ext/ViewExt.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/provider/ResourceProvider.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/provider/ResourceProviderImpl.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/MainActivity.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/adapter/MovieRecyclerAdapter.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/observe/ObserverProvider.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/observe/ObserverProviderImpl.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/viewholder/MovieRecyclerViewViewHolder.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/viewmodel/BaseViewModel.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/viewmodel/MainViewModel.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/util/BackKeyPressExt.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/util/widget/DebounceClickListener.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/util/widget/ThrottleClickListener.kt
  2004/taeseongyun/app/src/main/res/layout/activity_main.xml
  2004/taeseongyun/app/src/main/res/layout/movie_recycler_item.xml
Labels: Mentor Needed, Merge Needed

#634 HW-5 MVVM 적용
  2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/ui/BindingAdapter.kt
  2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/ui/MainActivity.kt
  2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/ui/MainContract.kt
  2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/ui/MainPresenter.kt
  2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/ui/MainViewModel.kt
  2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/ui/MovieAdapter.kt
  2004/nukeolaf/app/src/main/java/com/olaf/nukeolaf/ui/MovieItemViewHolder.kt
  2004/nukeolaf/app/src/main/res/layout/activity_main.xml
  2004/nukeolaf/app/src/main/res/layout/item_movies_rv.xml
Labels: Answer Needed

#631 HW-2 Model 적용
  2005/chuuuul/ArchitectureStudy/.idea/inspectionProfiles/Project_Default.xml
  2005/chuuuul/ArchitectureStudy/.idea/runConfigurations.xml
  2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/ConstValue.kt
  2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/activity/search/MovieListAdapter.kt
  2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/activity/search/SearchActivity.kt
  2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/data/model/MovieModel.kt
  2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/data/model/MovieResponseModel.kt
  2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/data/repository/NaverRepository.kt
  2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/data/repository/NaverRepositoryImpl.kt
  2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/data/source/local/NaverLocalDataSource.kt
  2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/data/source/local/NaverLocalDataSourceImpl.kt
  2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/data/source/remote/NaverRemoteDataSource.kt
  2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/data/source/remote/NaverRemoteDataSourceImpl.kt
  2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/retrofit/MovieSearchService.kt
  2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/util/AppUtil.kt
  2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/util/ConstValue.kt
Labels: Mentor Needed, Merge Needed

#643 HW-6 Apply LiveData
  2004/invitejay/app/build.gradle
  2004/invitejay/app/src/main/java/com/example/studyforkandroid/ui/MainActivity.kt
  2004/invitejay/app/src/main/java/com/example/studyforkandroid/viewmodel/MovieViewModel.kt
Labels: Mentor Needed, Merge Needed

#633 HW-2 Model 적용
  2005/developer-sungjae/ArchitectureStudy/app/build.gradle
  2005/developer-sungjae/ArchitectureStudy/app/src/main/AndroidManifest.xml
  2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/activities/MainActivity.kt
  2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/adapters/SearchAdapter.kt
  2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/components/Constants.kt
  2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/components/NaverApiService.kt
  2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/components/Retrofit.kt
  2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/components/RetrofitService.kt
  2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/model/MovieItem.kt
  2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/model/NaverApiData.kt
  2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/repository/NaverMovieRepository.kt
  2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/repository/NaverMovieRepositoryImpl.kt
  2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/local/NaverMovieLocalDataSource.kt
  2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/local/NaverMovieLocalDataSourceImpl.kt
  2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/local/room/MovieItemDao.kt
  2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/local/room/MovieLocalItem.kt
  2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/local/room/MovieRoomDataBase.kt
  2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/remote/NaverMovieRemoteDataSource.kt
  2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/remote/NaverMovieRemoteDataSourceImpl.kt
  2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/models/MovieData.kt
  2005/developer-sungjae/ArchitectureStudy/app/src/main/res/drawable/img_logo.png
  2005/developer-sungjae/ArchitectureStudy/app/src/main/res/layout/activity_main.xml
  2005/developer-sungjae/ArchitectureStudy/app/src/main/res/values/strings.xml
  2005/developer-sungjae/ArchitectureStudy/build.gradle
Labels: Mentor Needed, Merge Needed

#638 HW-2 Model 적용
  2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/ApiService.kt
  2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/data/model/Movie.kt
  2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/data/model/MovieItem.kt
  2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/data/repository/NaverMovieRepository.kt
  2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/data/repository/NaverMovieRepositoryImpl.kt
  2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/data/source/remote/MovieRemoteDataSource.kt
  2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/data/source/remote/MovieRemoteDataSourceImpl.kt
  2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/view/activity/MainActivity.kt
  2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/view/adapter/MovieListAdapter.kt
Labels: Mentor Needed, Merge Needed

#635 HW-2 Model 적용
  2005/sangjinKIM93/newproject/app/build.gradle
  2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MovieListActivity.kt
  2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/RetrofitService.kt
  2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/adapter/Movie.kt
  2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/adapter/MovieListAdapter.kt
  2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/data/model/Movie.kt
  2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/data/model/NaverMovieResponse.kt
  2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/data/repository/NaverMoviesRepository.kt
  2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/data/repository/NaverMoviesRepositoryImpl.kt
  2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/data/source/local/LocalDataSource.kt
  2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/data/source/local/LocalDataSourceImpl.kt
  2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/data/source/local/MovieDao.kt
  2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/data/source/local/RoomDb.kt
  2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/data/source/remote/RemoteDataSource.kt
  2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/data/source/remote/RemoteDataSourceImpl.kt
Labels: Mentor Needed, Merge Needed

#642 HW-2 Model 적용
  2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/MainActivity.kt
  2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/data/model/MovieVo.kt
  2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/data/repository/MovieRepository.kt
  2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/data/repository/MovieRepositoryImpl.kt
  2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/data/source/remote/NaverRemoteDataSource.kt
  2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/data/source/remote/NaverRemoteDataSourceImpl.kt
  2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/networks/ImageLoader.kt
  2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/networks/NaverApi.kt
  2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/vo/Item.kt
  2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/vo/MovieVo.kt
Labels: Mentor Needed, Merge Needed

#640 HW-6 apply Lifecycle & AAC ViewModel
  2004/taeseongyun/app/build.gradle
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/base/BaseActivity.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ext/SingleLiveData.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ext/ViewExt.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/MainActivity.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/viewmodel/BaseViewModel.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/ui/viewmodel/MainViewModel.kt
  2004/taeseongyun/app/src/main/java/com/tsdev/tsandroid/util/BackKeyPressExt.kt
  2004/taeseongyun/app/src/main/res/layout/activity_main.xml
  2004/taeseongyun/dependency.gradle
Labels: Mentor Needed, Merge Needed

#636 HW-2 Model적용
  2005/hwaniiidev/Architecture/app/build.gradle
  2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/AdapterMovieList.kt
  2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/MainActivity.kt
  2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/data/repository/NaverMovieRepository.kt
  2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/data/repository/NaverMovieRepositoryImpl.kt
  2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/data/source/local/MoviesDB.kt
  2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/data/source/local/MoviesDao.kt
  2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/data/source/local/NaverMovieLocalDataSource.kt
  2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/data/source/local/NaverMovieLocalDataSourceImpl.kt
  2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/data/source/remote/NaverMovieRemoteDataSource.kt
  2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/data/source/remote/NaverMovieRemoteDataSourceImpl.kt
  2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/model/Item.kt
  2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/model/ResponseMovieSearchData.kt
  2005/hwaniiidev/Architecture/app/src/main/res/drawable-v24/gm_noimage.png
Labels: Mentor Needed, Merge Needed

#650 HW-3 MVP 적용
  2005/chuuuul/ArchitectureStudy/app/build.gradle
  2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/activity/search/MovieListAdapter.kt
  2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/activity/search/SearchActivity.kt
  2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/activity/search/SearchContract.kt
  2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/activity/search/SearchPresenter.kt
  2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/activity/search/adapter/MovieAdapter.kt
  2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/activity/search/adapter/MovieAdapterContract.kt
  2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/activity/search/adapter/MovieAdapterPresenter.kt
  2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/activity/search/adapter/MovieHolder.kt
  2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/activity/search/adapter/MovieHolderContract.kt
  2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/activity/search/adapter/MovieHolderPresenter.kt
  2005/chuuuul/ArchitectureStudy/app/src/main/java/com/example/architecture/data/repository/NaverRepositoryImpl.kt
  2005/chuuuul/ArchitectureStudy/app/src/main/res/layout/activity_search.xml
  2005/chuuuul/ArchitectureStudy/build.gradle
Labels: Mentor Needed, Merge Needed

#646 HW-3 MVP 적용
  2005/RyuC0605/Android_X/app/src/main/AndroidManifest.xml
  2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/MainActivity.kt
  2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/main/MainActivity.kt
  2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/main/MainContract.kt
  2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/main/MainPresenter.kt
  2005/RyuC0605/Android_X/app/src/main/java/r/test/rapp/main/MovieAdapter.kt
  2005/RyuC0605/Android_X/app/src/main/res/layout/activity_main.xml
  2005/RyuC0605/Android_X/app/src/main/res/layout/layout_main_top.xml
  2005/RyuC0605/Android_X/gradle/wrapper/gradle-wrapper.properties
Labels: Mentor Needed, Merge Needed

#652 HW-3 MVP패턴 적용
  2005/leechungwoo92/StudyForkProject/app/src/main/AndroidManifest.xml
  2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/ui/common/BaseContract.kt
  2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/ui/main/MainActivity.kt
  2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/ui/main/MainContract.kt
  2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/ui/main/MainPresenter.kt
  2005/leechungwoo92/StudyForkProject/app/src/main/java/com/lllccww/studyforkproject/ui/main/MovieListAdapter.kt
Labels: Mentor Needed, Merge Needed

#645 HW-3 MVC -> MVP
  2005/developer-sungjae/ArchitectureStudy/app/src/main/AndroidManifest.xml
  2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/activities/MainActivity.kt
  2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/components/Constants.kt
  2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/data/source/local/NaverMovieLocalDataSourceImpl.kt
  2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/ui/search/SearchActivity.kt
  2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/ui/search/SearchAdapter.kt
  2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/ui/search/SearchContract.kt
  2005/developer-sungjae/ArchitectureStudy/app/src/main/java/com/project/architecturestudy/ui/search/SearchPresenter.kt
  2005/developer-sungjae/ArchitectureStudy/app/src/main/res/layout/activity_search.xml
  2005/developer-sungjae/ArchitectureStudy/app/src/main/res/layout/movie_item.xml
  2005/developer-sungjae/ArchitectureStudy/app/src/main/res/values/strings.xml
Labels: Mentor Needed, Merge Needed

#651 HW-6 AAC ViewModel and LiveData
  2004/jesterz91/app/build.gradle
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/common/BaseActivity.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/common/BaseAdapter.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/common/BaseViewModel.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/extension/LifecycleOwnerExtension.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/extension/RecyclerViewExtension.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/ui/MovieSearchActivity.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/ui/MovieSearchAdapter.kt
  2004/jesterz91/app/src/main/java/io/github/jesterz91/study/presentation/ui/MovieSearchViewModel.kt
  2004/jesterz91/app/src/main/res/layout/activity_movie_search.xml
  2004/jesterz91/build.gradle
Labels: Mentor Needed, Merge Needed

#647 HW-6 apply LiveData & AAC viewModel
  2004/kyudong3/app/build.gradle
  2004/kyudong3/app/src/main/java/com/example/kyudong3/extension/BindingAdapters.kt
  2004/kyudong3/app/src/main/java/com/example/kyudong3/provider/ResourceProvider.kt
  2004/kyudong3/app/src/main/java/com/example/kyudong3/provider/ResourceProviderImpl.kt
  2004/kyudong3/app/src/main/java/com/example/kyudong3/ui/MainActivity.kt
  2004/kyudong3/app/src/main/java/com/example/kyudong3/viewModel/MainViewModel.kt
  2004/kyudong3/app/src/main/res/values/strings.xml
Labels: Mentor Needed, Merge Needed

#649 HW-3 MVP 패턴
  2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MovieListActivity.kt
  2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MovieListContract.kt
  2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/MovieListPresenter.kt
  2005/sangjinKIM93/newproject/app/src/main/java/com/sangjin/newproject/adapter/MovieListAdapter.kt
  2005/sangjinKIM93/newproject/app/src/main/res/layout/item_movie.xml
Labels: Mentor Needed, Merge Needed

#648 HW-3 Presenter 적용
  2005/hwaniiidev/Architecture/app/src/main/AndroidManifest.xml
  2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/MainActivity.kt
  2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/data/repository/NaverMovieRepository.kt
  2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/data/repository/NaverMovieRepositoryImpl.kt
  2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/data/source/local/NaverMovieLocalDataSource.kt
  2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/data/source/local/NaverMovieLocalDataSourceImpl.kt
  2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/data/source/remote/NaverMovieRemoteDataSource.kt
  2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/data/source/remote/NaverMovieRemoteDataSourceImpl.kt
  2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/ui/main/AdapterMovieList.kt
  2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/ui/main/MainActivity.kt
  2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/ui/main/MainContract.kt
  2005/hwaniiidev/Architecture/app/src/main/java/com/hwaniiidev/architecture/ui/main/MainPresenter.kt
  2005/hwaniiidev/Architecture/app/src/main/res/layout/activity_main.xml
Labels: Mentor Needed, Merge Needed
